### ISSUE TITLE
Weird span tags rendering

### ISSUE THREAD

**Issue by igorscaglia** [EnlighterJS/Plugin.WordPress#100]
Hi guys! 

I'm facing weird behavior when Enlighter trying to render out an entire Java class. Bellow is what is going on. 
![screen shot 2018-05-26 at 12 08 01](https://user-images.githubusercontent.com/25579554/40577529-878f07be-60dd-11e8-88df-6af22a83286f.png)

Do you guys know what I did wrong? I did the basics... copy the code from IDE, paste the code in the new post, set as Java code and save it. 

Thanks in advance for any response.

**Comment by AndiDittrich** [comment]
Hi igorscaglia,

please use the "Enlighter Code Insert Dialog"  as mentioned in the [docs](https://github.com/EnlighterJS/Plugin.WordPress/blob/master/docs/Usage_VisualEditor.md)

currently you're copying rich-text from your IDE (including the IDEs highlighting elements) into the WordPress editor - this wont work.

best regards, Andi
