### ISSUE TITLE
Can't change settings in visual editor

### ISSUE THREAD

**Issue by Sarah1101** [EnlighterJS/Plugin.WordPress#101]
I can't change settings in visual editor anymore. 
Example: When I add a point out line and press OK button the settings aren't saved.

**Comment by AndiDittrich** [comment]
Hi Sarah1101,

thanks four your report - i will check it asap.
did in only occur with the latest release ?

best regards, Andi

**Comment by AndiDittrich** [comment]
Hi Sarah1101,

i can confirm the issue. it seems to be an error within the TinyMCU extension. the code edit button on the toolbar works but the button on the upper right corner of each codeblock is broken.

**Comment by Sarah1101** [comment]
Hi Andi, 

I don't know when the error occured. 
I will use the button on the upper right corner meanwhile, thank you.

Best regards
Sarah

**Comment by AndiDittrich** [comment]
Hi Sarah1101,

the issue is fixed in the current beta (3.7 - github master branch) including EnlighterJS.TinyMCE v3.4.0

best regards, Andi
