### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by applegrew** [EnlighterJS/Plugin.WordPress#102]
Please check - https://blog.applegrew.com/2015/05/javascript-fundamentals-for-oop-developers/ I see that the codes are getting rendered correctly and the Enlighter JS file is being loaded. Is the CSS is missing somehow?

**Comment by AndiDittrich** [comment]
hi @applegrew ,

you didn't use the Enlighter formated code... it's legacy jetpack markdown or crayon generated code ?! you can use the compatibility mode to highlight such kind of code (don't forget to clear your servers cache WP-Super-Cache) but it's recommended to your the VisualEditor integration

**your code**
```html
<pre><code class="js">
function Car(color) {
   Vehicle.call(this, color);
   this.getWheelsCount = function () {
       return 4;
   };
}
Car.prototype = new Vehicle();
</code></pre>
```

**Enlighter code**
```html
<pre class="EnlighterJSRAW" data-enlighter-language="js">
function Car(color) {
   Vehicle.call(this, color);
   this.getWheelsCount = function () {
       return 4;
   };
}
Car.prototype = new Vehicle();
</pre>
```

**Comment by applegrew** [comment]
Yes I am using Jetpack provided Markdown. Anyway to use this plugin with
that?

**Comment by AndiDittrich** [comment]
use the Enlighter Compatibility-Mode (Settings Page)
