### ISSUE TITLE
Database config queries optimalization

### ISSUE THREAD

**Issue by OskarLebuda** [EnlighterJS/Plugin.WordPress#105]
| Component | Queries           | Time  |
| ------------- |:-------------:| -----:|
| Plugin: enlighter | 164 | 7.0154s |

As you can see. Your plugin makes **164 queries (!!)** to database while load! That's terrible!!

Install `Query monitor plugin` for Wordpress and check how many queries to database makes your plugin. Even when doesn't work - no highlight anything. All queries is to the options table where are configurations of the plugin. So you should change configurations of your plugin or think about something like cache...

**Comment by AndiDittrich** [comment]
Hi @OskarLebuda ,

thanks four your report and of course.. the current Enlighter version make excessive use of calls to the WordPress API via [get_option](https://developer.wordpress.org/reference/functions/get_option/). But this function is internally cached by WordPress itself (`autoload` flag). Over the years there are a whole bunch of options which have to be loaded....this has to be change in one of the next release :+1: 
I'm not shure why the Query Monitor shows you such a high amount of **querys** ... thats in total the number of **rows** (options) which are aggregated during the initialization..

### Caching ###
There are a lot of caching plugins available for WordPress which are widely used:
* **Redis,memcache** - option/database caching
* **WPSuperCache, WPTotalCache** - static content cache

therefore i won't add a custom cache layer to the current version (see next paragraph)

### Future Releases ###
The next major release v4 is based on the **WP-Skeleton** plugin framework (already used by [Cryptex](https://wordpress.org/plugins/cryptex/) and [Tweakr](https://wordpress.org/plugins/tweakr/)) which reduces the total amount of options to **5**.

best regards, And
