### ISSUE TITLE
Inline code display sizing

### ISSUE THREAD

**Issue by andraantariksa** [EnlighterJS/Plugin.WordPress#106]
Is this caused by my template font or what? I've tried to change my font and size but it won't change
![screenshot from 2018-06-26 12-40-59](https://user-images.githubusercontent.com/9760691/41891391-58218a1e-793e-11e8-8f5c-2aade996e88b.png)
http://blog.andra.systems/?p=114

**Comment by AndiDittrich** [comment]
Hi @andraantariksa ,

your blog is currently offline. the issue you've experienced is caused by your themes css: its overriding some Enlighter related styles (line-height/height) which cause this effect. take a look into your WebDeveloperTools.

bets regards, Andi

**Comment by andraantariksa** [comment]
Idk what, but removing font-size on EnlighterJS.min.css make it better
![screenshot from 2018-06-27 20-49-04](https://user-images.githubusercontent.com/9760691/41978337-d228fba4-7a4b-11e8-953d-26dce8e6e81d.png)
