### ISSUE TITLE
Add ChordPro support

### ISSUE THREAD

**Issue by glewe** [EnlighterJS/Plugin.WordPress#108]
Hi Andi,

I'd love to see ChordPro language support in your plugin. ChordPro is a simple text based syntax to create musical song sheets (text and chords). It is really simple. Read more about it here:
https://www.chordpro.org/chordpro/ChordPro-File-Format-Specification.html

I looked at your template .js file (https://github.com/EnlighterJS/EnlighterJS/blob/master/Source/Language/Template.mylang.js) but it is more related to a programming lanuage and I do not know how to change it to reflect the chordpro format.

I have created a tmLanguage file for VS Code that might help you adding it:
`{
	"information_for_contributors": [ "n/a" ],
	"version": "1.0.0",
	"name": "ChordPro",
	"scopeName": "source.chordpro",
   "patterns": [
      {
         "name": "markup.withparams.chordpro",
         "match": "(?i:(\\{)(title|subtitle|comment_italic|comment|define|textfont|textsize|chordfont|chordsize|columns|page_type|t|st|ci|c|col):(.+)(\\}))",
         "captures": {
            "2": { "name": "support.function.chordpro" },
            "3": { "name": "variable.parameter.chordpro"}
         }
      },
      {
         "name": "markup.noparams.chordpro",
         "match": "(?i:(\\{)(new_song|start_of_chorus|end_of_chorus|start_of_tab|end_of_tab|no_grid|grid|new_page|new_physical_page|column_break|ns|soc|eoc|sob|eob|ng|g|npp|np|colb|col)(\\}))",
         "captures": {
            "2": { "name": "support.function.chordpro" }
         }
      },
      {
         "name": "comment.chordpro",
         "match": "^#.*$"
      },
      {
         "name": "keyword.chordpro",
         "match": "(\\[)(.+?)(\\])"
      },
      {
         "name": "string.chordpro",
         "match": "^([a-gA-G])(\\s)*?([\\|\\-\\d\\^bs\\/])+",
         "captures": {
            "1": { "name": "keyword.chordpro" },
            "4": { "name": "support.function.chordpro" }
         }
      }
   ],	
}`

Best regards
George

**Comment by AndiDittrich** [comment]
Hi George,

of course, we can add this to EnlighterJS v3.
as i see there are only 3 different elements used ?

* **chords**: everything in square brackets
* **metadata**: everything in curly brackets (key: value pair)
* **comments**: starting with pound key

can you provide some free demo content (MIT License ?)

best regards, Andi

**Comment by AndiDittrich** [comment]
## Bootstrap 4 Theme ##
![enlighter_cordpro1](https://user-images.githubusercontent.com/1474107/42658816-c183eeee-8626-11e8-9c90-b2f429a8cefe.png)

## Dracula Theme ##
![enlighter_cordpro2](https://user-images.githubusercontent.com/1474107/42658830-c7dad69a-8626-11e8-868e-f993b076d0ca.png)

**Comment by glewe** [comment]
Hi Andi,
thanks for your quick response.
Here is some demo content:
`# ---------------------------------------------------
# This sample song shows how to markup your tune in
# ChordPro format (visit the User Guide for more
# help and examples).
#
# First, lines beginning with # are ignored, these
# are hidden notes, memos to yourself; they won't be
# displayed in the final song.
# ---------------------------------------------------

{title: My Little Grass Shack in Kealakekua}
{artist: Lyrics & Music: B.Cogswell, T.Harrison and J.Noble (1933)}

{comment: Verse 1}
I want to go [G]back to my little grass shack
In Kealakekua, [A7]Hawaii
I want to [D7]be with all the kanes and wahines
That I used to [G]know... so long ago
I can [B7]hear the old guitars a-playing[E7]
On the beach at Honaunau
I can [A7]hear the old Hawaiians saying
"Komo [D7]mai no kaua i ka hale welakahau"

{comment: Verse 2}
It won't be [G]long till my ship will be sailing
Back to [A7]Kona
A [D7]grand old place
That's always fair to [B7]see... you're telling me
I'm [E7]just a little Hawaiian and a homesick island boy
I [A7]want to go back to my fish and poi

{start_of_chorus}
{comment: Chorus}
I want to go [G]back to my little grass shack
In Kealakekua, [A7]Hawaii
Where the [D7]humu-humu nuku-nuku a pua'a
Go swimming [G]by
{end_of_chorus}

{comment: Outro}
Where the [D7]humu-humu nuku-nuku a pua'a
Go swimming [G]by
`

**Comment by glewe** [comment]
Hi Andi,
that was quick. When will you publish the next release?
Best regards
George

**Comment by AndiDittrich** [comment]
Hi George,
the EnlighterJS release will be published within the next few days.
The WordPress plugin has to be **completely rewritten** - this will take some time. Maybe i can release a beta version without the ThemeCustomizer soon.

best regards, Andi
