### ISSUE TITLE
Copy to clipboard in Button toolbar

### ISSUE THREAD

**Issue by 24killen** [EnlighterJS/Plugin.WordPress#110]
I would really like to see a simple Copy button option to add in the Button toolbar. Which would copy all the code in the code block and place it in the clipboard.

**Comment by AndiDittrich** [comment]
Hi @24killen ,

this feature is related to EnlighterJS and it has already been implemented in the [latest release candidate](https://github.com/EnlighterJS/EnlighterJS/releases/tag/v3.0.0-RC1).

it will be added into the brand new Enlighter Plugin which will be released in the **next few weeks/month**.

in the meantime, i've created an [experimental plugin](https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat) to add EnlighterJS v3 to the current Enlighter WordPress Plugin (v3)

best regards, Andi
