### ISSUE TITLE
Wrap/unwrap code button

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [EnlighterJS/Plugin.WordPress#112]
Is it planned to add a button with this behavior?

**Comment by AndiDittrich** [comment]
not really - whats your use case ?

**Comment by JavierSegoviaCordoba** [comment]
@AndiDittrich allow the user to choose

**Comment by AndiDittrich** [comment]
for clarification: is your feature request related to the css line wrapping or the wrapping/folding of a code block (expand/minimize the height) ?

**Comment by JavierSegoviaCordoba** [comment]
Line breaking, but the second one can be useful too.

**Comment by AndiDittrich** [comment]
line breaking behaviour should (imho) controlled by the theme since it is related to the appearance.
personally i've never seen nor used such feature

the second one is projected for Enlighter v4.1 ... v4.3 - it requires some features which are not implemented yet

**Comment by JavierSegoviaCordoba** [comment]
I am trying this: https://github.com/EnlighterJS/Plugin.WordPress/issues/31

But I am having two issues:
- The scrollbar is always visible even if it has not scroll
- [I am getting this background color problem with the selected lines (it is cutted)](https://i.imgur.com/zTEFq8x.png)

**Comment by AndiDittrich** [comment]
did you solve it with the code in #31 ?

**Comment by JavierSegoviaCordoba** [comment]
Yeah

**Comment by AndiDittrich** [comment]
great, i'll close this issue
