### ISSUE TITLE
Update code snippet icons

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [EnlighterJS/Plugin.WordPress#113]
Really I did this with CSS, but should be great to update these icons because they look old and they do not fit with the current flat design.

This is my actual implementation: 

Normal: https://i.imgur.com/IcHtzpB.png

Hover: https://i.imgur.com/PmBuUGx.png

**Comment by AndiDittrich** [comment]
thanks for your feedback. please check EnlighterJS v3 - https://github.com/EnlighterJS/EnlighterJS

**Comment by AndiDittrich** [comment]
especially https://github.com/EnlighterJS/EnlighterJS/tree/master/src/themes/icons

btw. its intended that the icons can be changed with a custom theme to match your requirements

**Comment by JavierSegoviaCordoba** [comment]
I didn't know about it, it is great.

**Comment by AndiDittrich** [comment]
EnlighterJS v3 will be released with Enlighter v4 (WordPress Plugin) in the next few weeks/month - currently the Gutenberg Editor support has the highest priority.

but your also welcome to contribute a flat iconset to the upcoming release
