### ISSUE TITLE
One line token styles are not being applied correctly

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [EnlighterJS/Plugin.WordPress#114]
I tried formatting with both (inline and block), both have the same problem:

https://i.imgur.com/F3bWdmi.png

The first word (val) should be blue, but it is not getting the style, however, the last zero, is getting the style.

Another example:

https://i.imgur.com/pnf6Ee0.png

**Comment by AndiDittrich** [comment]
it's a bug related to the highlighting engine/language support file used in EnlighterJS v2 - this should be addressed in EnlighterJS v3 - please try it.

btw. you can post images directly here on GitHub by just dragging them into the editor :+1:
