### ISSUE TITLE
Code indentation isn't working on Mozilla, Edge & Safari

### ISSUE THREAD

**Issue by CodingInfinite** [EnlighterJS/Plugin.WordPress#116]
Code indentation is only working with Google Chrome. It's not working on Mozilla, Edge & Safari. Code gets Indent to the Left. 
Image attached. 
Thanks.
![screen shot 2018-09-02 at 2 34 51 pm](https://user-images.githubusercontent.com/38278026/44954585-877d7c00-aebd-11e8-896a-f99272fd0c7c.png)

**Comment by AndiDittrich** [comment]
HI @CodingInfinite ,

thanks for your report. currently i cannot reproduce your issue - everything works as expected.

1. does the same error occur on the [demo page](https://enlighterjs.org/Language.Javascript.html) ?
2. do you've disable the indentation mode (set to tabs) in `Enlighter -> Appearance -> Global Settings -> Code Indent` ? if so, please set in to **spaces**
3. did you tried the inspect your page css rules ? in most of the cases some of the wordpress theme styles interfere with the EnlighterJS styles and override some rules - maybe you can post a link to a demo page ?

best regards, Andi

**Comment by CodingInfinite** [comment]
Hi @AndiDittrich,
Problem solved!
I was using WP Fastest Cache plugin. I unchecked "Minify HTML" option & now everything is working fine.
