### ISSUE TITLE
Conflict with Beaver Builder

### ISSUE THREAD

**Issue by michaeltieso** [EnlighterJS/Plugin.WordPress#117]
There is a conflict with Beaver Builder. It causes [Beaver Builder](https://www.wpbeaverbuilder.com/) to break making it no longer possible to use their UI. Example below of a broken builder page.

![screenshot_2018-09-07_22 01 55](https://user-images.githubusercontent.com/1500606/45240658-b6468880-b2e9-11e8-8409-2b99c63e53ba.png)

**Comment by AndiDittrich** [comment]
Hi @michaeltieso ,

where does the error occur ?
i'm not familiar with "Beaver Builder" but i assume it is a page builder for the frontend ?

in this case it might conflict with MooTools which is still used by EnlighterJS v2 to highlight the code. there are some other open issues related to MooTools which cannot be fixed within the current release.

therefore i've created a new version of EnlighterJS (v3) which works without any dependency - it will be released this year (Enlighter Plugin v4). 
an experimental release is already available but targeted to advanced/professional users only

best regards, Andi

**Comment by michaeltieso** [comment]
Hey @AndiDittrich .
Yeah, it's a page builder. It occurs on all pages when activating the builder. I'll ping the Beaver Builder folks if they have any insight they can provide.
Thanks for looking into it.

**Comment by michaeltieso** [comment]
Yeap, that's exactly it. Not including fixes it.
Does this need to be added onto every page? Could it be conditional on only pages that use it?

**Comment by AndiDittrich** [comment]
there is an "experimental/beta" feature available in `Enlighter - BETA - Dynamic Resource Invocation (DRI)` which only invokes the Enlighter resources in case they are needed - you can try it out but i didn't believe that this works in your case

**Comment by michaeltieso** [comment]
Ah, I missed that feature. That worked for me. Thank you!

**Comment by AndiDittrich** [comment]
great :+1:
