### ISSUE TITLE
v3.8 archive contains duplicate files

### ISSUE THREAD

**Issue by aguidrevitch** [EnlighterJS/Plugin.WordPress#119]
![image](https://user-images.githubusercontent.com/1030492/45694051-16012700-bb67-11e8-909f-15500541d8c9.png)

This creates huge problem on case-insensitive filesystem, as EnlighterJS.min.js comes out broken when installed through WordPress

**Comment by AndiDittrich** [comment]
Hi @aguidrevitch 

thanks for your report. i can confirm that something gone wrong with the release files on WordPress.org (SVN) - the repository (GitHub) is fine - i will check this asap!

the lowercase file are the EnlighterJS v3 js files which are not released yet.....

best regards, Andi

**Comment by AndiDittrich** [comment]
fixed in 3.8.1 (already released on WordPress.org as well as on GitHub)
