### ISSUE TITLE
It doesn't work in custom post types

### ISSUE THREAD

**Issue by rafaelcmgt** [EnlighterJS/Plugin.WordPress#122]
Hi,

I am trying to use this plugin in my custom post types, but it doesn't work whatsoever. Is there a way to do it?

**Comment by AndiDittrich** [comment]
Hi @rafaelcmgt ,

is this issue related to TinyMCE or Gutenberg editor ?

could you please post a minimal example code snippet how you've created the post types ?

best regards, Andi

**Comment by rafaelcmgt** [comment]
Hi,
Thank you for the quick response.

- I am not using Gutenberg. Only TinyMCE.

- I created my custom post type with [toolset](https://toolset.com), a suite of plugins. I used Types plugin to create de custom post type and Views plugin to show it in the front-end. Both are part of Toolset, as I said before.

**Comment by AndiDittrich** [comment]
i've created a minimal example code to add a custom post-type and everything works as expected: Enlighter Toolbar buttons are available and the EnlighterJS/Plugin.TinyMCE has been successful initialized.

currently i believe it is an issue with your toolset plugin - maybe they override the editor plugins/buttons. you should contact their support for further further assistance.... because it is a payed plugin and i have no possibility to test/debug it. sorry!

you should also send them a link to this issue.

in the past there were a lot of issues related to 3rd party plugin - most of the commercial providers/vendors fixed the issues related to the editor

-------------

**Code**

```php
<?php

add_action('init', function(){

    register_post_type(
        'courses',
        array(
            'label' => __('Courses'),
            'public' => true,
            'show_ui' => true,
            'supports' => array(
                'title',
                'editor',
                'post-thumbnails',
                'thumbnail',
                'revisions')
        )
    );

    register_taxonomy('coursetype', 'courses',
        array(
            'hierarchical' => true,
            'label' => __('Course Types'),
            'query_var' => 'coursetype',
            'rewrite' => array('slug' => 'coursetype' )
        )
    );
});
```

**Result**
![enlighter_posttype_test](https://user-images.githubusercontent.com/1474107/45874728-eb48e580-bd95-11e8-91e4-79a60e880aac.png)

**Comment by rafaelcmgt** [comment]
Sorry, I forgot to mention that the plugin works ok in the back-end. The problem is that it doesn't work in the front-end. Here is an example:

The back-end:
![back-end](https://user-images.githubusercontent.com/13097597/45875545-4a0f5e80-bd98-11e8-98d0-9a8afca9e742.png)

The front-end
![front-end](https://user-images.githubusercontent.com/13097597/45875563-585d7a80-bd98-11e8-8e2c-28afe21cb4b9.png)

I think that it might be this plugin. Other syntax hightlighter plugin works properly in my custom post type.

**Comment by AndiDittrich** [comment]
btw. can you post a link to the frontend ? i will take a look on it - maybe some resources are missing

**Comment by rafaelcmgt** [comment]
It works perfect on standard post.
This web is not on production yet. This is why i am not using any optimization/minification plugins.
I was using a different syntax highlighting plugin. I have deactivated it, I have activated enlighter plugin and I have just created a post in my custom post type for you to see it. This is the link:

[https://www.rafaelmartinweb.com/snippet/enlighter-plugin-test/](https://www.rafaelmartinweb.com/snippet/enlighter-plugin-test/)

Just in case, here you have all my activated plugins:

![plugins rafaelmartinweb wordpress](https://user-images.githubusercontent.com/13097597/45889329-73dc7b80-bdc0-11e8-9711-7cbfba15a320.png)

"Funciones" plugin is my own function plugin.

**Comment by AndiDittrich** [comment]
i've identified the issue: your `frontend-builder` css is overriding the EnlighterJS styles - therefore you didn't see any highlighted code (the engine itself and the plugin is working fine...)

by disabling the weak css rules everything works as expected..

![enlighter_error_frontendbuilder](https://user-images.githubusercontent.com/1474107/45896733-4817c080-bdd5-11e8-8a84-3c8071904306.png)

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/Plugin.WordPress/blob/master/class/ResourceLoader.php#L253

**Comment by rafaelcmgt** [comment]
Thank you.

Unfortunately, it didn't work.
I have decided to stop using the frontend builder for this custom post type. Now the Enlighter plugin is working properly.

Nice plugin and good support.
I am going to post a good review in the wordpress repository.
