### ISSUE TITLE
Adding YAML support

### ISSUE THREAD

**Issue by EricDele** [EnlighterJS/Plugin.WordPress#128]
Hello

Could you add the YAML syntax support to the WordPress Plugin ?
I saw you have this syntax in the generic EnlighterJS but not in the WordPress Plugin.
It could be great for Ansible snippets.

Many thanks
Eric.

**Comment by AndiDittrich** [comment]
Hi @EricDele ,

YAML support is available in EnlighterJS v3. 
The next major release of the WordPress Plugin (Enlighter v4) will include the new highlighting core.

best regards, Andi

**Comment by EricDele** [comment]
Hi @AndiDittrich 

Thanks for your quick answer, do you have an estimation of the availability of the next release ?

Best regards.
Eric.

**Comment by AndiDittrich** [comment]
est. `Dec 2018` ... `Q1 2019`

in the meantime you can try the [experimental integration](https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat)

**Comment by EricDele** [comment]
Many thanks @AndiDittrich 
I will give it a try to the experimental

Best regards.
Eric.

**Comment by EricDele** [comment]
the experimental is working fine, thanks.
I close the issue, many thanks @AndiDittrich 
Best regards.
Eric
