### ISSUE TITLE
Code folding? 

### ISSUE THREAD

**Issue by DavidGRX** [EnlighterJS/Plugin.WordPress#129]
Dear Enlighter developers:
   thank you first for this great plugin!. 
I wonder if it possible to have "code folding" in the current plugin version. 
I'm using C++ examples and it would be nice to have fold/unfold properties at some points of the code(i.e functions' code).

All the best
David

**Comment by AndiDittrich** [comment]
Hi David,

such feature is currently not implemented nor planed for the future.

the problem with code-folding on functions/blocks is that it requires a lexical processing of the code as well as an abstract-syntax-tree to analyze the structure. 
this kind of feature may provided by an IDE but not by a "simple" syntax highlighter based token analysis.

best regards, Andi

**Comment by DavidGRX** [comment]
Thank you for your quick response. I'll try to find another plugin at least to fold/unfold the whole code. 

Regards
David

**Comment by AndiDittrich** [comment]
folding the whole code based on number of visible lines or the height can be implemented soon
