### ISSUE TITLE
Conflict with Divi animations on mobile and MooTools library

### ISSUE THREAD

**Issue by yankiara** [EnlighterJS/Plugin.WordPress#132]
Hi Andi!

I have a new issue with Divi and MooTools...
On mobile devices (Android), all animated elements are invisible.

Hopefully I don't need Enlighter on my animated pages for I only use it on non-animated blog posts, so I could deactivate MooTools with this on the static pages (and with Visual Builder):

```
function pavenum_remove_mootools_with_visual_builder() {
	if ( et_core_is_fb_enabled() || isset( $_GET['et_fb'] ) || is_page() ) {
		wp_dequeue_script( 'mootools-google-cdn' );
	}
}
add_action('wp_footer', 'pavenum_remove_mootools_with_visual_builder');
```

When I dequeue MooTools lib, everything is fine.

Hope you will soon  get rid of this lib :-)
Have a beautiful day.

**Comment by AndiDittrich** [comment]
Hi @yankiara ,

of course - disabling MooTools for selected pages is the best workaround.
you can also try the [experimental EnlighterJS3](https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat) release which works standalone.

best regards, Andi
