### ISSUE TITLE
Line number not show on

### ISSUE THREAD

**Issue by RodriAndreotti** [EnlighterJS/Plugin.WordPress#134]
![line numbers](https://user-images.githubusercontent.com/9449048/49118721-968d8380-f28c-11e8-9ac0-ed62997823b3.PNG)

**Comment by AndiDittrich** [comment]
Hi @RodriAndreotti ,

it looks like that some of your theme/page styles are overriding the Enlighter line numbering.
maybe you can post a link ? i will take a look on it.

within the testing environments everything works fine - it's not a general plugin issue.

best regards, Andi

**Comment by RodriAndreotti** [comment]
Hi, there!

Of course I can provide a link:
Here is it: https://blog.eximiaweb.com.br/4-conceitos-orientacao-a-objetos/

I have duplicated actual <pre> tag using Enlighter..

I'm using Mesmerize theme (free version).

Thanks!

**Comment by AndiDittrich** [comment]
Enlighter is not used on this page - only Gutenberg `pre` blocks

**Comment by RodriAndreotti** [comment]
Hello!
Thanks for the answer, I actually have yes, if you can take a look at the attachment.

I noticed when I am not logged in it does not load the mootools, however this should be some problem with autoptimize, however logged in it displays for me the block registered with the enlighter.

I deactivated autoptimize to make the communication easier, then check how to solve this case .. hehe.

Thank you!
![line numbers](https://user-images.githubusercontent.com/9449048/49155519-4bae5300-f302-11e8-8c86-0f231c22bdfd.PNG)
![line numbers 2](https://user-images.githubusercontent.com/9449048/49155566-61237d00-f302-11e8-9a44-673c4ae7edd7.PNG)

**Comment by AndiDittrich** [comment]
now i see whats going wrong: please set show/hide line-numbers in the Gutenberg Enlighter block **directly** - the global setting in Enlighter Settings **will not work with EnlighterJS v2**

the Gutenberg Plugin is designed for EnlighterJS v3 - therefore it is still marked as **beta** in the current Enlighter Release

**Comment by RodriAndreotti** [comment]
The Enlighter is set to version 3, I think, at least I do not remember having changed that.

But configuring directly in the local settings of the block worked.

Anyway, thank you for the help, now I will need to go through each of the posts by changing my PRE blocks, since my previous plugin has no more update and broke all my posts ..

Thanks again!

**Comment by AndiDittrich** [comment]
Enlighter (WordPress Plugin) !== EnlighterJS (Javascript Highlighter)

**Comment by RodriAndreotti** [comment]
Ops... my bad.. rs
Thank you again ;-)

**Comment by AndiDittrich** [comment]
it's not projected to be "resolved" for the current version - see https://github.com/EnlighterJS/Plugin.Gutenberg/issues/2

**Comment by AndiDittrich** [comment]
please see https://github.com/EnlighterJS/Plugin.Gutenberg/issues/2

the changes applied to EnlighterJS v2.13.0 will become available in v3.9.0
