### ISSUE TITLE
No theme applied on some pages

### ISSUE THREAD

**Issue by mennowo** [EnlighterJS/Plugin.WordPress#135]
Hello,
on my website Enlighter works fine on regular posts, however, on some wiki pages no theme seems to be applied, and no monospace font is used.
For example here: https://www.codingconnected.eu/category/nieuws/ (scroll down a bit) all works well.
However, here: https://www.codingconnected.eu/tlcgenwiki/tutorial-tlcgen-plugin-data-opslaan/ no theme seems to be applied, and source code formatting seems to be only partially applied. this is the case both when using the inline editor for TinyMCE, and using the ``` block code syntax.
Might there be a simple way to fix this? Or is Enlighter somehow incompatible with the Echo Knowledgebase plugin I am using?
Thanks! Greets,
Menno

**Comment by AndiDittrich** [comment]
Hi @mennowo ,

your page styles are overriding the EnlighterJS themes ...

![enlighterjs_css_compat](https://user-images.githubusercontent.com/1474107/50161106-226a5c80-02db-11e9-932d-d1747ec946f4.png)


best regards, Andi

btw. your website is unusable in Chromium (71.0.3578.80) - Firefox works fine..

**Comment by mennowo** [comment]
Hello Andi,
thanks for looking into this! I will check how I can disable the overriding styles. This oddly does not happen on posts, which should be helpful to pinpoint towards a solution.
I just tried my site on Chromium (ungoogled) same version.98, and it works fine as far as I can see. Maybe the server running the site was having trouble... Thanks for remarking it though!
Greets, Menno

**Comment by mennowo** [comment]
Sorry to comment after I closed the issue; is there an easy fix for this? Can I just make the Enlighter style override the page styles? Maybe by manually including EnlighterJS.js and EnlighterJS.css? Or will I have to alter the sources of my theme for this?
