### ISSUE TITLE
Syntax highlighting won't work on mobile 

### ISSUE THREAD

**Issue by dukesx** [EnlighterJS/Plugin.WordPress#138]
The Syntax highlighting won't work on Chrome for Android but works perfectly on Chrome for Windows 10.

- WordPress version 5.0.2 
- Plugin updated to latest version
- Android version 7.0.2 On Galaxy S8+

You can check this by browsing to React JS lectures on https://techinterventions.com to see how the highlighting doesn't work on Mobile phone

**Comment by dukesx** [comment]
@AndiDittrich Please have a look

**Comment by AndiDittrich** [comment]
@dukesx 

you opened the issue **1 day ago** ... so be patient ;) i need some free time to check/verify/debug the issue.

your website doesn't work in Chromium (all platforms) as well because **you've unloaded the MooTools Framework** - `Enlighter Error: MooTools Framework not loaded yet!` (chrome console error)

do you've changed this recently ?

best regards,
Andi

**Comment by dukesx** [comment]
@AndiDittrich which thing is using Moo tools ? and I have not touched anything. Can you point me to where can this problem originate from ?

**Comment by AndiDittrich** [comment]
please take a look into your website sourcecode...

```html
<script data-minify="1"  src="https://techinterventions.com/wp-content/cache/min/1/wp-content/plugins/enlighter/resources/mootools-core-yc-363efd0a1258b7545bd5aa52599b1930.js" defer></script>
<script  src="https://techinterventions.com/wp-content/cache/busting/1/wp-content/plugins/enlighter/resources/EnlighterJS.min-3.8.1.js" defer></script> 
```

this resources are **not loaded by Enlighter this way** - i assume you've some kind of optimization plugins enabled.... exclude Enlighter from any modifications!

the problem is caused by the `defer` property - it causes an `undefined behaviour` - it's not related to mobile..

**Comment by dukesx** [comment]
You are absolutely right, the issue was WP Rocket caching plugin that I use. Let me try by excluding the three URLs provided

**Comment by chnaveen138** [comment]
> please take a look into your website sourcecode...
> 
> ```
> <script data-minify="1"  src="https://techinterventions.com/wp-content/cache/min/1/wp-content/plugins/enlighter/resources/mootools-core-yc-363efd0a1258b7545bd5aa52599b1930.js" defer></script>
> <script  src="https://techinterventions.com/wp-content/cache/busting/1/wp-content/plugins/enlighter/resources/EnlighterJS.min-3.8.1.js" defer></script> 
> ```
> 
> this resources are **not loaded by Enlighter this way** - i assume you've some kind of optimization plugins enabled.... exclude Enlighter from any modifications!
> 
> the problem is caused by the `defer` property - it causes an `undefined behaviour` - it's not related to mobile..



> You are absolutely right, the issue was WP Rocket caching plugin that I use. Let me try by excluding the three URLs provided
> 
> Update #1: the problem has been resolved after excluding the URLs.
> 
> Thank you very much, you are a hero! And I sincerely apologize for startling you, since my work is teaching programming and mostly people use mobile phones to see websites, and no other syntax highlighter is compatabile with Gutenberg, it was alarming situation for me to lose the the tiny audience that I have.

dukesx I have same problem with wp-rocket cache plugin. Can you tell me how did you solve that problem? Where you have excluded that URLs

**Comment by dukesx** [comment]
Sure, if you faced the same issue as mine then there are two ways :

1. If you have WP Rocket javascript Defer setting to on, then turn it off (it didn't make a difference to speed anyway as I checked on Pingdom tools)

2. If you still want to keep javascript deferred then open the page source and check for enlighter javascript links either in footer or header, and then add that link to the exclude in the javascript defer settings. 

After this, clear the cache and the code should start loading and highlighting again normally with the theme

**Comment by chnaveen138** [comment]
> Sure, if you faced the same issue as mine then there are two ways :
> 
> 1. If you have WP Rocket javascript Defer setting to on, then turn it off (it didn't make a difference to speed anyway as I checked on Pingdom tools)
> 2. If you still want to keep javascript deferred then open the page source and check for enlighter javascript links either in footer or header, and then add that link to the exclude in the javascript defer settings.
> 
> After this, clear the cache and the code should start loading and highlighting again normally with the theme

Yeah! It's working like a charm... Thanks for the fast reply.

**Comment by dukesx** [comment]
All thanks to the developer :D

**Comment by highhimanshu** [comment]
> > Sure, if you faced the same issue as mine then there are two ways :
> > 
> > 1. If you have WP Rocket javascript Defer setting to on, then turn it off (it didn't make a difference to speed anyway as I checked on Pingdom tools)
> > 2. If you still want to keep javascript deferred then open the page source and check for enlighter javascript links either in footer or header, and then add that link to the exclude in the javascript defer settings.
> > 
> > After this, clear the cache and the code should start loading and highlighting again normally with the theme
> 
> Yeah! It's working like a charm... Thanks for the fast reply.

worked

**Comment by AndiDittrich** [comment]
for Enlighter >v4 you can also set the init code option to "single file". but the solution to exclude EnlighterJS from "optimizations" is recommended

**Comment by AshwinDWeBlogStories** [comment]
I am facing the same issue even after following the steps mentioned.

Also, one more thing I observed is on windows desktop when I open blog page, sometimes I don't see enlighter code block. I have to refresh the page two or three times and then I start seeing the enlighter code block on the blog page.

It is creating lot of inconvenience and trouble. Please help!

My blog page is https://weblogstories.com

**Comment by AndiDittrich** [comment]
try to reproduce the issue within a clean environment (no plugins, default theme).
if it still happens it's an Enlighter issue (just open a new issue in this case). otherwise it's some kind of theme/plugin issue - see https://github.com/EnlighterJS/documentation/blob/master/wordpress/Troubleshooting.md

**Comment by AshwinDWeBlogStories** [comment]
> try to reproduce the issue within a clean environment (no plugins, default theme). if it still happens it's an Enlighter issue (just open a new issue in this case). otherwise it's some kind of theme/plugin issue - see https://github.com/EnlighterJS/documentation/blob/master/wordpress/Troubleshooting.md

Thanks Andi for quick response. As suggested, I tried deactivate plugins and I found the culprit. It is AMP plugin, when it is deactivated, enlighter is working like a charm...

Thanks again for your help :-)
