### ISSUE TITLE
Line number not on the right side

### ISSUE THREAD

**Issue by TheRealTiti** [EnlighterJS/Plugin.WordPress#139]
Hello,

I just installed the plugin and my problem is that line numbers are not on the left part but in the right part within the code.

Thank for this great plugin.

<img width="305" alt="capture d ecran 2019-01-04 a 00 28 37" src="https://user-images.githubusercontent.com/46360371/50667086-fd9f0600-0fb7-11e9-8930-3d5977dee790.png">

**Comment by AndiDittrich** [comment]
Hi @TheRealTiti 

some of your theme/page styles are overriding the margin/padding of the enlighter container.
please check/inspect your css rules

best regards, Andi
