### ISSUE TITLE
Does this work with WP 5?

### ISSUE THREAD

**Issue by cityjumper** [EnlighterJS/Plugin.WordPress#140]
I just upgraded to WP and I thought this would work in WP 5.

**Comment by AndiDittrich** [comment]
Hi @cityjumper 

it works fine with WordPress 5.0.x as marked on WordPress.org compatibility

do you have any issues ?

best regards, Andi

**Comment by cityjumper** [comment]
So maybe I miss understood how to use it but when I highlight text or code I do not see any place where I can select your plug=in. I was under the impression that I if I wrote a new section and made it performated, and then if I was to highlight the code the editor or smart editor would give em an option to turn it into EnlightedJS, and then the code highlighting would kick in. But I do not see the EnllightenJS:(

I am on 5.0.2, and I have the following settings:
Enable Backend Integration
Enable Frontend Integration
Add Editor Formats

It does say that I might need a font end plugin which one would I need? (maybe I missed it) So any advice you could give that would be great:)

**Comment by AndiDittrich** [comment]
do you use the Gutenberg Editor ?

if so, you have explicit enable the extension in 3.8.1 - goto `Enlighter -> BETA -> Gutenberg` and check the box.

Enlighter adds its own Gutenberg sourcecode block. you can find a simple gif demo [within the Gutenberg Plugin Repository](https://github.com/EnlighterJS/Plugin.WordPress/blob/master/docs/Usage_GutenbergEditor.md)

**Comment by cityjumper** [comment]
Ahh it works like a charm:) thanks ever so much. I did not turn on the BETA part. Thanks for making this a reality, it is super cool.
