### ISSUE TITLE
Code Enlightment is occuring only for logged in users

### ISSUE THREAD

**Issue by chnaveen138** [EnlighterJS/Plugin.WordPress#141]
I can see **Code Enlightment** only when I was editing as admin but not for normal users. How can I solve this issue?
I am getting this javascript error:
(index):77 Enlighter Error: MooTools Framework not loaded yet!

**Comment by AndiDittrich** [comment]
Hi @chnaveen138 ,

generally Enlighter is not designed to work in editing mode like an editor/ide including syntax highlighting - the Enlighter editor plugins provides "plain textareas" to insert/edit the sourcecode - therefore i'm a little confused about your issue. Did you may use other syntax highlighting plugins ? Maybe you can provide a screenshot?

The javascript error indicates that the MooTools library could not be loaded which is required to highlight the code. there are two possible issues known:

1. you've manually disabled MooTools on the Enlighter settings page `Enlighter -> Options -> Resources+CDN -> MooTools Framework Source`
2. you may use some kind of "optimization plugin" or "caching plugin" which alters the script execution. in this case, exclude the Enlighter related scripts (everything in `wp-content/plugins/enlighter` from getting "optimized"

if you cannot investigate the issue further, it would be nice to provide a link to your website - then i can take a look on it (also possible via e-mail or twitter pm)

best regards, Andi

**Comment by chnaveen138** [comment]
Yeah! I am actually using wp-rocket caching plugin. The error [MooTools Framework is not loaded yet] only occurs for normal users. When I am logged in I cannot see any error and Code Enlightment works fine.
This is my website:
[](http://naveenchelimilla.tech)

**Comment by AndiDittrich** [comment]
ah.. wp-rocket cache - please read this similar issue with it: https://github.com/EnlighterJS/Plugin.WordPress/issues/138

you have to exclude Enlighter from caching

**Comment by chnaveen138** [comment]
Yeah! I have understood the problem. Can you please tell me which URLs I should exclude?
I have excluded URLs that were mentioned in that issue but it didn't work for me...

**Comment by chnaveen138** [comment]
Actually, It's working when I am loading uncached file...
So the problem is by wp-rocket for sure... Can I know the URLs that I have to exclude?

**Comment by chnaveen138** [comment]
I have tried that but it was not working! But I am sure that it's due to WP-Rocket Plugin.
Anyway, thanks for the super fast reply!
