### ISSUE TITLE
Swift Language Support?

### ISSUE THREAD

**Issue by woolseyj** [EnlighterJS/Plugin.WordPress#142]
Is there a plan to add support for the Swift language?

**Comment by AndiDittrich** [comment]
`swift` is already supported in EnlighterJS v3.0.0-RC1

you can try it by using the [experimental integration](https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat) - it will be released soon as part of the Enlighter WordPress Plugin 4.0

best regards, Andi

**Comment by woolseyj** [comment]
That is great news, thank you.
