### ISSUE TITLE
Where is the Theme Customizer?

### ISSUE THREAD

**Issue by holdenhinkle** [EnlighterJS/Plugin.WordPress#143]
Hi Andi,

Amazing plugin. Thanks for everything you do.

I'm sorry to bother you with this, but can you please tell me where the Theme Customizer is located in the WP plugin? I can't find it.

All the best,

Holden

**Comment by AndiDittrich** [comment]
Hi Holden,

`Enlighter -> Appearance -> Theme` - select **WP Custom** and the `Theme Customizer` tab will appear in the menu.

best regards, Andi
