### ISSUE TITLE
How to add a new language

### ISSUE THREAD

**Issue by keahh** [EnlighterJS/Plugin.WordPress#146]
Hello, this question may be stupid, I may overlook something in the docs... but...

I would like to highlight syntax of OpenEdge ABL.
How do I add a new language?

kind regareds
Klaus

**Comment by keahh** [comment]
Hello Andi,
thanks for the information, I had a look at some of the languages.

_I will not go deeper into that in the moment. Looks too much effort for that what I am intending in the moment._

I talked in parallel with the guys from Beaver Builder. I use BB.
I suggested them to add Enlighter JS. They told me the following:
"
Guy Barry I'm not getting far with this unfortunately. I suggest you get in touch with the developer of the Enlighter plugin and ask him to make it compatible with Beaver Builder.
Tell him that BB removes all third party TinyMCE buttons on the front end with a priority of 999999 to avoid conflicts with plugins that are only intended to be used in the backend.
Since Enlighter already has an option for being used on the front end, it should hopefully be a simple thing for him to add as an option, or to give you a function to override the priority.
A plugin like Elighter can be made compatible by hooking into the FLBuilderModel php class to enqueue it's scripts and styles without forcefully overriding the priority.
"

That might something which can extend your user base. Beaver Builder is used from a lot o people.
kind regards
and thanks for your help
Klaus

**Comment by AndiDittrich** [comment]
@keahh 

the problem with plugins like "Beaver Builder" is that they are proprietary...that means i have to buy a license to test it with Enlighter and may need an additional "support license/fee" to get in contact with the developers..... and currently the Enlighter project is totally free... i did not earn any money with it. in the past it took a lot of time to fix issues related to 3rd party plugins...

therefore i'm unable to implement it. we can do it on a commercial base via my company but this will cost some k€ ....

best regards, Andi
