### ISSUE TITLE
Increase theme font-size

### ISSUE THREAD

**Issue by houdayec** [EnlighterJS/Plugin.WordPress#147]
Hi !

I'm trying to increase the font-size of Visual Editor (Tab Visual Editor -> 
Code-Block Styles -> Font-Size)

Default value is 0.7em, I've tried many different size (randomly from 1 to 3 em) but it doesn't seems to change the code snippet.

I've tried changing the value then adding new code snippets but nothing.

Do you have any idea how to fix it ?

Btw, the plugin is really good, thanks for making it.

**Comment by AndiDittrich** [comment]
Hi @houdayec ,

setting it to e.g. `2em` works as expected using the "Classic Editor" plugin in WordPress 5.0.X

![image](https://user-images.githubusercontent.com/1474107/52727016-a3c92d00-2fb4-11e9-8591-cdb1f31d245a.png)

**Comment by AndiDittrich** [comment]
could you solve the issue for your site ?

**Comment by houdayec** [comment]
Hi ! i've tried many solutions but font is still stucked at its original size ..

![screenshot 2019-02-16 at 12 28 04](https://user-images.githubusercontent.com/17120398/52899098-6815a980-31e6-11e9-8c52-8c88b8768aaf.png)

I'm using Materialize Theme

**Comment by AndiDittrich** [comment]
you want to change the font-size on your blogs `frontend` but you use the settings to change the **editor styles** in the `backend` - do you see whats going wrong ?

the `* Editor` tab settings are responsible for the editors (TinyMCE, Gutenberg, Text) but **NOT** for the themes!


----------

to configure the theme goto `Enlighter -> Appearance  -> Global Settings -> Theme` and select **WP Custom** - this enables the theme editor (a new tab will appear on the menu).

to change the themes font size goto `Enlighter -> Theme Customizer -> Font Styles`

best regards, Andi

**Comment by houdayec** [comment]
Okay I see now !

I've tried this WP Custom solution at first, but I didn't see that a new tab appeared. You clearly indicated to choose custom (_If you want to customize themes, choose the default theme option "custom"_), hopefully you told me to take a look at the tabs. 

Maybe you should highlight it in a visible color or put a warning, it's not really user friendly. The fact that i'm a WP beginner can also affect my point of view.

However, thanks for the reactive support. Keep going, your plugin is lit. Thanks.

**Comment by marslulu** [comment]
> you want to change the font-size on your blogs `frontend` but you use the settings to change the **editor styles** in the `backend` - do you see whats going wrong ?
> 
> the `* Editor` tab settings are responsible for the editors (TinyMCE, Gutenberg, Text) but **NOT** for the themes!
> 
> to configure the theme goto `Enlighter -> Appearance -> Global Settings -> Theme` and select **WP Custom** - this enables the theme editor (a new tab will appear on the menu).
> 
> to change the themes font size goto `Enlighter -> Theme Customizer -> Font Styles`
> 
> best regards, Andi

you are absolutely RIGHT! Anyway, the Theme Cusermizer is mixed with other themes, it's not a surprise that the average user would have trouble locating the settings for this function.
