### ISSUE TITLE
How to use with Gutenberg?

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [EnlighterJS/Plugin.WordPress#148]
I updated it today and I can't use it. The option is enabled in the plugin settings.

**Comment by AndiDittrich** [comment]
please provide some additional information... whats not working ?

**Comment by AndiDittrich** [comment]
Editor Usage: https://github.com/EnlighterJS/Plugin.WordPress/blob/master/docs/Usage_GutenbergEditor.md

**Comment by JavierSegoviaCordoba** [comment]
It is not appearing for me: https://i.imgur.com/SmG0IMC.png

**Comment by AndiDittrich** [comment]
i see the "Enlighter Sourcecode" icon on your screenshot.... sry but i need a lot more detailed informations...otherwise i'm unable to help you.

there are a lot of things which can gone wrong with the highlighting...but the Gutenberg editor plugin itself should work flawlessly....

**Comment by JavierSegoviaCordoba** [comment]
yeah, I mean that is not appearing for me

**Comment by AndiDittrich** [comment]
thats very strange... do you use some kind of caching/optimization plugins ?

**Comment by JavierSegoviaCordoba** [comment]
wp rocket

**Comment by AndiDittrich** [comment]
does it also cache backend resources ? did you tried to disable it ?

**Comment by JavierSegoviaCordoba** [comment]
Disabled and nothing.

I tried to disable and reenable Enlighter too, the problem persists.

**Comment by JavierSegoviaCordoba** [comment]
I have tinyMCE advanced installed and it is not appearing too inside of tinyMCE

https://i.imgur.com/GkkrLPY.png

**Comment by AndiDittrich** [comment]
TinyMCE advanced button alignment is not supported by the TinyMCE plugin.

do you see some javascript errors in the web-browser console using Gutenberg Editor?

**Comment by JavierSegoviaCordoba** [comment]
I have no idea about javascript :( but if you want I can give you admin access

**Comment by AndiDittrich** [comment]
please no admin access.... only a simple `Contributor` account which allows me to use the Gutenberg Editor. maybe we should discuss this via email for security reasons.

**Comment by JavierSegoviaCordoba** [comment]
okay! javiersegoviacordoba@gmail.com

**Comment by JavierSegoviaCordoba** [comment]
Do you could copy my email?

**Comment by AndiDittrich** [comment]
of course - i've just send you an email

**Comment by JavierSegoviaCordoba** [comment]
I didn't receive it :/ maybe I put bad my email? javiersegoviacordoba@gmail.com

**Comment by JavierSegoviaCordoba** [comment]
well I received it but it is in the bin folder... gmail things
