### ISSUE TITLE
Enlighter always displaying code as plain text

### ISSUE THREAD

**Issue by caiosabadin** [EnlighterJS/Plugin.WordPress#149]
Hello!

As I've read in the FAQ, I've set the wp-content/plugins/enlighter/cache as 0744, and still... The plugin displays my code as plain text. If I write a very long line of code, it evens breaks my layout. 

I'm currently using the Gutenberg version of the plugin. My Wordpress version is 5.0.3, and my plugin version is 3.9.0. 

The current theme I'm using was all made by myself... Am I missing something on its code, or is this issue maybe related to something else? I've read something about cache, and I do use the WP Super Cache plugin.

**Comment by AndiDittrich** [comment]
Hi @caiosabadin ,

could you please provide a link to your blog ? maybe some of the enlighter resources are missing (js+css) - did you cleared your wp super cache ?

best regards, Andi

**Comment by caiosabadin** [comment]
Hello, thanks for your answer.

I cleaned the super cache, indeed. My blog is https://panqks.com.br, but I'm afraid you won't find any posts with highlights on, because I don't want to post it and break my layout.

I had also tried reinstalling the Enlighter, but it didn't work.

Thank you again.

**Comment by AndiDittrich** [comment]
you're also using `autoptimize` ... please exclude EnlighterJS resources from being modified - the MooTools framework is also missing within the "optimized" bundle...

therefore EnlighterJS cannot work..

**Comment by caiosabadin** [comment]
Thank you! That was exactly the problem. I immensely appreciate your help.
