### ISSUE TITLE
TypeScript in Enlighter Wordpress Plugin not appearing

### ISSUE THREAD

**Issue by thomasberman** [EnlighterJS/Plugin.WordPress#150]
Hi Andi,

I saw in a previously closed issue that you added TypeScript to Enlighter V3, however, I don't seem to be able to pick it from the selector. Using the Gutenberg plugin. Is this supported yet?

Thanks,
Thomas

**Comment by thomasberman** [comment]
Ah I see now that the latest WP Plugin is running EnlighterJS 2.x

**Comment by AndiDittrich** [comment]
Hi @thomasberman ,

please keep in mind that `EnlighterJS` **is not the same as the** `Enlighter WordPress Plugin` - both using independent versioning.

to test `EnlighterJS v3` with the current plugin you can take a look onto the [experimental integration](https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat)

EnlighterJS v3 will be included in the WordPress Plugin v4

best regards, Andi
