### ISSUE TITLE
[Feature Request] PowerShell theme

### ISSUE THREAD

**Issue by willstocks-tech** [EnlighterJS/Plugin.WordPress#151]
Hi Andi,

PowerShell is a pretty widely used scripting language, especially amongst sys admins - it would be nice to be able to have a PowerShell theme so things look exactly as a reader would see it as they type! 😊

Thanks,

Will

**Comment by AndiDittrich** [comment]
Hi Will,

i think this doesn't make sense because the PowerShell "Terminal" is just a white font on a blue background...(well..yellow/red font in special cases).

a theme should support all kind of languages/tokens.

br, Andi

**Comment by willstocks-tech** [comment]
True... it’s mostly blue and white, with red and black/yellow and black.

What about (spinning off the idea!) allowing a user to store multiple
“custom theme”’s? That way, I could build my own “custom - powershell”,
“custom - MacBook terminal” themes and it’s not something you have to
“maintain” from a plugin perspective?

**Comment by AndiDittrich** [comment]
git clone EnlighterJS/EnlighterJS -> add your theme -> run gulp -> upload .....

**Comment by AndiDittrich** [comment]
storing multiple custom themes may be available in the upcoming "Enlighter Pro/Enterprise" versions - they also include server side rendering which reduces the frontend assets to ~10kB

**Comment by willstocks-tech** [comment]
Ahhhh - nice @AndiDittrich that sounds good! 

Is that going to be a paid tier? Out of curiosity, do you have an “Enlighter Roadmap”?

**Comment by AndiDittrich** [comment]
of course...on a subscription base (not much for personal blogs, just a few bucks a year).

an official roadmap is no available sry :(
