### ISSUE TITLE
[Feature Req] Inline code (back ticks)

### ISSUE THREAD

**Issue by willstocks-tech** [EnlighterJS/Plugin.WordPress#154]
Hi Andi,

Would there ever be an option to also style inline code (that is surrounded by back ticks) - similar to `this()` or `display: block;` - but using generic styling?

When I changed the selectors to vanilla pre and code (aka no EnlighterJSRaw), it was highlighting my inline code and it looked _really good_ (IMHO). 

I could try to stylise this via CSS myself manually, however if I ever changed my generic theme, I'd have to then change my CSS as well (duplication). Not only that, but it was so much simpler as it was styling selections/functions/strings all in their relevant different colours, and it just looked really nice! 

Would this be something you'd consider in the future as an option?

**Comment by AndiDittrich** [comment]
inline syntax highlighting is already suported by EnlighterJS, the Enlighter WordPress Plugin and the TinyMCE Editor but **not for Gutenberg**

i'm working on a workaround to add additional styles to the paragraph block which is based on RichText component but this is going to be complicated (Gutenberg code is really annoying...docs are missing...)

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/Plugin.WordPress/blob/master/docs/Usage_VisualEditor.md#use-inline-code-highlighting

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/Plugin.WordPress/blob/master/docs/Usage_Markdown.md#extended-inline-code

**Comment by willstocks-tech** [comment]
Ahaaaa - it's Gutenberg where I'm getting stuck then! 😉 

Thanks Andi - genuinely impressive what you're doing 😁 I'm truly grateful!
