### ISSUE TITLE
[Enhancement] MooTools jsDelivr version bump

### ISSUE THREAD

**Issue by willstocks-tech** [EnlighterJS/Plugin.WordPress#155]
Per earlier discussion in a separate thread (apologies - I hijacked the end of https://github.com/EnlighterJS/Plugin.WordPress/pull/153#issuecomment-467803409 and should've opened this separately, which I'm doing now!):

MooTools from jsdelivr via Enlighter (plugin) is a minor version behind all other CDN's? 

```
self::$cdnLocations['mootools-google'] = '//ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.min.js';
self::$cdnLocations['mootools-cdnjs'] = '//cdnjs.cloudflare.com/ajax/libs/mootools/1.6.0/mootools-core.min.js';
self::$cdnLocations['mootools-jsdelivr'] = '//cdn.jsdelivr.net/mootools/1.5.0/mootools-core-nocompat
```

To get around this, I enqueued MooTools from jsDelivr manually using https://cdn.jsdelivr.net/gh/mootools/mootools-core@1.6.0/dist/mootools-core.min.js (using their GitHub repo as the source!) and it has been working without any issues. The only problem with this is, it means that I'm not loading MooTools only when absolutely necessary (DRI).

I'll switch back to using the plugin enqueued version (v1.5.0) for the time being so that it's only enqueued when necessary via DRI (confirmed working).

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/Plugin.WordPress/commits/master
