### ISSUE TITLE
Special setting required when using Autooptimize

### ISSUE THREAD

**Issue by belidzs** [EnlighterJS/Plugin.WordPress#156]
I'm just opening this issue to raise awareness that Autooptimize might interfere with EnlighterJS so it is necessary to add its javascript files as an exception in Autooptimize's settings:

`Settings / Autooptimize / Javascript options / Exclude scripts from Autoptimize:` 

Add `enlighter/resources/` to the end of the comma separated list

**Comment by AndiDittrich** [comment]
Hi @belidzs ,

the compatibility issue is already known. i can add an additional FAQ entry

**Comment by belidzs** [comment]
Great idea! I was looking for a wiki on GitHub to add this myself but I couldn't find any so I decided it's best to leave it to the authors.

Thanks for this plugin, I really like it.

**Comment by AndiDittrich** [comment]
added to the FAQ!
