### ISSUE TITLE
Enlighter button change the row

### ISSUE THREAD

**Issue by pokertour** [EnlighterJS/Plugin.WordPress#157]
Hello,

i don't know if it's normal but after i've installed your plugins, your button add a second row in my editor look : 
![image](https://user-images.githubusercontent.com/7757451/53745938-69aac700-3ea0-11e9-908b-60f207c10192.png)

How can i put your button on the first row ?
Thx

**Comment by AndiDittrich** [comment]
hi @pokertour ,

that looks very strange and it's not the intended behaviour. do you use some TinyMCE tweaking plugins ? try to disable them

normally the toolbar (current WordPress release, current Enlighter release, Classic Editor Plugin) looks like this:

![image](https://user-images.githubusercontent.com/1474107/53746736-22bdd100-3ea2-11e9-96c9-bb582147918b.png)

best regards, Andi

**Comment by pokertour** [comment]
i'm using tiny mce advanced but i already try to remove it and it did nothing.
I also use Asgaros forum plugin

**Comment by pokertour** [comment]
it's ok, i found the problem, it's my theme that add button in toolbar.
You can close this :)
Thx you :)
