### ISSUE TITLE
Assets loading on pages when no Enlighter block used (DRI enabled)

### ISSUE THREAD

**Issue by willstocks-tech** [EnlighterJS/Plugin.WordPress#159]
Hey Andi

I was just finishing building up a new page on my site (https://willstocks.co.uk/referrals/) and noticed that Enlighter's CSS is being requested, despite there's no Enlighter blocks on the page and I have DRI enabled.

Any ideas as to why this might be?

**Comment by AndiDittrich** [comment]
HI Will,

i cannot see any Enlighter related resources within the page sources/html.
btw. the html of your site is still broken (html tag in the document...)

best regards, Andi

**Comment by willstocks-tech** [comment]
Hi Andi,

Sorry, you might have to hit: https://willstocks.co.uk/referrals/?ao_noptimize=1 - as the EnlighterCSS gets combined by Autoptimize (JS is excluded) - you will see here that the Enlighter CSS file is being requested.

Which part of the HTML is broken? 😟

**Comment by AndiDittrich** [comment]
**HTML**
![image](https://user-images.githubusercontent.com/1474107/54295843-1af1e100-45b4-11e9-9b5d-50183ec5cf87.png)

**Comment by willstocks-tech** [comment]
Ooooh, OK that's really interesting! Great eye Andi 😉 - I'll take a look into that

**Comment by AndiDittrich** [comment]
i will take a short look on the css issue

but generally you should **NEVER** combine dynamic resource invocation with bundeling...this will have a negative performance impact on your site...

**Comment by willstocks-tech** [comment]
Oh, really - why, what is the impact? So far I've only seen a difference in terms of the request size for a page/post _with_ Enlighter content vs _without_ - AO is pretty clever in the way it handles the bundling 😄

**Comment by AndiDittrich** [comment]
in case you're only looking on a **single page** it might work, but imagine a visitor travel through a bunch of pages - each of them enqueues different resources. in this case AO (or any other optimize/caching plugin) has to use **multiple different bundles** and the user has to request the **full** bundle on each page because it cannot be cached by the browser.

**Comment by AndiDittrich** [comment]
regarding you issue: DRI does currently only affect js resources...not the css.
but this cannot be solved because the styles are enqueued in the html head **before** the content has been rendered..therefore the detection didn't take place yet

**Comment by willstocks-tech** [comment]
That is true, although the way I'm currently setup I only see three different bundles: home/archive, single page, post (no code), post (code) - the only reason I'm splitting the two post-types is because when I look at analytics, most people that are visiting for code snippets stick to the code posts rather than venturing on to non-code posts, and vice versa

**Comment by willstocks-tech** [comment]
Ahhhhhh, it's only the JS! Ah, in that case, then DRI is doing its job fine - I don't know why, I thought it was all assets 😄

**Comment by willstocks-tech** [comment]
I shall close this now due to

> but this cannot be solved because the styles are enqueued in the html head before the content has been rendered..therefore the detection didn't take place yet

**Comment by willstocks-tech** [comment]
> **HTML**
> ![image](https://user-images.githubusercontent.com/1474107/54295843-1af1e100-45b4-11e9-9b5d-50183ec5cf87.png)

Worked this out (I think) - I know it's nothing to do with your plugin, but thought I'd let you know that I _think_ I've worked out how that extra `<html>` tag is getting there... https://willstocks.co.uk/php-dom-manipulation-snippet/
