### ISSUE TITLE
Issue: Enlighter plugin triggers multiple HTTP GET calls during page load

### ISSUE THREAD

**Issue by rieckpil** [EnlighterJS/Plugin.WordPress#160]
Hi,

I am using the following Wordpress setup:

```
Server
PHP Version: 7.1.26
PHP JSON Extension: available
Server Software: SunOS
Components
Enlighter Plugin Version: 3.9.0
EnlighterJS Version: 2.13.0
TinyMCE Extension: 3.5.1
Gutenberg Extension: 0.4.0
Environment
Cache writeable: true
Shortcode Processor: Enlighter low-level
```

and when I activate the EnlighterJS plugin I get several HTTP GET calls during page initialization which come from MooTools and result in bad page performance/too much Google Analytics page view:

![enlighterJsBug](https://user-images.githubusercontent.com/14176609/54547450-05126080-49a6-11e9-8951-eed784f43c3b.png)

I've already disabled Jetpack and currently only activated plugins for the The7 Wordpress theme

**Comment by AndiDittrich** [comment]
Hi @rieckpil ,

EnlighterJS itself doesn't trigger any XHR requests. 
i'm not sure whats going on in your special case. do you use jquery or another javascript framework ? maybe it's an incompatibility with MooTools...

best regards, Andi

**Comment by rieckpil** [comment]
Hi @AndiDittrich,

currently only jQuery and some custom JS from the Wordpress Theme

**Comment by AndiDittrich** [comment]
please try it with one of the WordPress default themes on your testing site....
most of the MooTools issues are caused by weak javascript code....therefore it will be removed in the upcoming release

**Comment by rieckpil** [comment]
Works fine with one of the default themes. When do you plan to release the new version and what exactly gets fixed?

Thank you so far!

**Comment by AndiDittrich** [comment]
in the next few month. EnlighterJS3-RC2 is already out (no external dependencies, no frameworks needed)

**Comment by rieckpil** [comment]
Do you have a working plugin version based on EnlighterJS3-RC2  already?

**Comment by AndiDittrich** [comment]
you can use EnlighterJS3-RC2 with the current WordPress Plugin - see https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat

**Comment by rieckpil** [comment]
Thanks for the link, works like charm: https://rieckpil.de/howto-simple-crud-table-with-jsf-2-3-and-primefaces/

Do you have any donation link?

**Comment by AndiDittrich** [comment]
perfekt ;)

Es ist leider relativ problematisch eine "Spenden" Funktion in Deutschland bereitzustellen da der Begriff/Funktionalität eigtl. ausschließlich im Zusammenhang mit gemeinnützigen Organisationen verwendet werden kann. 

Soetwas als Privatperson anzubieten - wie es viele machen - ist eine Grauzone (wird von einigen Zahlungsdienstleistern geduldet da diese damit Geld verdienen..). Als Firma geht es defakto nicht möglich....

Bleiben nur 2 Optionen: 

- eine Stiftung oder Verein gründen der soetwas darf (was kostentechnisch ein absolutes Verlustgeschäft ist)
- einen Onlineshop erstellen der irgendwelche Sticker o.ä. verkauft....ist nur die Frage ob sich soetwas lohnt bzw. ob die internationale Unterstützer dies überhaupt nutzen würden...

**Comment by rieckpil** [comment]
Verstehe :D Danke dir dennoch vielmahls  👍
