### ISSUE TITLE
Expose internal config object via static method

### ISSUE THREAD

**Issue by pjotrsavitski** [EnlighterJS/Plugin.WordPress#161]
Is there a way to expose the **EnlighterJS_Config** within the admin context or any to how would it be possible to extract the config values?

`appendInlineEditorConfig` of `ResourceLoader.class` seems to be exposing the **EnlighterJS_EditorConfig** but not the standard config itself.

The requirement is to run the Enlighter on one of the admin pages (it is a bit more complicated and requires running the `EnlighterJS.Util.Init` explicitly).

A hint on how to extract the configuration data without creating an instance of the `ConfigGenerator.class` and passing all the requirements in would be as good as exposing the data itself.

**Comment by AndiDittrich** [comment]
There is no API or something similar available...

but all options are stored in the database (wordpress options api) ...just retrieve the required ones via [get_option](https://developer.wordpress.org/reference/functions/get_option/)

**Comment by pjotrsavitski** [comment]
Thanks for a quick response. Would it be possible to expose that data alongside the EditorConfig that is currently accessible for the next version?

**Comment by AndiDittrich** [comment]
i can add a method which return the full plugin config (the editor config is derived from it)

**Comment by pjotrsavitski** [comment]
Thank you, that should do the trick.

**Comment by AndiDittrich** [comment]
In Enlighter v4 you can retrieve the full plugin config (not the theme settings) after `init` has been triggered via:

```php
$enlighter = Enlighter::getInstance();

$enlighterConfig = $enlighter->getPluginConfig();
```
