### ISSUE TITLE
[Question] Dequeue unused theme CSS

### ISSUE THREAD

**Issue by willstocks-tech** [EnlighterJS/Plugin.WordPress#165]
Hey Andi,
Hope you're well?
I may have asked this before, but I can't find the issue (and I think you mentioned the next version will be minimising the CSS and JS dependencies!)

I currently have a custom theme setup for my site:
![image](https://user-images.githubusercontent.com/43744514/57016272-21462600-6c11-11e9-8eb1-feaf9cb39e03.png)

However, when I view a page that has code highlighting enabled (DRI), and I review my CSS - I'm still seeing all of the CSS for all of the other standard/external themes (Godzilla etc.).

I still have the following enabled though:
![image](https://user-images.githubusercontent.com/43744514/57016424-e690bd80-6c11-11e9-9327-ec8464874be5.png)

Do I need to disable the Enlighter CSS and enqueue only the custom CSS path?

**Comment by AndiDittrich** [comment]
the "standard" EnlighterJS.css file contains some basic styles which are required for the highlighting.
you can download the latest v2 release and rebuild the css manually - then override `resources/EnlighterJS.min.css` 

the uncompressed dist files area available on https://github.com/EnlighterJS/EnlighterJS/blob/v2-legacy/Build/EnlighterJS.css

**Comment by willstocks-tech** [comment]
Ahhh yes, it's line 333 onwards! 

Will I need to keep the "parent theme" that the custom theme was based on? For example, I based my custom theme on the "Panic" theme, but obviously now it is a custom theme, so I assume all I need is the core enlighter styles + my custom theme CSS?

I've just weighed it up (for my use case - Enlighter + a single, custom theme):
###### Un-minified
Full/Original CSS: ~57KB
Enlighter core CSS: ~8KB

###### Minified
Full/Original CSS: ~36KB
Enlighter core CSS: ~6KB

###### Minified + GZIPped
Full/Original CSS: ~6KB
Enlighter core CSS: ~2KB


Not _massive_ numbers by any means (and gzip makes it much more manageable, as well as caching takes care of it all after first load anyways), but still a decent chunk of styles that are going potentially unused (especially if a user hasn't configured gzip on their server)

**Comment by AndiDittrich** [comment]
you just need the core + custom css.

the "custom" themes are based on [special versions](https://github.com/EnlighterJS/Plugin.WordPress/tree/master/views/themes) of the origin themes

**Comment by willstocks-tech** [comment]
Nice one - thanks Andi! I will give that a go on my install and will close this off now - thank you for your very prompt assistance once again! 😁

**Comment by willstocks-tech** [comment]
All sorted - thanks @AndiDittrich 

Just to confirm, I actually had to rebuild the `cache/EnlighterJS.custom.css` file, not the/just the  `resources/EnlighterJS.min.css` file. Once that was done, it was all sorted and my CSS file size actually decreased by a decent amount 😄
