### ISSUE TITLE
Inline Code is not working but Block Code is working

### ISSUE THREAD

**Issue by guitorioadar** [EnlighterJS/Plugin.WordPress#168]
I am trying to write blog and i just love this plugin. I don't want to switch to another. But i recently the inline code in this plugin is not working. But it is showing in the editor. Let me show you.

![enlighter1](https://user-images.githubusercontent.com/13439371/57414601-a38aa780-721a-11e9-8cc4-e0d1b18c6b7a.PNG)

the above is the wordpress editor. It is showing the format but in the post it is not working. 

`<code class="EnlighterJSRAW" data-enlighter-language="java">setStudentName()</code>
 and 
<code class="EnlighterJSRAW" data-enlighter-language="java">setStudentRoll()</code> 
method.`

They are not showing the way it must show. It was showing the default format of the wordpress itself. But the block code is working. Please help me with it.

My wordpress theme is: oceanwp
My wordpress version is: 5.2
My Enlighter theme is: Enlighter
My Enlighter Default Language is: java
Website: https://androvaid.com/android-mvc-example/

**Comment by AndiDittrich** [comment]
HI @guitorioadar ,

i assume you're using the "Classic Editor" and not Gutenberg ?

The inline code on your site didn't contain any of the required Enlighter attributes (you've posted them above)

**Code of your paragraph**
![image](https://user-images.githubusercontent.com/1474107/57436651-6802d400-7240-11e9-9600-23d39fb3f267.png)

maybe there are some other code plugins active which are filtering the attributes ? Please try to disable all other plugin and another theme (e.g. one of the WordPress standard themes) on your testing site.

best regards, Andi

## Working Example ##

**Classic Editor**
![image](https://user-images.githubusercontent.com/1474107/57437202-90d79900-7241-11e9-8fd0-cd5a886b781a.png)

**Result**
![image](https://user-images.githubusercontent.com/1474107/57437219-9df48800-7241-11e9-88ce-781410bb2433.png)

**Comment by guitorioadar** [comment]
Here we can see that we have created constructor of the this controller which gets two parameters. One is the model and the another one is the view. As the view we are getting MainActivity. we can get data from the database of from the view and set the data to the model with the help of 
`<code class="EnlighterJSRAW" data-enlighter-language="java">setStudentName()</code>`
and
`<code class="EnlighterJSRAW" data-enlighter-language="java">setStudentRoll()</code>`
method. The other two get methods will return the values from the model. This is one of the examples of <strong>Encapsulation. </strong>

This is the editor code of this post. But after updating, is is just like as you have shown above.

In my another post: image
![enlighter2](https://user-images.githubusercontent.com/13439371/57474891-02046400-72b5-11e9-9a79-ae410613adf6.PNG)

in this post enlighter is working.

The plugins that i use are
1. Akismet
2. Contact Form 7
3. Disable Gutenberg
4. Enlighter - Customizable Syntax Highlighter
5. Google Analytics Dashboard for WP (GADWP)
6. Jetpack by WordPress.com
7. Ocean Custom Sidebar
8. ocean Extra
9. Shortcode Ultimate
10. Wp-PostViewer
11. Yoast SEO

**Comment by AndiDittrich** [comment]
that's very strange because the Enlighter TinyMCE doesn't trigger any action/filter on-save/on-update
therefore i assume that some filter removes the attributes.

do you edit the post as admin ? the wordpress kses filters restrict the use of some attributes but Enlighter [allows](https://github.com/EnlighterJS/Plugin.WordPress/blob/master/class/Enlighter.php#L169) this special attributes

**Comment by guitorioadar** [comment]
i always edit the posts as admin mode...

**Comment by AndiDittrich** [comment]
please try to reproduce the issue within a **clean wordpress installation** without any plugins and one od the default themes

**Comment by zeon77** [comment]
Hello @AndiDittrich!
I have the same issue like @guitorioadar .

After some hour of researching i could reproduce the issue.

1. deactivate all plugings, but Enlighter and TinyMCE Adv.
2. nothing happens, inline code highlighting still doesn't work
3. updating post, inline code highlighting starts to work
4. activating **and set up Jetpack** plugin (inline code highlighting still works)
5. updating post and inline code highlighting stop working

thanks.

**Comment by AndiDittrich** [comment]
JetPack is taking over the markdown elements (i assume that your referring to markdown inline code)
You can exclude inline+block codes from being processed by jetPack (Enlighter -> Extensions -> JetPack).

**Comment by zeon77** [comment]
I enabled Enlighter -> Extensions -> JetPack -> "Markdown codeblocks" setting, but nothing changed.

I think my issue is not specific to markdown.

Here is what i'm doing:
1. In TinyMCE editor i'm inserting an inline code with the "Code Insert" toolbar icon, with Language: CSS, and Mode: Inline-Code.
2. In HTML editor i see the following:
`<code class="EnlighterJSRAW" data-enlighter-language="css">.hello { color: white; }</code>`
3. updating the post, and in the browser i see only the following:
`<code>.hello { color: white; }</code>`
4. if i disable Jetpack (its not enough, on its own), **and updating the post (without any modification)**, i get two element in the browser:
`<div class="enlighter-default enlighter-v-inline"> ... many span element inside </div>`
`<code class="EnlighterJSRAW enlighter-origin" data-enlighter-language="css">.hello { color: white; }</code>`

am i doing something wrong?

Thank you for your patience @AndiDittrich .

**Comment by AndiDittrich** [comment]
it sounds like JetPack is doing some weird things with the Enlighter codeblocks...

update+saving posts is required in case of JetPack (internal behaviour - formattings are applied `onSave` and not when the content is retrieved by the page)
