### ISSUE TITLE
URL in code creates issues

### ISSUE THREAD

**Issue by mmajcica** [EnlighterJS/Plugin.WordPress#169]
In case I enter an url in the code sample I am unable to save or publish my post anymore.

![image](https://user-images.githubusercontent.com/3026551/57465970-fe0a1f00-727f-11e9-9765-5949986fb491.png)

Any idea on what can cause this or and how to solve this issue?

Thanks

**Comment by AndiDittrich** [comment]
Hi @mmajcica ,

what happens in case you use the Gutenberg "standard" code block ?

**Comment by mmajcica** [comment]
Hi,

Exactly the same in case a put a simple <a> in a paragraph block.

Any idea what can cause that?

Thanks

**Comment by AndiDittrich** [comment]
maybe... in the past there were 2 similar issues...they were caused by an IDPS running on the webserver/network which blocks the request (this can also been caused by some kind of weak router or endpoint security suite)

**Comment by mmajcica** [comment]
Before Gutenberg it all worked well. My WP instance runs on Strato
provider, I suppose things network wise are all OK.
Should be a setting or something not allowing urls to be persisted or
similar.

**Comment by AndiDittrich** [comment]
do you see any errors in the webbrowser console ?

within the last few days i've experienced some weak errors when editing with Gutenberg... clearing the "Local Storage" of the browser solves the issue in my case

**Comment by mmajcica** [comment]
Hi Andi,

nothing was shown in the console, however clearing the "Local Storage" did
the trick.

Thanks
