### ISSUE TITLE
When will Golang highlighting be added?

### ISSUE THREAD

**Issue by huornlmj** [EnlighterJS/Plugin.WordPress#170]
Feature request: When will Golang highlighting be added?

**Comment by AndiDittrich** [comment]
With the next major release (WordPress Plugin v4 + EnlighterJS v3) - the WordPress plugin needs a complete rework..

to try EnlighterJS v3 with the current release (v3) please take a look on the [experimental integration](https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat)
