### ISSUE TITLE
font size not working

### ISSUE THREAD

**Issue by rollrodrig** [EnlighterJS/Plugin.WordPress#172]
I change the font size in the configuration section but it is not reflected in the post

**Comment by AndiDittrich** [comment]
HI @rollrodrig ,

your issue seems to be related to the WordPress plugin and **not** the Gutenberg editor plugin.

which setting did you change in the ThemeCustomizer (please provide a screenshot) ?

**Comment by rollrodrig** [comment]
Sure here the screenshots.
2em font size but is not reflected in the post.
![Screen Shot 2019-05-20 at 8 59 59 AM](https://user-images.githubusercontent.com/12551728/58027240-d3209600-7add-11e9-9450-ce6ccf0b2c80.png)


![Screen Shot 2019-05-20 at 9 00 32 AM](https://user-images.githubusercontent.com/12551728/58027265-dfa4ee80-7add-11e9-837b-3a64cf7fa71e.png)

I had to change it manually using custom css

**Comment by AndiDittrich** [comment]
please read the **headings** and **tab names** within the settings page...you're currently changing the fonts of the **TinyMCE** plugin....

to change the theme settings you have to enable the **ThemeCustomizer** by selecting the theme `WP Custom` as default (as mentioned in the FAQ)
