### ISSUE TITLE
Enlighter 4 BETA 1

### ISSUE THREAD

**Issue by AndiDittrich** [EnlighterJS/Plugin.WordPress#178]
i've just release the first beta version of Enlighter v4 including EnlighterJS v3.1.0

https://github.com/EnlighterJS/Plugin.WordPress/releases/tag/v4.0.0-BETA1

-----

i appreciate your feedback - please open a new issue for specific bugs

**Comment by Suplanus** [comment]
Big thanks for your great work!
I would like to reopen #31 see [my comment](https://github.com/EnlighterJS/Plugin.WordPress/issues/31#issuecomment-513710130).

**Comment by westerdaled** [comment]
Hi any more news on the Gist support . 
 I am still using Beta 1 btw so happy to test the next if this ready to be released .

**Comment by AndiDittrich** [comment]
no updates yet sry

**Comment by westerdaled** [comment]
No probs

**Comment by ajtruckle** [comment]
I have just upgraded to the V4 beta. I am just trying to find an example of how to format the code in the bbPress topics as the old way doesn't work.

**Comment by AndiDittrich** [comment]
it works but you have to enable it - all settings have been changed and there is no upgrade path available

**Comment by ajtruckle** [comment]
This is what I am seeing:

![beta4](https://user-images.githubusercontent.com/7985331/74588717-c5f5f080-4ff6-11ea-8bee-1331a59a6475.png)

**Comment by AndiDittrich** [comment]
just fix the plugin error: you uploaded the files to the wrong location

**Comment by ajtruckle** [comment]
I fixed that issue and I have switched on bbPress again via the "Extensions" section in the settings like before. But it is not working I am afraid. Sorry:

https://www.publictalksoftware.co.uk/support-forums/topic/this-is-a-test-for-debugging/

**Comment by AndiDittrich** [comment]
i didn't have to to investigate it right now - it seems the extension is not enabled/working

**Comment by ajtruckle** [comment]
Typo in help:

Generic-Shortcodes: [enlighter lang="" theme="" group="" tab="" highlight="" offset="" linenumbers=""] YOUR CODE **[/js]**

for now I use v3

**Comment by ajtruckle** [comment]
> i didn't have to to investigate it right now - it seems the extension is not enabled/working

Ok,

**Comment by ajtruckle** [comment]
> i didn't have to to investigate it right now - it seems the extension is not enabled/working

When you do have time to have a look, then I will be happy to beta test for you on my staging site.
