### ISSUE TITLE
Not compatible with Autoptimize plugin

### ISSUE THREAD

**Issue by parvez1487** [EnlighterJS/Plugin.WordPress#179]
displaying plain code when the Autoptimize plugin is enabled.I have implemented into below link.

https://www.uibootstrap.net/bootstrap-css/simple-html-contact-form-to-email-using-ajax-and-php/

**Comment by AndiDittrich** [comment]
as mentioned in the [FAQ](https://github.com/EnlighterJS/Plugin.WordPress/blob/v3/docs/FAQ.md#autooptimize-compatibility-settings) you have to exclude the EnlighterJS resources (which are already optimze) from the plugin
