### ISSUE TITLE
Support for Generics

### ISSUE THREAD

**Issue by victorromeo** [EnlighterJS/Plugin.WordPress#181]
The support for generics appears to be either not complete, or undocumented.  Can you advise the best way to encode the following code?  The less-than and greater-than appear to be correctly encoded, but they don't always render correctly in the view.

public IList&lt;Vehicle&gt; GetVehicles() { ... }
or 
public IList&lt;T&gt; GetItems&lt;T&gt;() { ... }

These appear to change the item into lowercase, when displaying them on the final view, and they are auto closed within the code group.  See below how Vehicle is changed to vehicle.

public class VehicleRepository {
  private DbConnection _dbConnection;
  public VehicleRepository(DbConnection dbConnection) {
    _dbConnection = dbConnection;
  } 

  public IList&lt;Vehicle&gt; GetVehicles() {
    ...
  }
}

![Screenshot from 2019-08-01 16-54-44](https://user-images.githubusercontent.com/3838993/62272104-a09bfd80-b47d-11e9-82df-f500c15eea40.png)

**Comment by AndiDittrich** [comment]
Hi @victorromeo ,

i assume that you're using the **deprecated** shortcode mode with the "legacy (WordPress based)" shortcode processor right ?

the trailing tag is caused by unescaped html sequences. do you edited the content in text mode ?
