### ISSUE TITLE
Show Title without CodeGroup

### ISSUE THREAD

**Issue by gitsnow** [EnlighterJS/Plugin.WordPress#182]
I'm currently trying to migrate from Crayon to Enlighter.  I've tried out the stable and Beta versions of Enlighter and was wondering if there's a way to have the title show without having to add the data-enlighter-group attribute?

The Beta version converts legacy Crayon titles to data-enlighter-title, but they don't seem to display unless a group is set.  Is it meant to work this way or is this a bug?

**Comment by gitsnow** [comment]
As a temporary workaround I edited modules/compatibility/Crayon.php and added the following lines

`if (isset($match[2])){
$htmlAttributes['data-enlighter-group'] = trim($match[2]);
        }`

This just sets the data-enlighter-group attribute value to the Crayon pre title.  This probably won't work if the Crayon title is blank, but again this is just a temporary hack.

**Comment by AndiDittrich** [comment]
HI @gitsnow ,

this is the intended behaviour - EnlighterJS doesn't support titles at the moment. 
I've just copied+converted the title attribute for future use.
