### ISSUE TITLE
Code display style issues

### ISSUE THREAD

**Issue by Ryan-Gao** [EnlighterJS/Plugin.WordPress#187]
I use EnlighterJS plugin throughout the site, It works most of the time, I recently created a new page where the code appears to have some issues: **After the page loads, the code must be refreshed again to display properly**
The picture below is a comparison
![QQ图片20190908171004](https://user-images.githubusercontent.com/28983335/64486103-8a8f1300-d25b-11e9-978a-9fcc21284a2f.jpg)
The left is the error display and the right is the refreshed normal style

here is a example url: https://www.powerbigeek.com/datetime-functions/

**Comment by AndiDittrich** [comment]
you're using another syntax highlighting plugin which conflict with EnlighterJS - the markup on the left is not created by Enlighter nor the editing plugins

**Comment by Ryan-Gao** [comment]
> you're using another syntax highlighting plugin which conflict with EnlighterJS - the markup on the left is not created by Enlighter nor the editing plugins

Thanks for your quick reply, I checked all the plugins,  Enlighter 3.10.0 is the only plugin installed for syntax highlighting. maybe  there is another plugin which conflicts with it ? Can you tell me which one it is ? thanks！

On the left and right of the figure above is the same article, The edit page  looks like this
![PowerBIGeek_20190908_235108](https://user-images.githubusercontent.com/28983335/64490871-318fa100-d294-11e9-84ed-8afd94d0eaf6.jpg)

**Comment by Ryan-Gao** [comment]
Hi Andi , I consulted the theme developers, The theme I used has a built-in code highlighting function, which may conflict with the plugin. Now The problem is that Enlighter plugin js cannot load without refreshing the page, Are there any workarounds? 

thanks

**Comment by Ryan-Gao** [comment]
This problem is solved. Thanks for your help
