### ISSUE TITLE
Enlighter 4 BETA 1 - theme customizer not working

### ISSUE THREAD

**Issue by xstefank** [EnlighterJS/Plugin.WordPress#188]
I manually installed Enlighter Version 4.0-BETA1 to my WordPress 5.2.3. Everything works but when I click Theme customizer nothing shows up:

![2019-09-15-1568550287_1702x800](https://user-images.githubusercontent.com/9353101/64921524-b31b8d80-d7c4-11e9-9b32-a41bfda9df9f.png)

Any pointers how I can get this running, please?

**Comment by AndiDittrich** [comment]
The theme customizer is not yet available

**Comment by xstefank** [comment]
@AndiDittrich thanks, I am just starting with Enlighter and I saw it in the docs. I will then wait for the later release.
