### ISSUE TITLE
Only logged in users can see the snippet

### ISSUE THREAD

**Issue by silversillu** [EnlighterJS/Plugin.WordPress#189]
I used this code in my blog post: https://gist.github.com/silversillu/52ad72eaee5450ace862f39e52f6b953

The problem is that only logged in users can see it. Non-logged-in users see nothing, also there is nothing in the DOM.

When I make the script a bit shorter, it shows up.

**Comment by AndiDittrich** [comment]
the WordPress plugin has its own repository - i've moved your issue.

----

i assume that you're using some kind of caching plugin (wp super cache...) - invalidate the cached content and it should work

**Comment by silversillu** [comment]
> the WordPress plugin has its own repository - i've moved your issue.
> 
> i assume that you're using some kind of caching plugin (wp super cache...) - invalidate the cached content and it should work

A bit strange situation but you seem to be right. Clearing all cache didn't fix it but disabling the "WP Fastest Cache" fixed it. Re-enabling cache broke it again.

**Comment by AndiDittrich** [comment]
in case the "Fastest Cache" plugin tries to "optmize" the already optimized js+css resources it could cause the issue

**Comment by silversillu** [comment]
> in case the "Fastest Cache" plugin tries to "optmize" the already optimized js+css resources it could cause the issue

Had to disable CSS minifier. Now works fine. Thanks!
