### ISSUE TITLE
Support for  rendering Gists

### ISSUE THREAD

**Issue by westerdaled** [EnlighterJS/Plugin.WordPress#190]
Hi 

Firstly, noticed I am running an older version  of the pluging so I guess need to upgrade 
![enlightener plugin latest](https://user-images.githubusercontent.com/937208/66342954-7c0f4680-e942-11e9-8016-02a3396f090a.PNG)

I really like the support you have provided in Gutenberg  and wondered if this could be extended for reference Gist URLs on Github. It would mean keep my code snippets under scm.

**Comment by westerdaled** [comment]
Ok I will stay with V3 until the V4 beta is out . Should I still be using Enlighter Compatibility Version 0.1 and if not is there any upgrade details?

**Comment by AndiDittrich** [comment]
v4-beta1 is available since july - https://github.com/EnlighterJS/Plugin.WordPress/releases

* delete Enlighter v3 plugin
* delete compatibility plugin
* install v4-beta1

**Comment by westerdaled** [comment]
Hi did have a few issues installing v4-beta1 with the install namely:

- couldn't completely delete previous enlighter dir with FileZila  due to the permissions of a file in the assets dir
- Also uploading and activating \Plugin.WordPress-4.0.0-BETA1,zip does't work correctly as this unzipped source needs to be uploaded to the /enligher dir

Once, I am over that, I find the plugin works fine and even accepts the markup of the previous Enghter v3 plugin. Excellent news 😀 as no having to edit multiple posts. 

Happy to test out the Gist support when it becomes available as this give this plugin steroids!

**Comment by westerdaled** [comment]
I have found another issue.

I recently my humble blog to a friend's hosting company mainly due to what [Uptime robot ](https://uptimerobot.com/) revealed.
Now this hosting is a bit more wizzy and does stuff like lazy loading etc which seems to stopped enlighter V4 working ; although you wouldn't think so from the status page: 


![enlighter setup](https://user-images.githubusercontent.com/937208/77313049-0e41b600-6cfb-11ea-908b-fe893769b4cf.PNG)

Should I simply delete and reinstall again and, or disable CSS caching?

**Comment by AndiDittrich** [comment]
Hi @westerdaled,

please create a new issue and describe whats not working. external resource caches are not supported by the plugin

**Comment by westerdaled** [comment]
Ok , will look at the external resource caches and see if there is still and issue to report.

**Comment by westerdaled** [comment]
Yes it was a caching issue on our end.  Btw I noticed Enlighterv4 is now released: did you add the gist support as mentioned in this post.

**Comment by AndiDittrich** [comment]
hi @westerdaled ,

the pro/enterprise version are not available yet

**Comment by westerdaled** [comment]
Ok, do you have further details on those editions?

**Comment by AndiDittrich** [comment]
what do you want to know ?
