### ISSUE TITLE
How do I enable PowerShell as the default language?

### ISSUE THREAD

**Issue by yobyot** [EnlighterJS/Plugin.WordPress#191]
It looks like [PowerShel](https://wordpress.org/support/topic/request-powershell-and-typescript-languate-support/)l support was added quite some time ago, but it doesn't appear in the list of default languages. How would I enable it?

Enlighter is (finally) freeing me from the woes of the now-abandoned Crayon Syntax plugin. Really appreciate the capabilities in this plugin.

Thanks!

**Comment by AndiDittrich** [comment]
Hi @yobyot 

powershell support has been added to EnlighterJS v3 - you have to use Enlighter v4-beta1.

btw. the "standard" language setting has been removed

**Comment by yobyot** [comment]
Thanks.
