### ISSUE TITLE
The webpage would be blank the first time I open the page until I refresh it

### ISSUE THREAD

**Issue by fatsky** [EnlighterJS/Plugin.WordPress#196]
Every time when I open a page with Enlighter, it would become a blank page at first.And then it will work properly when I refresh.The problem disappeared when this plugin was disabled.

**Comment by fatsky** [comment]
I changed my theme and found the problem fixed. But I still don't know why. Here's my website with the problem: blog.icysky.site. You will see the static cache at first now(Just like that everything works well except enlighter).

**Comment by AndiDittrich** [comment]
it's caused by the ajax based page loading and MooTools framework used by EnlighterJS v2

you have 2 possibilities to solve the issue:

* disable ajax loading feature
* use Enlighter v4-BETA1 which works without MooTools
