### ISSUE TITLE
Incorrect alignment and line number empty 

### ISSUE THREAD

**Issue by Arafa-microsys** [EnlighterJS/Plugin.WordPress#198]
My problem is when I add a code in my post, it will show with the wrong alignment plus line number is empty, what I can do to overcome this problem?
The problem has shown here
https://arafamicrosys.com/2019/12/14/test/

**Comment by AndiDittrich** [comment]
your themes css overrides a lot of the EnlighterJS rules - therefore the styles are completely broken..

to investigate the issue use [Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools) and inspect the dom/affected css rules
