### ISSUE TITLE
Dead link in "Option use_smilies is enabled" warning

### ISSUE THREAD

**Issue by theHacker** [EnlighterJS/Plugin.WordPress#199]
Just installed the plugin. On the admin page it shows a warning `Enlighter Plugin Warning: Option use_smilies is enabled. Legacy smiley sequences like :) are replaced by images which also affects posted sourcecode. - view help`. Clicking the "view help" link is a dead link.

It goes to: `https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs/PluginNotifications.md`
It should go to: `https://github.com/EnlighterJS/Plugin.WordPress/blob/v3/docs/PluginNotifications.md`

---

Components
Enlighter Plugin Version: 3.10.0
EnlighterJS Version: 2.13.0
TinyMCE Extension: 3.5.1
Gutenberg Extension: 0.4.0

**Comment by AndiDittrich** [comment]
hi @theHacker 

thanks for the hint. it won't be fixed for v3 - the next release will be v4
