### ISSUE TITLE
Plugins do not work when the article page is not the first page opened

### ISSUE THREAD

**Issue by sliyoxn** [EnlighterJS/Plugin.WordPress#202]
if you enter the article page from the home page, the plugin do not work until you refresh it
![image](https://user-images.githubusercontent.com/43871064/72365384-1269ba00-3733-11ea-9156-d62b5301babf.png)
![image](https://user-images.githubusercontent.com/43871064/72364138-f1a06500-3730-11ea-81ba-7c1396224bcb.png)

the wrong case
![image](https://user-images.githubusercontent.com/43871064/72364337-51970b80-3731-11ea-8087-e5f6ab3924bf.png)
if you refresh the page, the plugin work
![image](https://user-images.githubusercontent.com/43871064/72364404-6c698000-3731-11ea-993e-1aba13470f88.png)

I guess the reason for the problem may be the highlight.min.js will highlight the code block，but this js file only execute once, it only be executed when first be loaded, enter the article page from others page will not load the highlight.js.min again, so it do not execute again. It's just a guess......

Could you tell me how to solve it?Thank you very much.

**Comment by sliyoxn** [comment]
> if you enter the article page from the home page, the plugin do not work until you refresh it
![image](https://user-images.githubusercontent.com/43871064/72365273-dc2c3a80-3732-11ea-91e5-45cb1a4cff61.png)
> ![image](https://user-images.githubusercontent.com/43871064/72364138-f1a06500-3730-11ea-81ba-7c1396224bcb.png)
> 
> the wrong case
> ![image](https://user-images.githubusercontent.com/43871064/72364337-51970b80-3731-11ea-8087-e5f6ab3924bf.png)
> if you refresh the page, the plugin work
> ![image](https://user-images.githubusercontent.com/43871064/72364404-6c698000-3731-11ea-993e-1aba13470f88.png)
> 
> I guess the reason for the problem may be the highlight.min.js will highlight the code block，but this js file only execute once, it only be executed when first be loaded, enter the article page from others page will not load the highlight.js.min again, so it do not execute again. It's just a guess......
> 
> Could you tell me how to solve it?Thank you very much.

**Comment by AndiDittrich** [comment]
disable all kind of "optimization" plugins - i assume that some of your plugins tries to decrease the page load time and adds the attributes `defer` or `async` to the enlighterjs script tags - that won't work.

**Comment by sliyoxn** [comment]
> disable all kind of "optimization" plugins - i assume that some of your plugins tries to decrease the page load time and adds the attributes `defer` or `async` to the enlighterjs script tags - that won't work.

Thank you for you advice,  i check the options in the theme, after close pjax option in the theme, everything works well.

**Comment by AndiDittrich** [comment]
Great! it sounds like an ajax/xhr related issue - you can try Enlighter v4 available on GitHub which includes a full integration for ajaxload via jQuery or JetPack infinite scroll
