### ISSUE TITLE
Support of React JSX syntax?!

### ISSUE THREAD

**Issue by zheleznyak** [EnlighterJS/Plugin.WordPress#204]
Hello,
I'm facing with issue using plugin for WP.
When I added this code:
`const Todos = (todos) => {
  return (
    <ul>
      {todos.map(todo => (
        <li key={todo.id}>{todo.text}</li>
      ))}
    </ul>
  )
}`

this line `<li key={todo.id}>{todo.text}</li>` was automatically converted to `<li key="{todo.id}">{todo.text}</li>`.

How to avoid adding "double quotes"?

**Comment by AndiDittrich** [comment]
Hi @zheleznyak,

Neither EnlighterJS nor the editing plugins are modifying the content. it's a third party/usage issue

how did you insert the code into your page ? i assume via copy& paste ? in this case use the code insert dialog (TinyMCE) or paste directly into the Enlighter Gutenberg block

**Comment by zheleznyak** [comment]
Yes, you're right. Now it's fixed. Thanks
