### ISSUE TITLE
Breaks HTML5 player of Seriously simple podcasts

### ISSUE THREAD

**Issue by asm0dey** [EnlighterJS/Plugin.WordPress#205]
Today during tough debugging session I've discovered that this plugins breaks [Seriously Simple Podcasting's](https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting) HTML5 player. It's being rendered correctly, but `Play` button won't work. It happens even if there is no highlighter block in my podcast (which is my case).

Enlighter plugin version: 3.10.0
Seriously Simple podcasting version: 1.20.11
Gutenberg version: 7.3.0
Wordpress version: 5.3.2
Theme: Shift, version: 1.21

**Comment by AndiDittrich** [comment]
Please use Enlighter v4-beta1 available on GitHub under releases.

the issue is mostly caused by the MooTools library which is required for EnlighterJS v2 - the new release (EnlighterJS v3) has been added to Enlighter v4 which doesn't required any third party libraries anymore

**Comment by asm0dey** [comment]
Easy: but!

1. Highlighting won't work: https://it.asm0dey.ru/2017/07/16/night-studies-lateral/
2. `Enlighter Plugin Error: The plugin is located within an invalid path - the enlighter/ directory name is mandatory` error appears in plugin settings

**Comment by AndiDittrich** [comment]
fix the error ;) https://github.com/EnlighterJS/Plugin.WordPress/blob/v3/docs/PluginNotifications.md#error-the-plugin-is-located-within-an-invalid-path

otherwise the resources (required for highlighting) cannot be loaded
