### ISSUE TITLE
No copy code button 

### ISSUE THREAD

**Issue by hmantri05** [EnlighterJS/Plugin.WordPress#206]
There should be a copy code button in the editor.

**Comment by AndiDittrich** [comment]
in the editor ?

**Comment by hmantri05** [comment]
![1](https://user-images.githubusercontent.com/5938397/74517369-017db580-4f38-11ea-9db3-a01a1dd0b547.JPG)
You need to click on Copy button and manually press Ctrl + C to copy the code. Copy code button should automatically copy the code to clipboard.
![2](https://user-images.githubusercontent.com/5938397/74517546-49044180-4f38-11ea-8df4-4bf1b65f442e.JPG)

**Comment by AndiDittrich** [comment]
the picture above doesn't show EnlighterJS - you're using Crayon!
