### ISSUE TITLE
Using with bbPress

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#207]
How do you use this with BBPress topics / replies?

**Comment by AndiDittrich** [comment]
just enable the bbpress integration within the Enlighter settings (Extensions -> bbpress).
this allows you to use shortcodes or markdown codeblocks

**Comment by ajtruckle** [comment]
Thanks. This is my first time using your highlighter. I have just enabled it. Can you show me an example for showing a xml snippet please. What the short code would look like in the TinyMCE editor in BBPress and the text editor. Thanks.

**Comment by AndiDittrich** [comment]
**never ever use shortcodes within the visual editor!**

shortcode examples are included within the contextual help of the plugin settings page:

![image](https://user-images.githubusercontent.com/1474107/74552706-1cf7b900-4f56-11ea-8fe1-8bf1f5dda0c7.png)


## Shortcode Example ##

```
[xml]
content
[/xml]
```

## Markdown ##

see https://github.com/EnlighterJS/Plugin.WordPress/blob/master/docs/Usage_Markdown.md

**Comment by ajtruckle** [comment]
Ok. So what is going to happen if someone tries to edit a topic or reply afterwards and visual is the active editor?

Will look at the examples. Ta.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AndiDittrich** [comment]
you should enforce text or visual mode. switching between editors (text<>visual> will break the content (whitespaces, specialchars)

but this is a general issue in WordPress and not related to the plugin - most people don't take care of it

**Comment by ajtruckle** [comment]
Understood.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
