### ISSUE TITLE
Using line numbers with BBPress

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#208]
I am using the `[generic]` code formatting option because the code I am showing is a custom language. It looks quite nice "as is":

![Sample-BBPress](https://user-images.githubusercontent.com/7985331/74569767-1b88b980-4f73-11ea-8a49-484a0ebf5359.png)

But I wanted to try and display line numbers. So I adjusted the **shortcode** like this:

`[generic linenumbers="true"]`

But I could not get it to work. I thought I had followed the documentation right?

**Comment by AndiDittrich** [comment]
does the global linenumber setting work ? if not please check the sourcecode - in case `ol` wrapper is used your theme is overriding the line number styles

**Comment by ajtruckle** [comment]
Hi

I am not sure which source code I need to look at. Sorry.

I have slot of css styling in my additional css file of my child theme needed for the site.

But I don’t really know anything about driving into the website source code.

I can tell you the global setting is actually tick. So it is just not working on my site.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
I don't quite understand this. When I view the page source with IE, there is this first sectionL

![Snap1](https://user-images.githubusercontent.com/7985331/74587464-92ad6480-4fea-11ea-9f59-8d325a0850d3.png)

Then, there is a second element with the `ol` elements you referred too:

![Snap2](https://user-images.githubusercontent.com/7985331/74587476-c25c6c80-4fea-11ea-862c-44ec511356e0.png)

And the code also appears again inside that second block as a lump.

So I don't know how to proceed.

**Comment by ajtruckle** [comment]
If I use this styling:

`list-style-position: inside;`

Then it seems to work::

![Snap3](https://user-images.githubusercontent.com/7985331/74587550-d359ad80-4feb-11ea-893d-0cac394e34b7.png)

I stumbled on that from this StackOverflow [question](https://stackoverflow.com/questions/12447611/css-list-style-type-not-working). So is there a place in your plugin that I can add this custom styling, or must we put something into my child theme **Additional CSS** area?

**Comment by ajtruckle** [comment]
Could it just be the width of the `ol li` objects or something? For example if I change it to Godzilla:

![Snap4](https://user-images.githubusercontent.com/7985331/74587650-7959e780-4fed-11ea-9ff2-2b4e6da7109a.png)

This looks like it should be able to show the text to the left but it won't show unless I use `inside` which is wrong.

**Comment by ajtruckle** [comment]
If I use this additional CSS it will work:

```
#bbpress-forums div.bbp-reply-content ol li
{
	list-style-position: inside;
}
```
But my concern is that the above will affect standard `ol li` objects and not limit it to just the `EnlighterJS` elements.

**Comment by ajtruckle** [comment]
I used this:

`
#bbpress-forums div.bbp-reply-content ol li.odd, #bbpress-forums div.bbp-reply-content ol li.even
{
	list-style-position: inside;
}`

Please tell me if it was wrong. It seems the `bbpress-forums` styling is overriding the `.EnlighterJS` styling in the CSS hierarchy. The above would fail with the `.bbp-topic-content` elements too.

This must have come up before for bbPress users. What is the safest way to get this styling correct just for the **.EnlighterJS ol li** elements?

**Comment by AndiDittrich** [comment]
```css
ol.EnlighterJS, ul.EnlighterJS{
list-style-position: inside !important;
}
```

**Comment by ajtruckle** [comment]
Thank you. That looks like it is working for me and line numbers are showing.
