### ISSUE TITLE
404 - Enlighter Plugin Warning: Option use_smilies is enabled

### ISSUE THREAD

**Issue by xermus** [EnlighterJS/Plugin.WordPress#210]
I just installed your plugin for the first time. There is a notifcation showing:

`Enlighter Plugin Warning: Option use_smilies is enabled. Legacy smiley sequences like :) are replaced by images which also affects posted sourcecode. - view help`

but the link "view help" is leading to a 404 page.

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/Plugin.WordPress/blob/v3/docs/PluginNotifications.md

the current release wp version has been moved into the `v3` branch, therefore all of the links are currently broken (until next release)

**Comment by AndiDittrich** [comment]
the warning has been removed in v4.1 since the issue got fixed in WordPress core
