### ISSUE TITLE
Buttons on hover with bbPress - not visible

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#211]
According to the demos online when you hover over the code a toolbar should show:

![buttons](https://user-images.githubusercontent.com/7985331/74587998-c4292e80-4ff0-11ea-8f35-4ac9d60f5655.png)

I have checked my EnlighterJS settings and it has them switched on:

![options](https://user-images.githubusercontent.com/7985331/74588015-ee7aec00-4ff0-11ea-9a5c-455beecbace7.png)

But in my bbPress topics no buttons can be seen:

![buttons2](https://user-images.githubusercontent.com/7985331/74588036-25510200-4ff1-11ea-8a7c-469d68938ce9.png)

Yet, as you can see, if I hover over the area for the buttons they are live and I can click. Why can't I see them?

**Comment by ajtruckle** [comment]
Similarly, the highlighting of the current mouse row doesn't see to work. Would you like the link to my forum?

**Comment by AndiDittrich** [comment]
i assume that you're theme styles are overriding a lot of the EnlighterJS core styles...

**Comment by ajtruckle** [comment]
I would guess so. Or the `.bbp-forum` styles are superseding yours. I have provided a link to an example for you if it is going to help us get to the bottom of the issue.

At the moment I am just so pleased that I can input code in my forum topics for the benefit of users. So it will just be nice to get these finer bits like the toolbar buttons visible etc.

**Comment by AndiDittrich** [comment]
![Screenshot_2020-02-15_14-00-23](https://user-images.githubusercontent.com/1474107/74588325-b1682700-4ffb-11ea-96dc-a8fc7164d1a1.png)

the issue is caused by the bb-press id selector....

to avoid such issues in the future EnlighterJS v3 uses another markup structure without standard ol/li elements

**Comment by ajtruckle** [comment]
Thanks. So:

1. Is there a temporary solution to this or must I live with it?
2. I saw your related response about **EnlighterJS v3** [here](https://github.com/EnlighterJS/EnlighterJS/issues/90#issuecomment-586570582) but my problem is that I don't know how to install this EnlighterJS v3.

**Comment by AndiDittrich** [comment]
just override all styles i've disabled (top right of the screenshot)

Enlighter v4-beta1 is available here on GitHub (release section) - you have to install it manually.
