### ISSUE TITLE
Highlighting the whole line?

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#213]
Is it possible to highlight the whole line out of interest?

![F1D601AD-6DE4-47F0-97C2-5EBEDCDDB4EF](https://user-images.githubusercontent.com/7985331/74590168-d1034d80-5003-11ea-993e-8443666c27d7.jpeg)

Fantastic plugin. 😉

**Comment by AndiDittrich** [comment]
of course, just look into the sources and add some css

**Comment by ajtruckle** [comment]
Sorted it. :)

```
.EnlighterJS .specialline {
	background-color: yellow !important;
}
```

Sample:

![HighlightRow](https://user-images.githubusercontent.com/7985331/74591244-293f4d00-500e-11ea-92dd-6afe03438065.png)

**Comment by ajtruckle** [comment]
Just an observation. If I scroll left and / or drag left with a touchscreen the highlight is not done:

![2E2DC19E-9D9F-4689-8EE5-E6D5F5D17AE2](https://user-images.githubusercontent.com/7985331/74591409-adde9b00-500f-11ea-9a2c-77e4481b5d75.jpeg)

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/Plugin.WordPress/issues/31

fixed in EnlighterJS v3

**Comment by ajtruckle** [comment]
Thanks for the link. I had seen that issue but it doesn't make sense to me. In that discussion they are taking about V3 supporting word-wrap or scroll (like the existing WordPress Plugin I am using already does.

So I am not sure how that discussion relates to getting the line to continue rendering the background colour as one scrolls or drags to the right. But I take your word for it.

As you already know I have reverted to the current release version as I could not get V4 to work for bbPress. I will try again on my staging.

**Comment by ajtruckle** [comment]
I confirm that the v4 beta doesn't seem to work right with bbPress so I am sticking with v2 of your plugin and will live with the background colour issue until such a time as v4 beta is tested as functioning with latest bbPress plugin.

Thanks for your help so far.
