### ISSUE TITLE
Colour of the focus row / and line number width woes (again)

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#214]
I have just used your plugin for the first time on an actual [post](https://www.publictalksoftware.co.uk/2020/02/14/meeting-schedule-assistant-v20-0-7-newsletter/) on my site with Gutenberg (in this case not bbPress) and I have to say it was a pleasant experience. :)

I only have two issues that i see:

1/ The colour of the focus row highlight is not that apparent to me (I am colour blind). I have looked for a `hover` css to override the background and I can't see one.

2/ I have a conflict for the width of the line numbers area. In bbPress posts I need to use something like this:

```
ol.EnlighterJS, ul.EnlighterJS {
    padding-left: 50px !important;
    font-size: 10pt !important;
}
```
If I don't use `50px` then I can't see the line numbers. But in a standard "post" that width is too much. It only needs to be `10px`. How can I use one width for bbPress and one for posts?

**Comment by AndiDittrich** [comment]
1. do you mean "highlighted line" mode or just hover ? both settings can be controlled via the theme customizer
2. you can use `#bbpress-forums` as selector

**Comment by ajtruckle** [comment]
1. I mean just hover. 
2. I tried to use #bbpress-forums with the css you already provided me so I could localise the padding to just the forum topic and replies and not general posts but failed.

**Comment by ajtruckle** [comment]
I have made some progress with this.

Firstly, I have applied the following styling (based on your suggestion):

```
#bbpress-forums ol.EnlighterJS {
	padding-left: 50px !important;
}

ol.EnlighterJS {
	padding-left: 0px !important;
}
```

The above seems to work Ok but it might not be foolproof. For example, is a padding of 50px going to be OK if the starting line number is bigger, like 1000? This is why I am not sure if changing the padding is the right thing to do. But at least it works.

As for the focus row (in a standard post) this is what it looks like for me:

![focus-line](https://user-images.githubusercontent.com/7985331/74602323-2ccee480-509f-11ea-8d4f-10b51ee89ba4.png)

That colour is just not standing out for me being colourblind.

**Comment by ajtruckle** [comment]
>  So it seems to me that there is something else that needs to be fixed instead of adjusting this padding property.

I did a side by side comparison of the **Post** v **bbPress Topic** and I noticed a difference. I therefore changed my **Additional CSS** to match the **Post** style, like this:

```
#bbpress-forums ol.EnlighterJS > li, ul.EnlighterJS > li {
  margin-left: 40px !important;
}
```
That did the trick. What I have noticed though is that the line numbering system appears to be designed to cope with numbers up to `999`. As as soon as you use `1001` you will visually lose a character. I don't know if you have noticed that before? The above styling was what I required though and I have tested it with multiple browsers.

> As for the focus row (in a standard post) this is what it looks like for me:

The above issue still stands for me about the colour of row mouse is over.

**Comment by AndiDittrich** [comment]
this are known "side effects" of using the list auto-numbering. EnlighterJS v3 solves this issue using another markup.

just change the color within the theme customizer

**Comment by ajtruckle** [comment]
> this are known "side effects" of using the list auto-numbering. EnlighterJS v3 solves this issue using another markup.
> 
> just change the color within the theme customizer

What do you mean by **theme customiser**? Sorry if I should already know the answer to that one. Are you referring to my WordPress Additional CSS area?

**Comment by AndiDittrich** [comment]
the most powerful feature of the Enlighter plugin - you can customize any theme without css knowledge (as mentioned in every doc) just select `wp custom` as theme and a new tab on the settings page will appear

**Comment by ajtruckle** [comment]
> the most powerful feature of the Enlighter plugin - you can customize any theme without css knowledge (as mentioned in every doc) just select `wp custom` as theme and a new tab on the settings page will appear

That is a **fabulous** feature! :) Issue sorted!
