### ISSUE TITLE
Link to FAQ is broken

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#215]
It takes you here:

https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs/FAQ.md

It 404s.

**Comment by ajtruckle** [comment]
This one (entitled "View Help") also 404s:

https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs/PluginNotifications.md

**Comment by AndiDittrich** [comment]
all links are broken - the docs have been moved. you can still access the old docs within the v3 branch  https://github.com/EnlighterJS/Plugin.WordPress/tree/v3/docs
