### ISSUE TITLE
Switch off linenumbers via shortcode is rendering oddly in bbPress.

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#216]
**Switching off** line numbers doesn't rendering correctly inside bbPress posts. This is not critical for me as I will just keep the line numbers visible. I just wanted to bring it to your attention.

So, this was my code in the post:

```
[xml]
<Meeting BookmarkId="0" PageBreak="0" NumberClasses="1" SpecialEvent="1">
    <Date ThisWeek="W20200406" NextWeek="W20200413">April 6-12</Date>
    <SpecialEvent>
        <Event>Memorial</Event>
        <Location>Bath Hill East, Keynsham, BRISTOL, BS31 1HJ</Location>
        <Date Day="7" 
	    DayShort="Tue" 
	    DayFull="Tuesday" 
	    Month="4" 
	    MonthShort="Apr" 
	    MonthFull="April" 
	    Year="2020" 
	    Memorial="true" 
	    Midweek="true">07/04/2020</Date>
    </SpecialEvent>
</Meeting>
[/xml]
```

The above is fine and displays good:

![SampleXMLNumbers](https://user-images.githubusercontent.com/7985331/74608966-69213580-50dd-11ea-9d0f-0a89cb8e47dc.png)

But if I adjust the shortcode like this:

`[xml linenumbers="false"]`

Then it doesn't like it:

![SampleXMLNoNumbers](https://user-images.githubusercontent.com/7985331/74608981-86ee9a80-50dd-11ea-87ce-cef06a32e22f.png)

I just provided this as feedback as I appreciate your priority will now be on the v4 beta of your plugin.

**Comment by AndiDittrich** [comment]
thanks @ajtruckle 

but all issues of EnlighterJS v2/Enlighter plugin v3 become invalid with the new release

**Comment by AndiDittrich** [comment]
btw. this issue is might caused by you additional css rules which are also altering `ul` elements

**Comment by ajtruckle** [comment]
> btw. this issue is might caused by you additional css rules which are also altering `ul` elements

Yes. It is hard to sort one out without affecting the other. I think for the main part it is functional. Most times I will want line numbers anyway. 

Eventually, when v4 beta works with BBPress it seems all these issues will be a moot point.
