### ISSUE TITLE
bbPress Integration

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#217]
I have several plugins installed with respects to TinyMCE.

- TinyMCE Advanced

I use the above plugin for core formatting of the TinyMCE toolbar, adding buttons that I would like displayed and some default editor behaviour.

- Advanced TinyMCE Configuration

I use the above plugin for additional configuration. Specifically, for:

```
content_style
.mce-content-body{font:12pt Tahoma, sans-serif}
```

- Add AutoSave | Fullscreen Plugins to TinyMCE

The above is my own plugin and will install the TimyMCE AutoSave | Fullscreen Plugins (version 4.9.6) and register them with TinyMCE. It is a simple plugin:

```
<?php
/**
* Plugin Name: Add AutoSave | Fullscreen Plugins to TinyMCE
* Plugin URI: https://www.trucklesoft.co.uk/
* Description: This will install the TimyMCE AutoSave | Fullscreen Plugins (version 4.9.6) and register them with TinyMCE.
* Version: 1.2
* Author: Andrew Truckle
* Author URI: https://www.trucklesoft.co.uk/
**/

/**
 * Add the TinyMCE AutoSave Plugin.
 *
 * @param array $plugins An array of all plugins.
 * @return array
 */
function tsoft_custom_plugins( $plugins ) {
     $plugins['autosave'] = plugins_url( 'mce/', __FILE__ ) . 'autosave/plugin.min.js';
     $plugins['fullscreen'] = plugins_url( 'mce/', __FILE__ ) . 'fullscreen/plugin.min.js';
     return $plugins;
}
add_filter( 'mce_external_plugins', 'tsoft_custom_plugins' );
```

So, we come you your **TinyMCE** plugin for **EnlighterJS**:

1. Do you foresee any compatibility issues with installing and activating this plugin?
2. Can you confirm if it is compatible with **bbPress** environment?

**Comment by ajtruckle** [comment]
Ah, thanks. Your showing me that has reminded me that I do have a activated "snippet" (using the snippets plugin):

add_filter( 'bbp_after_get_the_content_parse_args', 'ajt_enable_visual_editor' );

```
//editor bbpress
function ajt_enable_visual_editor( $args = array() ) {
  global $bsp_style_settings_form ;
  $args['tinymce'] = true;
  $args['teeny'] = false;
  if ($bsp_style_settings_form['Show_editorsactivate'] == 1)  $args['quicktags'] = false;
  return $args;
}
```

So my system is already working along the lines of what you have suggested. So it is strange that my toolbar doesn't behave like yours!

**Comment by AndiDittrich** [comment]
the TinyMCE frontend integration is enabled ? it should work

**Comment by ajtruckle** [comment]
> the TinyMCE frontend integration is enabled ? it should work

Yes, it is switched on. I am happy for you to have a look at my site if you like with admin rights, if it is of any help.

**Comment by AndiDittrich** [comment]
i only have to take a look onto the bbPress editor - do you have a public open topic where everyone can write replies ?

**Comment by ajtruckle** [comment]
I just temporarily added a public forum for you:

https://www.publictalksoftware.co.uk/support-forums/forum/test-forum/

I will delete it when you are finished with it.

**Comment by AndiDittrich** [comment]
i still need an account :(

**Comment by ajtruckle** [comment]
What email address shall I use?

**Comment by AndiDittrich** [comment]
wptest _AT enlighterjs ..... 0rg

**Comment by ajtruckle** [comment]
I added your account. You should be able to reset your password.+

**Comment by AndiDittrich** [comment]
thanks i'm able to login but none of the Enlighter components are loaded. did you added the code snippet to allow non admin users to use the editor components ?

```php
function mm_ejs_frontend_editing($allowed){
      return is_user_logged_in();
}

// add filter
add_filter('enlighter_frontend_editing', 'mm_ejs_frontend_editing');
```

**Comment by ajtruckle** [comment]
I have added a snippet and activated it (everywhere on the site - backend and frontend) for you.

**Comment by AndiDittrich** [comment]
now it's working! the background images of the buttons are hidden by your site css....but you can even use the (3rd and 4th position after "fullscreen")

**Comment by ajtruckle** [comment]
Interesting. Thank you. I wonder why those features you were on about were not activated in the first place when I ticked that option? Now I got to work out about the styling of these buttons! Do you know how we fix that?

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/74734991-0ef4b180-5250-11ea-9dc6-68b839bf9423.png)

**Comment by AndiDittrich** [comment]
it's one of your manual added css rules...you should really take care of that
![image](https://user-images.githubusercontent.com/1474107/74735067-35b2e800-5250-11ea-9d38-656b903a8b8b.png)

**Comment by ajtruckle** [comment]
I have commented that line out. Thanks.

**Comment by AndiDittrich** [comment]
you can also delete the wptest account! have fun!
