### ISSUE TITLE
Is it safe to use "140%!important" for the line-height setting on the code block styles?

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#219]
Just looking at your settings for **code block styles**. There are many :) :

![Code Block Styles](https://user-images.githubusercontent.com/7985331/74738626-3bf49480-524f-11ea-9dcb-5590e672959a.png)

In the notes it mentions units of `em`. I confess I tend not to use these size units. Now, in my bbPress topics I have looked at the fonts and for basic text it uses:

- `font-size: 10pt`
- `line-height: 140%!important`

Are we permitted to use values like `140%!important`?

I feel that I must use something because at the moment the text is small and squashed:

![sample](https://user-images.githubusercontent.com/7985331/74739091-161bbf80-5250-11ea-9e3d-e670da979d34.png)

This is a FANTASTIC plugin.

**Comment by AndiDittrich** [comment]
it's just a 1:1 passthrough to the css generator - you can use any unit you want
