### ISSUE TITLE
Just tried v4 beta with bPress

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#224]
The reason it did not show before was because we did not have the TinyMCE toolbar showing on the front end. So that is good.

I have just tested in my staging sight and in principle it was working for bbPress. The hover toolbar is there etc. But, there is one big issue. Please look:

![v4-beta](https://user-images.githubusercontent.com/7985331/74879053-46528380-5360-11ea-94c5-f77018875209.png)

Once I hit submit to the issue it is showing the enlighter syntax styles code and the raw code underneath.

**Comment by ajtruckle** [comment]
The element that is visible is:

```
<pre class="enlighter-raw">&lt;xsl:template name="MEMORIAL-WEEKEND"&gt;
  &lt;!-- 1. Is there a Special Event associated with this week? --&gt;
  &lt;!-- 2. Is it the Memorial? --&gt;
  &lt;!-- 3. Is the Memorial at the Weekend? --&gt;
  &lt;!-- If the answers are all Yes then we must display the Special Event information. --&gt;
  &lt;xsl:if test="@SpecialEvent=1 and SpecialEvent/Date/@Memorial=1 and SpecialEvent/Date/@MidweekEvent=0"&gt;
    &lt;table class="tableWeekend"&gt;
      &lt;tr&gt;
        &lt;!-- We need to use a colspan of 4 for consitency with the logic of the SpecialEvent template. --&gt;
        &lt;td class ="cellWEEKEND" colspan="4"&gt;
          &lt;div class="textWEEKEND" style="float:left"&gt;
            &lt;xsl:value-of select="//Labels/PTS_WeekendMeeting"/&gt;
          &lt;/div&gt;
        &lt;/td&gt;
      &lt;/tr&gt;
      &lt;xsl:apply-templates select="SpecialEvent"/&gt;
    &lt;/table&gt;
  &lt;/xsl:if&gt;
&lt;/xsl:template&gt;</pre>
```
Is there a setting I have not ticked, or is this a bug with something?

**Comment by AndiDittrich** [comment]
it's your theme ....

**Comment by ajtruckle** [comment]
How do I fix this then? As you know, I was not having this issue with the previous EnlighterJS.

**Comment by AndiDittrich** [comment]
but you've had a lot of other issue ...

normally this behaviour should never appear...there must be some weak selectors used by bbPress or the theme. 

maybe i should remove the bbPress support from the plugin since it causes such issues :(

**Comment by ajtruckle** [comment]
No! You can't remove bbPress!! Please! I love this plugin and it is the only one that works with bbPress. This is the only issue I have encountered with the beta.

**Comment by AndiDittrich** [comment]
but this issue is very serious... can you post the url to this testpost ?

**Comment by ajtruckle** [comment]
I have just compared the two topics in my live site and the staging site.

The only difference is that on the live site it has `display: none;` and on your beta it does not.

Old: `<pre style="display: none;">`
Beta: `<pre class="enlighter-raw">`

As soon as I manually change it:

`<pre class="enlighter-raw" style="display: none;">`

Problem solved.

**Comment by ajtruckle** [comment]
I don't want to post a url to a test post because I don't like exposing the staging site url. I am happy to create a public forum again with this test code if required. But I personally think we are just lacking this `display: none;`. Please advise. Thanks.

**Comment by AndiDittrich** [comment]
that's not solved ;) something is overriding the `enlighter-raw` styles which already includes `display: none`

**Comment by ajtruckle** [comment]
It is the bbPress styling, here:

![style-pack](https://user-images.githubusercontent.com/7985331/74880209-a21e0c00-5362-11ea-96c0-80ae31fb56da.png)

If you just add `!important` to your class then it takes precedence according to my testing here.

**Comment by ajtruckle** [comment]
![result](https://user-images.githubusercontent.com/7985331/74880383-fe812b80-5362-11ea-952b-012e3120da62.png)

See?

**Comment by AndiDittrich** [comment]
i see but `!important` attribute should never be used by libraries such way... a better solution might to replace the `pre` tag with a div

**Comment by ajtruckle** [comment]
> i see but `!important` attribute should never be used by libraries such way... a better solution might to replace the `pre` tag with a div

Ok, only you can decide that I guess!

> the issue is still caused by the bbPress `id` selector ..

Ok, sorry about that. From what I can tell this is the only issue. I tried editing a post and editing the code settings to highlight lines and it worked.

Once you are happy to confirm a way forward (as I know it is late there!) I will be happy to try it again, first on the staging and then on my live site.

**Comment by AndiDittrich** [comment]
thanks for the hint regarding bbPress

**Comment by ajtruckle** [comment]
I realise too that we can't use `!important` because when you want to toggle the code ... :)

**Comment by ajtruckle** [comment]
The only other thing I have noticed (and this might be because it is beta) in the old version when you hovered over your toolbar buttons - over the code view) it showed tooltips. In the beta it does not (in bbPress anyway). Other than that observation, looks great.

**Comment by AndiDittrich** [comment]
tooltipps are not implemented yet. the old version uses generic `title` attributes which was not suitable for a modern react/jsx based app.

**Comment by ajtruckle** [comment]
> tooltipps are not implemented yet. the old version uses generic `title` attributes which was not suitable for a modern react/jsx based app.

Then I think for the most part this was a very successful test exercise with v4 beta in bbPress. Just the one issue. I will delete the staging now until I here from you and I will test. Night!

**Comment by ajtruckle** [comment]
The alternative is to do it like your older version and use inline styles instead of a class. 

Does it need a class? It is raw code and thus as plain as possible. Or, maybe just use inline for bbPress mode. 

Just ideas. I am sure you thought of them already along with your other suggestion of div. 

Heck, my alarm just gone off. Time to get up. Early start at work.

**Comment by AndiDittrich** [comment]
the EnlighterJS library is a monolithic component and doesn't have any "bbPress" mode or similar - it has to work in a generic way.

**Comment by ajtruckle** [comment]
Understood.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
> the EnlighterJS library is a monolithic component and doesn't have any "bbPress" mode or similar - it has to work in a generic way.

So hopefully it will be ok with a `div` Like you said. If that also didn’t work I would have to go over to the BBPress forum for advice. 

I let us hope it will just be ok. #excited.

**Comment by ajtruckle** [comment]
More positive news. With my "live" site and the current EnlighterJS my topics mess up when I choose to not show line numbers (theme style issue).

But, the same does not happen with the new version. They display and render fine! :) So that is good. Is it hard to try changing the pre to a div?

**Comment by AndiDittrich** [comment]
great! it's already changed in the v3.2 branch

**Comment by ajtruckle** [comment]
You mean here?

https://github.com/EnlighterJS/Plugin.WordPress/tree/v3.2

Need to make sure I download the right files.

**Comment by ajtruckle** [comment]
> great! it's already changed in the v3.2 branch

Does that mean there is a branch I can download? I can't see any recent commits.

**Comment by AndiDittrich** [comment]
no i'm talking about EnlighterJS not Enlighter Wordpress Plugin

**Comment by ajtruckle** [comment]
Oh, ok. So you need to update it into your system first. I getcha.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
Is this not that then?
![14F9C496-B293-4FEF-B7F6-9176C59D1F8E](https://user-images.githubusercontent.com/7985331/75007012-b00b8400-546b-11ea-8adb-cfcbefa01103.jpeg)

**Comment by AndiDittrich** [comment]
you're not familiar with git ?

the development is done locally, when a stable stage is reached it will be pushed to the origin repository. v3.2 is the current development branch projected as next release - there is no preview version available

**Comment by ajtruckle** [comment]
I getcha. I use TortoiseGit with BitBucket. Understood.

**Comment by AndiDittrich** [comment]
v4.1 is out including EnlighterJS v3.2.0  - this should address to bbPress issue

**Comment by ajtruckle** [comment]
Yep, the tips are showing. :)
