### ISSUE TITLE
Can you modify the element label of the button?

### ISSUE THREAD

**Issue by hiikii** [EnlighterJS/Plugin.WordPress#225]
In my theme, I have used the background-image rule in the content. Due to the element label, it will override the button background-image set in the Enlighter css. So can you consider modifying the element label? For example:
```
.EnlighterJSToolbar .EnlighterJSWindowButton {
	background-image: url(data:image/gif;base64,R0lGODlhLgAuAKIAADtJcYuWq6Wxw/L7/9Xz/+z6/////wAAACwAAAAALgAuAAAD02i63P4wykmrvTjrzbv/YCiOZCacaKquace+sOAKRG3feH7Oee/vnJNveANuhLWAcslsOpkYJOFJrQaitGSAyFVibUou0XuRhgmFtHrNXpMt5i26TWe/K/FaHQCoF+4UeXNtfH6AE4J7fXWHEol0hYxXZVlTcoqGk3CVZ5hsA6CNEY98paanoAOiEKSnrnypqw+PhIt0sg60bJG3mnicl5C2bbgNumu8xL6BKZ3CmVgozrXQHNN+vR3X2HbLGNvcasURVuVQ1ubmJevs7e7v8PHy7QkAOw==);
}
```

**Comment by AndiDittrich** [comment]
you should consider to change your selectors which are setting the background of the theme.

currently Enlighter v4-beta1 is available which uses another markup (EnlighterJS v3) - maybe this works for you without any issues
