### ISSUE TITLE
Plugin links are hitting 404's

### ISSUE THREAD

**Issue by technoogies** [EnlighterJS/Plugin.WordPress#227]
Example: 
[https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs](https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs)

**Comment by AndiDittrich** [comment]
see #215 #210

the documentation has moved into it's own [repository](https://github.com/EnlighterJS/documentation)

you can still view the legacy Enlighter v3 docs by selecting the [v3 branch](https://github.com/EnlighterJS/Plugin.WordPress/tree/v3)
