### ISSUE TITLE
Code on Mobile devices gets wrapped. How to set the code unwrap

### ISSUE THREAD

**Issue by windson** [EnlighterJS/Plugin.WordPress#229]
Code on Mobile devices gets wrapped and loses readability.
How to set the code unwrap on any screen width?

**Comment by AndiDittrich** [comment]
your issue seems not to be related to the Gutenberg plugin -> moved

---

you can add some custom css rules to modify the wrapping :

EnlighterJS v2: https://github.com/EnlighterJS/Plugin.WordPress/issues/31
EnlighterJS v3: use the build-in option on the settings page
