### ISSUE TITLE
Author link

### ISSUE THREAD

**Issue by rockingaryan** [EnlighterJS/Plugin.WordPress#230]
Hi,

Thank you for this amazing Plugin. I am using it from the beginning, when listed on WordPress. There is no plugin that offers this this much features.

Today., I installed it on test site and noticed that author page link add the domain.

/wp-admin/admin.php?page=Enlighter-About

https://example.com/andidittrich.de

I have a question, the v4 not using mootools? I am testing it and it showing only two JS files, it was 4 in older version.

Thanks.

**Comment by AndiDittrich** [comment]
Hi @rockingaryan 

thanks for that hint. it's a typo - a single slash `/` was used for the protocol instead of a double one.

EnlighterJS v3 is a standlone library without any external framework. It just requires a **single** javascript file - the config scripts are all inlined into the page

**Comment by rockingaryan** [comment]
wow,

Amazing. I just working on my personal site to share web dev codes, HTML, CSS and PHP and JS mainly.

I would be happy to test it.

**Comment by AndiDittrich** [comment]
it's public available in [releases](https://github.com/EnlighterJS/Plugin.WordPress/releases/tag/v4.0.0-BETA1)

**Comment by rockingaryan** [comment]
1. Not showing Theme customizer, no tab seems to work.
wp-admin/admin.php?page=enlighter-customizer
![image](https://user-images.githubusercontent.com/34836534/77535218-3fb7ae80-6ec0-11ea-8ed2-69d5fd609857.png)

2. Toolbar is fixed and moves when code is scrolled.
![image](https://user-images.githubusercontent.com/34836534/77535488-afc63480-6ec0-11ea-9374-8d39a73c39c5.png)

3. Beta Options missing?
wp-admin/admin.php?page=enlighter-options
![image](https://user-images.githubusercontent.com/34836534/77535666-fc117480-6ec0-11ea-85a3-dd90c3413820.png)

I have checked all the options, this is all the errors i found. Monokai and Dracula theme is beautiful.

Options are now more easier to navigate and setup. Great work. Waiting for the next release. I would also love to donate. Please create a Patreon or donorbox.org

**Comment by AndiDittrich** [comment]
please read the release notes... https://github.com/EnlighterJS/Plugin.WordPress/releases/tag/v4.0.0-BETA1

currently there are not beta options available in the plugin

**Comment by rockingaryan** [comment]
Ok Thanks for your time. I mark this as solved.

**Comment by AndiDittrich** [comment]
v4.0/v4.1 is out including the new Theme Customizer -have fun!
