### ISSUE TITLE
Shortcut alt+shift+x doesn't work

### ISSUE THREAD

**Issue by akoshman** [EnlighterJS/Plugin.WordPress#233]
Hi,
I use latest version of Enlighter and try to convert selected text into formatted text.
I try to format text by using **ctrl+shift+x** and **alt+shift+x** but neither of them work.
The option `Enlighter -> VisualEditor -> Tweaks -> Enable Keyboard Shortcut` is enabled.
How can I fix this?
Thanks in advance.

**Comment by AndiDittrich** [comment]
which editor do you use ?

**Comment by akoshman** [comment]
Standard gutenberg editor in WP

**Comment by AndiDittrich** [comment]
the settings you've mentioned above are related to the Visual Editor (TinyMCE) and not to the Gutenberg Editor.

shortcuts are currently not supported in this editor mode

**Comment by akoshman** [comment]
I remember it worked a year ago for sure. Is there any way to make it work again? Any hacks, etc?

**Comment by AndiDittrich** [comment]
It has never been implemented to the Gutenberg plugin due to the non-existing shortcut api - only TinyMCE/Classic Editor support shortcuts (this has been change in WordPress 5.4)
