### ISSUE TITLE
Icons - one line

### ISSUE THREAD

**Issue by rbzg** [EnlighterJS/Plugin.WordPress#236]
When we have the code on one line, you can't see the whole icons toolbar.

Enlighter 4.0.

![bug](https://user-images.githubusercontent.com/37891616/79384011-76846000-7f66-11ea-8a67-8a20c5b1f4dd.jpg)

**Comment by AndiDittrich** [comment]
EnlighterJS (v2 + v3) are not designed to display a single line of code as "block code". especially there is no simple solution available which didn't affect the "regular" blocks.

the following workarounds are available

1. use inline highlighting mode of the classic editor
2. disable the toolbar
3. add some `dummy lines` to have at least `3` lines of code

if you have a suggestion how this issue can be address please feel free to post them
