### ISSUE TITLE
Using the Raw button

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#237]
Example:
![FloatingToolbar](https://user-images.githubusercontent.com/7985331/79387107-03c5b580-7f63-11ea-855e-9375c2d8771e.png)
If I click the Raw button the code block vanishes. Is this because I added additional CSS code to my website (for bbPress):

```
.enlighter-default .enlighter-raw {
	display:none !important;
}
```
? Or is this a bug?

For now I am hiding that button since they can click Copy or view in Popup window.

**Comment by AndiDittrich** [comment]
it is caused by your custom css...your rules will never show the raw code (hide it forever)

**Comment by ajtruckle** [comment]
OK, I will endeavour to investigate this further.
