### ISSUE TITLE
Advanced settings & Theme-Customizer

### ISSUE THREAD

**Issue by Suplanus** [EnlighterJS/Plugin.WordPress#241]
I upgraded to V4.0.
Where I can find advanced settings & Theme-Customizer?

![image](https://user-images.githubusercontent.com/2002916/79447311-f8fd3600-7fdf-11ea-82fe-4b1e7abf6554.png)

**Comment by AndiDittrich** [comment]
in the menu:
![image](https://user-images.githubusercontent.com/1474107/79447506-411c5880-7fe0-11ea-8e48-e869b7573fb4.png)

**Comment by Suplanus** [comment]
🤦
