### ISSUE TITLE
EnlighterJS attribution/logo

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#243]
> Please keep the EnlighterJS website link visible to give other users the ability to get in touch with EnlighterJS and the Enlighter WordPress plugin.

If I switched off showing the button would it be ok to add an entry to my [links](https://www.publictalksoftware.co.uk/other-links/) page?

Or would you prefer I leave your button activated?

**Comment by AndiDittrich** [comment]
do whatever you want ;)

**Comment by ajtruckle** [comment]
Ok! Do you have to have a suitable logo so I can keep the same style as my other links on like page?

**Comment by AndiDittrich** [comment]
can you provide an example ? but generally it is not needed to add links to your page for attribution!

**Comment by ajtruckle** [comment]
> can you provide an example ? but generally it is not needed to add links to your page for attribution!

Sure, I provided the link in the original message:

> If I switched off showing the button would it be ok to add an entry to my [links](https://www.publictalksoftware.co.uk/other-links/) page?

If you look there you will see how I like to present the links. The only reason I was thinking of doing this for you is because:

1. I would prefer to switch off the EnlighterJS link button.
2. I think you have worked VERY HARD so should be acknowledged on my other links page as an alternative. You can even provide the wording if you like.

**Comment by AndiDittrich** [comment]
sry i didn't saw that it was linked.

i can add the new WordPress icon (2 brackets with a slash) later to the docs (svg/png) - it's designated as new logo

**Comment by ajtruckle** [comment]
> i can add the new WordPress icon (2 brackets with a slash) later to the docs (svg/png) - it's designated as new logo

Did you upload one yesterday?

**Comment by AndiDittrich** [comment]
https://github.com/EnlighterJS/Plugin.WordPress/tree/master/resources/admin

please use the badges of the plugin - i have to recreate the logo

**Comment by ajtruckle** [comment]
No worries. I will wait for the logon. When you are ready. No rush!
