### ISSUE TITLE
v4.0 -- SQL highlighter issues

### ISSUE THREAD

**Issue by petr-hybler** [EnlighterJS/Plugin.WordPress#244]
hello the single line comments are not working properly ... when there is a single quote it treats it as a string even tho it's just a comment

example:
-- some data and ' this is treated as a string ....

+ some words are weirdly highligheted randomly (data types, function names, ..)

**Comment by AndiDittrich** [comment]
Hi @petr-hybler 

thanks for your report, i've moved your issue yesterday to the EnlighterJS library repository - it has been fixed asap in `v4.1.0` (EnlighterJS `v3.2.0`).

if it doesn't work in your case please provide a full code snipped to reproduce the error

**Example**
![image](https://user-images.githubusercontent.com/1474107/79546701-25be5580-8093-11ea-8181-97b5a7e1edd8.png)

**Comment by petr-hybler** [comment]
the single line comment with quotes issue is fixed .. thx .. but the syntax is still weirdly highlighted :-/

check out the examples
![Screenshot from 2020-04-17 23-00-58](https://user-images.githubusercontent.com/17429498/79583162-550aac00-80ff-11ea-9f26-71da0e8f5bab.png)
![Screenshot from 2020-04-17 23-02-36](https://user-images.githubusercontent.com/17429498/79583172-576d0600-80ff-11ea-853b-b4f4bcc933b3.png)
![Screenshot from 2020-04-17 23-02-51](https://user-images.githubusercontent.com/17429498/79583177-589e3300-80ff-11ea-92d6-b93cdfa2ad5d.png)
![Screenshot from 2020-04-17 23-03-15](https://user-images.githubusercontent.com/17429498/79583178-59cf6000-80ff-11ea-9881-3f1545cfc989.png)

**Comment by AndiDittrich** [comment]
hmm.. it looks like expected...

figure 1: "desc" is a keyword, therefore the other highlighting appears
figure 2/3: keywords and "function calls" are mixed...thats not an optimal solution

the general problem with "sql" is that it has normally be split into multiple dialects to cover all use cases (i'm primarily working/testing with mariadb/mysql syntax).

**Comment by AndiDittrich** [comment]
the current languages rules can be found here: https://github.com/EnlighterJS/EnlighterJS/blob/master/src/lang/sql.js

**Comment by petr-hybler** [comment]
figure 1: desc is ok .. but how about the NOT NULL ? or highlighted name of the table?  same like VARCHAR2 in the next figures ... it's not bold and sometimes highlighted :(

**Comment by AndiDittrich** [comment]
there rule `_language_common_rules.fCalls` is actually used to cover something like `TYPE(..` - maybe we should remove them

**Comment by AndiDittrich** [comment]
btw. the old language support file: https://github.com/EnlighterJS/EnlighterJS/blob/v2-legacy/Source/Language/Sql.js

**Comment by AndiDittrich** [comment]
without function call regex:
![image](https://user-images.githubusercontent.com/1474107/79587293-9fc1ff00-80d2-11ea-8f0e-b3cffa15f33e.png)

**Comment by petr-hybler** [comment]
that looks way better imo :) thx ...

btw is there still the option to set a default language as it was previously? or not anymore?

**Comment by AndiDittrich** [comment]
it has been added as "fallback language" option in v4.1 (Enlighter -> Options -> Advanced -> EnlighterJS). but this setting is normally not needed because the shortcodes/markdown/gutenberg/tinymce are setting the language attribute explicitly - whats your intention to use it ?

in the previous versions there were a lot of misunderstandings by the users who didn't know what this setting really does.

**Comment by petr-hybler** [comment]
all my codes are SQL only :) so it would be nice to have this language "by default" and not to pick it everytime manually (am posting a lot of articles) - that's kinda bother ... not a big deal tho

**Comment by AndiDittrich** [comment]
that's the issue ;) the "default" setting doesn't set any language select boxes even in the legacy versions

**Comment by AndiDittrich** [comment]
the changes have been applied to EnlighterJS `v3.2.0`
