### ISSUE TITLE
Code element misalignment

### ISSUE THREAD

**Issue by yohgaki** [EnlighterJS/Plugin.WordPress#249]
I'm using the "Twenty Twenty" theme which is current WP default.

Enlighter element is misaligned to left edge of screen.  Removing "enlighter-default" from div fixes misalignment, but break the code element format. 

Disabling ".enligher-default" class "margin" setting or set "margin" to auto via browser developer tool fixes this misalignment on Linux Chrome.

It seems code element is misaligned because "Twenty Twenty"'s parent div container width is screen wide.

**Comment by AndiDittrich** [comment]
please read the docs: https://github.com/EnlighterJS/documentation/blob/master/wordpress/WPThemeCompatibility.md

**Comment by yohgaki** [comment]
Missed document. Thank you!
