### ISSUE TITLE
Distorted quoted replies when using EnlighterJS with Asgaros forum and TinyMCE Advanced.

### ISSUE THREAD

**Issue by DaveVoorhis** [EnlighterJS/Plugin.WordPress#250]
Hi,

I'm using EnlighterJS 4.1 with Asgaros forum 1.15.4 and TinyMCE Advanced 5.4.0. Forum posts using Enlighter to embed source code work fine when displayed directly but are distorted as replies.

Here's an example that one of my users posted:
![CodeQuotingProblem](https://user-images.githubusercontent.com/747612/79993686-ed60b200-84ac-11ea-8feb-916dcb91ebe3.png)

Here's what I see when I try to create a quoted reply to the first post above. Note the "black bar" text repeated above the Enlighter box:
![CodeQuotingProblem2](https://user-images.githubusercontent.com/747612/79993779-09645380-84ad-11ea-9404-dd10db598df2.png)

Thanks!

**Comment by AndiDittrich** [comment]
please ask the authors of " Asgaros forum" for support - the issue seems to be related within the quoting function.

i assume that the EnlighterJS related css classes/data attributes got striped off

**Comment by DaveVoorhis** [comment]
Thanks, will do.
