### ISSUE TITLE
Resource Has to be Manually Loaded in Footer

### ISSUE THREAD

**Issue by jrg94** [EnlighterJS/Plugin.WordPress#252]
Love the plugin! I've been using it for a couple years now. I just switched my theme, and I'm running into an issue where the JS resource isn't loading in:

```
(index):1222 Error: EnlighterJS resources not loaded yet!
(anonymous) @ (index):1222
(anonymous) @ (index):1222
```

I have since added the call to the local script in the footer of my theme. Obviously, this isn't sustainable unless I make a child theme. Would love to get this sorted out if possible!

Also, double loading the script does slow my site down a hair:

![GTMetrix Site Performance](https://user-images.githubusercontent.com/11050412/80294518-9e7a7d00-8737-11ea-8b1e-f0a1ef749850.png)

I have since replaced the URL in the footer, so they're consistent:

```html
<script type="text/javascript" src="/wp-content/plugins/enlighter/resources/enlighterjs/enlighterjs.min.js?ver=4.1"></script>
```

Here's my site: https://therenegadecoder.com

**Comment by AndiDittrich** [comment]
please disable your "optimization plugin" which adds the `async defer` attributes .... (please read the mdn docs about this attributes and what they are doing )

**Comment by jrg94** [comment]
Hmm, I'm not running any optimization plugins as far as I know (besides ShortPixel):

![List of Plugins](https://user-images.githubusercontent.com/11050412/80313643-2903c080-87ba-11ea-895f-fe1e353ddbbb.png)

I'm wondering if my new theme does this natively.

**Comment by AndiDittrich** [comment]
disable one-by-one to find it

**Comment by jrg94** [comment]
Yup, it's the theme itself. I had my suspicions since I've removed significantly more plugins than I've added after switching the theme. Any tips for how to deal with this beyond what I already did?

**Comment by AndiDittrich** [comment]
normally, pre-build/public availabke themes are offering options to control these settings - if not you should ask the theme authors for assistance

**Comment by jrg94** [comment]
Sounds great! Thanks for your help.
