### ISSUE TITLE
Add support for Dart language

### ISSUE THREAD

**Issue by anuragbhd** [EnlighterJS/Plugin.WordPress#253]
I had been using [WP Syntax](https://wordpress.org/plugins/wp-syntax/) plugin for like ever. I installed Enlighter on my WordPress blog today, and instantly loved it. Not only my code now looks more beautiful on posts, support for so many languages is really cool.

Sadly, I could not find Dart in the dropdown list of language. Please consider supporting it now that Flutter development is exploding :)

**Comment by AndiDittrich** [comment]
duplicate https://github.com/EnlighterJS/EnlighterJS/issues/52

the generic highlighting should work fine!

**Comment by anuragbhd** [comment]
Whoops, somehow #52 didn't come up in my search before raising this issue.

Thanks for pointing that out, @AndiDittrich.
