### ISSUE TITLE
EnlighterJs 4.1 - Theme Customizer - Not picking the set font size

### ISSUE THREAD

**Issue by javadevcentral** [EnlighterJS/Plugin.WordPress#254]
In EnlighterJs 4.1, the `font-size` in Fonts -> Global setting does not take effect. 

Setting a custom font size adds the CSS `.enlighter-t-wpcustom` with the set font-size. But, the font-size gets overridden.

On analysing the *Computed CSS* on Chrome, the `.enlighter span` is overriding the custom font-size (`.enlighter-t-wpcustom`)

P.S: I was using enlighter as the base theme.

---

I guess this problem is not with all themes. I noticed that for some themes (like dracula), the following style is generated as (as part of `enlighterjs.min.css`)

    .enlighter-t-wpcustom .enlighter span {
	    font-size: <my_custom_font_size>
    } 

I guess it is because of the additional selector (`.enlighter span`), it is working for other themes.

**Comment by AndiDittrich** [comment]
hi @javadevcentral ,

it was the expected behaviour. the "global" setting does only set the defaults of the theme but they were mostly overridden by the themes css (EnlighterJS `<=3.2.0`)

EnlighterJS `v3.3.0` has changed this by using relative `em` based font sizes within the themes. Additionally the ThemeCustomizer `v2.2.0` got a new setting to change the default token styles.

**Comment by javadevcentral** [comment]
@AndiDittrich 
Thanks for a swift response. 

I'm confused a bit with the versions. The current [enlighter plugin](https://wordpress.org/plugins/enlighter/#developers) is 4.1.0. It uses 
* EnlighterJS v3.2.0
* EnlighterJS Theme-Customizer v2.1.0

Would a new plugin version be released with updated EnlighterJS and ThemeCustomizer which would enable to change the font-sizes?

**Comment by AndiDittrich** [comment]
see the master branch...

**Comment by javadevcentral** [comment]
I see 4.2.0 in the changelog :)
https://github.com/EnlighterJS/Plugin.WordPress/blob/master/CHANGES.md

Is it not yet deployed/released?

**Comment by AndiDittrich** [comment]
no, the stable release is 4.1

**Comment by javadevcentral** [comment]
This limitation (setting font-size) can be overcome once 4.2 is released and marked as stable, isn't it?
So, I would have to wait and upgrade to 4.2? (If yes, any tentative date?)

**Comment by AndiDittrich** [comment]
there is no release date set.

i'll waiting until i get more feedback and a higher spreading of the v4 release

**Comment by guitorioadar** [comment]
Hello,

We now have this huge editing section but I could not increase the font size...

<img width="1399" alt="Screenshot 2020-07-28 at 12 54 26 AM" src="https://user-images.githubusercontent.com/13439371/88580172-11fc9500-d06d-11ea-89d8-c6ec2a6a97c6.png">

<img width="699" alt="Screenshot 2020-07-28 at 12 56 22 AM" src="https://user-images.githubusercontent.com/13439371/88580261-2f316380-d06d-11ea-98e4-c9df7a15539a.png">

**Comment by AndiDittrich** [comment]
please open a new issue and post your config + link to an example page (set the font size to 2em for testing)

**Comment by guitorioadar** [comment]
**PLEASE**
**READ THE DOCUMENTATION PROPERLY**

Everything is explained there perfectly....

i am so sorry... i missed some documentation.... i am deleting my comment... i didn't read the documentation properly...

**Comment by AndiDittrich** [comment]
no problem, a common issue
