### ISSUE TITLE
Wordpress plugin CSS not centered

### ISSUE THREAD

**Issue by houserockr** [EnlighterJS/Plugin.WordPress#255]
When using EJS in a wordpress 5.4 with the latest twenty-twenty theme, the code blocks will all be left aligned, where the twenty-twenty theme is centered most of the time.

problem is the `enlighter-default` class, which uses `margin: 0 0 20px 0;` and thus overriding the theme's `margin-left: auto; margin-right: auro` situation.

**Comment by AndiDittrich** [comment]
please read the docs: https://github.com/EnlighterJS/documentation/blob/master/wordpress/WPThemeCompatibility.md
