### ISSUE TITLE
CSS resources not loaded - http404

### ISSUE THREAD

**Issue by yarotzckaya** [EnlighterJS/Plugin.WordPress#256]
I updated this plugin and after that all the code I've inserted in my post displays as a plaintext. No differences between all plaintext in a post and code, which is sad. (Before last update all was perfect). Hope you will fix it)

**Comment by yarotzckaya** [comment]
Yes, that shows 404 error 
<img width="542" alt="Screenshot 2020-04-28 at 11 41 22" src="https://user-images.githubusercontent.com/22495612/80472567-313c3700-8945-11ea-9ca7-d0195580e921.png"> 

for example, here is where I used the plugin - http://yarotzckaya.com/2020/04/28/%d0%bf%d0%b8%d1%80%d0%b0%d0%bc%d0%b8%d0%b4%d0%b0/

**Comment by AndiDittrich** [comment]
the css is missing - the syntax highlighter itself (javascript) works as expected.

are you getting any errors on the Enlighter settings page ? e.g. cache permissions ?
did you click "save" on the settings page after upgrading ?

**Comment by yarotzckaya** [comment]
<img width="1197" alt="Screenshot 2020-04-28 at 11 50 19" src="https://user-images.githubusercontent.com/22495612/80473447-714fe980-8946-11ea-8739-fab89326b995.png">
here it is

**Comment by AndiDittrich** [comment]
thats the issue. please fix it
