### ISSUE TITLE
enlighterjs.min.css loaded on all page even if not used

### ISSUE THREAD

**Issue by cedricwalter** [EnlighterJS/Plugin.WordPress#259]
Hi,

while profiling I discovered that enlighterjs.min.css is loaded on home, and everywhere even if not used....

Your scripts are useful for what your plugin or theme does in a specific place, but including them into pages where they are not needed will make this same pages unnecessarily heavier.

Wordpress has a solution for that, can you please implement it?

**Comment by cedricwalter** [comment]
thanks

**Comment by AndiDittrich** [comment]
but please keep in mind that the DRI can only optimize the (much larger) javascript file loading - css files cannot be limited by the DRI (see the old issue here for technical details).

WordPress has no build-in solution to achieve this.

if you want to optimize the css size it is recommended to use a single EnlighterJS theme (from the official repository) and add it to your theme styles - then you can disable the "full" theme pack
