### ISSUE TITLE
enlighter does not work with quizmaker plugin 

### ISSUE THREAD

**Issue by petr-hybler** [EnlighterJS/Plugin.WordPress#260]
Hello Andi ... after the updates to 4.2 the plugin works nearly flawlessly ... in posts the highlighting is fantastic .. however, I have just noticed a weird behavior .... when using a quizMaker plugin (premium plugin) it does not highlight ... check out the samples

here is a screenshot of a perfectly working code
![Screenshot from 2020-05-03 20-16-38](https://user-images.githubusercontent.com/17429498/80913961-06a21200-8d7b-11ea-9b72-ea45e908f041.png)

and here is another one of not working code (inside QuizMaker)
![Screenshot from 2020-05-03 20-17-44](https://user-images.githubusercontent.com/17429498/80913987-2fc2a280-8d7b-11ea-9ca8-bcd3b1948f1d.png)

I noticed there is a difference where is the former screenshot has some DIVs generated 
![Screenshot from 2020-05-03 20-18-21](https://user-images.githubusercontent.com/17429498/80914007-49fc8080-8d7b-11ea-86c1-7bdedec30d72.png)

whereas the latter one does not .. would you happen to know why? I check the console and there is no issue what so ever :(

**Comment by AndiDittrich** [comment]
Hi Petr,

are the EnlighterJS resources loaded on the pages which are generated with `quizMaker` ?
is the content of the `quizMaker` plugin dynamically loaded via ajax/xhr ? 

generally i cannot provide any kind of (free) support for paid plugins because i'm unable to use these kind of plugins within the dev environment.

**Comment by petr-hybler** [comment]
yup seems like it's loaded :( how can I check if it's loaded via AJAX?

**Comment by AndiDittrich** [comment]
chrome developer tools -> network -> XHR

**Comment by petr-hybler** [comment]
oh crap ... yes it is .. is that a big problem?

**Comment by AndiDittrich** [comment]
try `Enlighter -> Extensions -> Dynamic Content`

if this doesn't work you have to talk with the plugin authors to implement such hook

**Comment by petr-hybler** [comment]
could it mess up the existing highlighting?

**Comment by AndiDittrich** [comment]
no it just adds an event listener

**Comment by petr-hybler** [comment]
doesn't work :( thx anyway
