### ISSUE TITLE
Do not capitalize "raw"

### ISSUE THREAD

**Issue by locness3** [EnlighterJS/Plugin.WordPress#261]
`raw` in `raw code` should not be capitalized, because it can then be confused with RAW images.

**Comment by AndiDittrich** [comment]
Hi @locness3 

you can alter the language list and change the label using the filter functions.
the capitalized letters are used to indicate that this is not a highlighting language.

generally i didn't think that users are confused because if they're in contact with the select boxes they already added a "codeblock"

**Comment by locness3** [comment]
Still, this doesn't look right to me. And it's not only in the backend part, it's also visible when hovering the "raw" button on code blocks, in the tooltip (though the button itself isn't capitalized)

**Comment by AndiDittrich** [comment]
do you have any better suggestions ?

**Comment by locness3** [comment]
Well, just don't capitalize raw at all (I don't think it needs to be capitalized to be distinguished from a programming language name)

**Comment by AndiDittrich** [comment]
language list: `raw code (not highlighted)`

**Comment by roy-bongers** [comment]
raw code is without any formatting right? What about "Plain text". Sublime / PHPstorm etc also use plain text to indicate code without any formatting.

**Comment by AndiDittrich** [comment]
thanks, that might be a good label for the language lists. Any idea regarding the raw code button ?

**Comment by roy-bongers** [comment]
For any other highlighted language plain text would work well but not when you've already selected plain text...

Toggle formatting?

**Comment by AndiDittrich** [comment]
changed to "Plain text" (EnlighterJS tooltip + Enlighter language list)
