### ISSUE TITLE
DRI not working with bbPress shortcode

### ISSUE THREAD

**Issue by rrrfer** [EnlighterJS/Plugin.WordPress#265]
I set flags in Extensions->bbpress:
![Снимок экрана от 2020-05-14 17-40-00](https://user-images.githubusercontent.com/21195729/81925027-230b3d80-960a-11ea-8eca-934a9dd72f9c.png)

The plugin works great on a blog:
![Снимок экрана от 2020-05-14 17-42-21](https://user-images.githubusercontent.com/21195729/81925171-5a79ea00-960a-11ea-9640-159413d3862d.png)

But does not highlight the code on the forum:
![Снимок экрана от 2020-05-14 17-43-42](https://user-images.githubusercontent.com/21195729/81925270-7bdad600-960a-11ea-9dbf-a3870dc3646b.png)

I use tags [cpp]code[/cpp].

**Comment by AndiDittrich** [comment]
please post your settings: `Enlighter -> About -> Debug`

**Comment by rrrfer** [comment]
`{
    "translation-enabled": true,
    "enlighterjs-init": "inline",
    "enlighterjs-assets-js": true,
    "enlighterjs-assets-themes": true,
    "enlighterjs-assets-themes-external": true,
    "enlighterjs-selector-block": "pre.EnlighterJSRAW",
    "enlighterjs-selector-inline": "code.EnlighterJSRAW",
    "enlighterjs-indent": 2,
    "enlighterjs-ampersandcleanup": true,
    "enlighterjs-linehover": true,
    "enlighterjs-rawcodedbclick": false,
    "enlighterjs-textoverflow": "break",
    "enlighterjs-linenumbers": true,
    "enlighterjs-theme": "beyond",
    "enlighterjs-retaincss": false,
    "enlighterjs-language": "cpp",
    "toolbar-visibility": "default",
    "toolbar-button-raw": false,
    "toolbar-button-copy": true,
    "toolbar-button-window": false,
    "toolbar-button-enlighterjs": false,
    "tinymce-backend": false,
    "tinymce-frontend": false,
    "tinymce-formats": false,
    "tinymce-autowidth": false,
    "tinymce-tabindentation": false,
    "tinymce-keyboardshortcuts": false,
    "tinymce-font": "sourcecodepro",
    "tinymce-fontsize": "0.7em",
    "tinymce-lineheight": "1.4em",
    "tinymce-color": "#000000",
    "tinymce-bgcolor": "#f9f9f9",
    "gutenberg-backend": false,
    "quicktag-backend": true,
    "quicktag-frontend": true,
    "quicktag-mode": "shortcode",
    "shortcode-mode": "modern",
    "shortcode-inline": true,
    "shortcode-type-generic": true,
    "shortcode-type-language": true,
    "shortcode-type-group": false,
    "shortcode-filter-content": true,
    "shortcode-filter-excerpt": true,
    "shortcode-filter-widget": true,
    "shortcode-filter-comment": false,
    "shortcode-filter-commentexcerpt": false,
    "gfm-enabled": false,
    "gfm-inline": true,
    "gfm-language": "raw",
    "gfm-filter-content": true,
    "gfm-filter-excerpt": true,
    "gfm-filter-widget": true,
    "gfm-filter-comment": true,
    "gfm-filter-commentexcerpt": true,
    "compat-enabled": false,
    "compat-crayon": false,
    "compat-codecolorer": false,
    "compat-type1": false,
    "compat-type2": false,
    "compat-filter-content": true,
    "compat-filter-excerpt": true,
    "compat-filter-widget": false,
    "compat-filter-comment": false,
    "compat-filter-commentexcerpt": false,
    "cache-custom": false,
    "cache-path": "",
    "cache-url": "",
    "dynamic-resource-invocation": true,
    "ext-infinite-scroll": false,
    "ext-ajaxcomplete": false,
    "bbpress-shortcode": true,
    "bbpress-markdown": true
}`

**Comment by AndiDittrich** [comment]
the config looks ok...

try to disable the "DRI" and in case you're using caching plugins disable them also

**Comment by rrrfer** [comment]
thanks, I turned off DRI and it worked.

**Comment by AndiDittrich** [comment]
the issue is caused by the DRI detection: the Enlighter shortcode handler (low level) doesn't implement its own `hasContent` check - i will address this in the next release.

thanks four your help/feedback!
