### ISSUE TITLE
When I have a single line of code, the toolbar buttons are almost completely hidden

### ISSUE THREAD

**Issue by RobertBernstein** [EnlighterJS/Plugin.WordPress#269]
I would like the "Toggle RAW code", "Copy to clipboard", etc., buttons to be more visible when I hover over a code block in my WordPress page.

![image](https://user-images.githubusercontent.com/845559/82689908-3da46e80-9c29-11ea-88bc-abf59d368c28.png)

Here you can just see the tops of the toolbar buttons.  How can I fix this?

Here's the page where you can see the issue: [https://www.tardistech.com/2020/05/22/installing-and-updating-the-azure-az-powershell-module-vs-azurerm/](https://www.tardistech.com/2020/05/22/installing-and-updating-the-azure-az-powershell-module-vs-azurerm/)

Thanks in advance!

Rob

**Comment by AndiDittrich** [comment]
use more than 1 line or set a min-height to the inner container-

EnlighterJS block mode is not designed for a single line of code

**Comment by RobertBernstein** [comment]
Thank you!  I added this CSS to my site and now it looks better:

```CSS
.enlighter-default {
    min-height: 35px;
}
```

Just out of curiosity, is block mode the same thing as Gutenberg Blocks?  What is the alternative to block mode, the MCE editor?

Thanks again.

Rob

**Comment by AndiDittrich** [comment]
EnlighterJs has block and inline modes. TinyMCE has full support for both types. The Gutenberg editor is currently limited to block mode.
