### ISSUE TITLE
Inline code not working

### ISSUE THREAD

**Issue by 1iquk** [EnlighterJS/Plugin.WordPress#271]
I read the docs and i cannot get standard or extended inline highlighting to work.
I made this post as an example:
https://imranqureshi.co.uk/enlighter-test/

I am trying to display powershell mainly and used the backticks.
Code highlighting works fine for me using Gutenberg block editing.

I need it to work in Tablepress as shown in Command column on this page:
https://imranqureshi.co.uk/commands/

Previously i was using code colourer using tags [] but i want to switch to Enlighter.

**Comment by AndiDittrich** [comment]
you can still use shortcodes in Enlighter.

regarding your issue: please post your plugin settings `Enlighter ->About -> Debug`

**Comment by 1iquk** [comment]
Plugin configuration

{
    "translation-enabled": true,
    "enlighterjs-init": "inline",
    "enlighterjs-assets-js": true,
    "enlighterjs-assets-themes": true,
    "enlighterjs-assets-themes-external": false,
    "enlighterjs-selector-block": "pre.EnlighterJSRAW",
    "enlighterjs-selector-inline": "code.EnlighterJSRAW",
    "enlighterjs-indent": 4,
    "enlighterjs-ampersandcleanup": true,
    "enlighterjs-linehover": true,
    "enlighterjs-rawcodedbclick": false,
    "enlighterjs-textoverflow": "break",
    "enlighterjs-linenumbers": true,
    "enlighterjs-theme": "wpcustom",
    "enlighterjs-retaincss": false,
    "enlighterjs-language": "generic",
    "toolbar-visibility": "default",
    "toolbar-button-raw": true,
    "toolbar-button-copy": true,
    "toolbar-button-window": true,
    "toolbar-button-enlighterjs": true,
    "tinymce-backend": true,
    "tinymce-frontend": false,
    "tinymce-formats": true,
    "tinymce-autowidth": false,
    "tinymce-tabindentation": false,
    "tinymce-keyboardshortcuts": false,
    "tinymce-font": "sourcecodepro",
    "tinymce-fontsize": "0.7em",
    "tinymce-lineheight": "1.4em",
    "tinymce-color": "#000000",
    "tinymce-bgcolor": "#f9f9f9",
    "gutenberg-backend": true,
    "quicktag-backend": false,
    "quicktag-frontend": false,
    "quicktag-mode": "html",
    "shortcode-mode": "disabled",
    "shortcode-inline": true,
    "shortcode-type-generic": true,
    "shortcode-type-language": true,
    "shortcode-type-group": false,
    "shortcode-filter-content": true,
    "shortcode-filter-excerpt": true,
    "shortcode-filter-widget": false,
    "shortcode-filter-comment": false,
    "shortcode-filter-commentexcerpt": false,
    "gfm-enabled": false,
    "gfm-inline": true,
    "gfm-language": "raw",
    "gfm-filter-content": true,
    "gfm-filter-excerpt": true,
    "gfm-filter-widget": false,
    "gfm-filter-comment": false,
    "gfm-filter-commentexcerpt": false,
    "compat-enabled": false,
    "compat-crayon": false,
    "compat-codecolorer": false,
    "compat-type1": false,
    "compat-type2": false,
    "compat-filter-content": true,
    "compat-filter-excerpt": true,
    "compat-filter-widget": false,
    "compat-filter-comment": false,
    "compat-filter-commentexcerpt": false,
    "cache-custom": false,
    "cache-path": "",
    "cache-url": "",
    "dynamic-resource-invocation": false,
    "ext-infinite-scroll": false,
    "ext-ajaxcomplete": false,
    "bbpress-shortcode": false,
    "bbpress-markdown": false
}

**Comment by AndiDittrich** [comment]
GFM is no enabled..

**Comment by 1iquk** [comment]
enabled GFM it works great now on the post but not in the table on /commands page.

**Comment by AndiDittrich** [comment]
do you use any kind of caching plugin ?

does your tablepress plugin supports `the_content` filter ? i didn't know this plugin nor how it's working - it doesnt't seems to be an Enlighter issue...

**Comment by 1iquk** [comment]
no caching plugin.

Yes! got it working.
I played around with some settings in Markdown and found i had to add HTML QuickTag backend integration on Text/RAW Tab. Then i could see the language buttons on the advanced editor in TablePress. I can now switch of the QuickTag backend integration and the HTML code still works. See attached pics.
You can see how it looks https://imranqureshi.co.uk/commands


Thanks for the support and excellent plugin :)

![Selection_616](https://user-images.githubusercontent.com/28661524/83074524-371f5800-a06a-11ea-93bd-f63173404034.png)
![Selection_617](https://user-images.githubusercontent.com/28661524/83074533-3c7ca280-a06a-11ea-883a-90cd35d1186e.png)
![Selection_618](https://user-images.githubusercontent.com/28661524/83074548-430b1a00-a06a-11ea-9d93-f331b6e1c245.png)
![Selection_619](https://user-images.githubusercontent.com/28661524/83074559-469ea100-a06a-11ea-9db7-38ac2d91746a.png)
