### ISSUE TITLE
MooTwo theme in v4.2 is broken

### ISSUE THREAD

**Issue by notastudio** [EnlighterJS/Plugin.WordPress#273]
System info:
```
Server
PHP Version: 7.3.13
PHP JSON Extension: available
Server Software: Linux
Components
Enlighter Plugin: 4.2 CE
EnlighterJS Version: 3.3.0
TinyMCE Extension: 5.0.1
Gutenberg Extension: 1.0.0
Theme Customizer: 2.2.0
WP-Skeleton Version: 0.23.0
Environment
Cache writeable: true
Shortcode Processor: Enlighter low-level
```
I have updated from v3 to v4.2 right now and noticed that all of my code blocks in articles are not highlighted, and the toolbar is also broken:
![Snipaste_2020-06-01_21-36-38](https://user-images.githubusercontent.com/18502810/83414721-8f7e9d00-a450-11ea-916f-179c97be24db.png)
If I switch to another theme, everything is ok. Only MooTwo has problems. No errors are reported in the browser console.

**Comment by AndiDittrich** [comment]
take a look into the theme list... the legacy "mootwo" theme has been removed. as replacement "mowtwo" has been added -  see https://github.com/EnlighterJS/EnlighterJS/tree/master/src/themes

**Comment by notastudio** [comment]
> take a look into the theme list... the legacy "mootwo" theme has been removed. as replacement "mowtwo" has been added - see https://github.com/EnlighterJS/EnlighterJS/tree/master/src/themes

This is weird... There's only "mootwo", no "mowtwo" in the drop-down list.
![image](https://user-images.githubusercontent.com/18502810/83483646-b501ba00-a4d5-11ea-8add-277f68fa5fe7.png)

**Comment by AndiDittrich** [comment]
thanks for that hint, it's a typo within the select list. `mowtwo` is the correct identifier

**Comment by AndiDittrich** [comment]
it's fixed in the master branch

**Comment by notastudio** [comment]
thanks!

**Comment by AndiDittrich** [comment]
as a workaround, you can alter the theme list by using the filters (see documentation) and add the correct theme identifier
