### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by enesoral** [EnlighterJS/Plugin.WordPress#274]
Is there any option for responsivity?

**Comment by AndiDittrich** [comment]
All EnlighterJS v3 themes as well as all Enlighter UI components are already full responsive - you didn't need to enable it

**Comment by enesoral** [comment]
But when i turn the mobile view long lines move to the new line. Can we do scroll like github raw?

**Comment by AndiDittrich** [comment]
just change the line-break settings on the appearance page

**Comment by enesoral** [comment]
I really appreciate your support. Have a nice dev :)
