### ISSUE TITLE
backslash(\) is not displaying in post

### ISSUE THREAD

**Issue by gelodefaultbrain** [EnlighterJS/Plugin.WordPress#275]
I am displaying a source code on a website I am trying to make

example:
 
```
//must be like this
 printf("Hello World\n");
```

but instead it displays like this

```
//it displays like this, so annoying please update your plugin
printf("Hello Worldn");
```

As you can see it removes the backslash ( \ )

why is that man, I am trying to display a source code and the backslash must be included. It is very important especially on a particular programming language. Thank you.

**Comment by AndiDittrich** [comment]
which editing method do you use ?

**Comment by gelodefaultbrain** [comment]
Wow that was quick. Can you help me out? I've tried everything. Wait let me screenshot so that It would be clear.

**Comment by AndiDittrich** [comment]
i cannot reproduce the issue:

**Classic Editor**
![image](https://user-images.githubusercontent.com/1474107/84137555-2947da80-aa4d-11ea-8ddb-d0a3b7a05dc0.png)

![image](https://user-images.githubusercontent.com/1474107/84137583-35cc3300-aa4d-11ea-897f-a32c038280c2.png)

**Gutenberg Editor**

![image](https://user-images.githubusercontent.com/1474107/84137724-5ac0a600-aa4d-11ea-9a83-9d4059115eb0.png)

**Comment by gelodefaultbrain** [comment]
Look at this , this is what I mean

![image](https://user-images.githubusercontent.com/55988471/84137917-fff47200-aa7f-11ea-8819-09ba753d8522.png)

vs


![image](https://user-images.githubusercontent.com/55988471/84138016-2d412000-aa80-11ea-9613-5278fd22c980.png)

**Comment by gelodefaultbrain** [comment]
> i cannot reproduce the issue:
> 
> **Classic Editor**
> ![image](https://user-images.githubusercontent.com/1474107/84137555-2947da80-aa4d-11ea-8ddb-d0a3b7a05dc0.png)
> 
> ![image](https://user-images.githubusercontent.com/1474107/84137583-35cc3300-aa4d-11ea-897f-a32c038280c2.png)
> 
> **Gutenberg Editor**
> ![image](https://user-images.githubusercontent.com/1474107/84137841-8d6a9e80-aa4d-11ea-846d-793ff80a118c.png)
> 
> ![image](https://user-images.githubusercontent.com/1474107/84137724-5ac0a600-aa4d-11ea-9a83-9d4059115eb0.png)

How did you do that? :( 

This is my settings by the way I use Atomic cause I like the theme

![image](https://user-images.githubusercontent.com/55988471/84138213-7ee9aa80-aa80-11ea-9eeb-6ccfc5c35d06.png)

**Comment by AndiDittrich** [comment]
i believe that you're experiencing this behaviour but currently i assume that it's on of your plugins or your theme which may strip that out...

**Comment by gelodefaultbrain** [comment]
I don't have any plugin besides elementor like pods, and also elementor syntax highligther but I am not using it :(

**Comment by AndiDittrich** [comment]
maybe it's elementor which strips it . try to create a post in Gutenberg or classic editor...

the issue doesn't seems to be related to Enlighter...

**Comment by gelodefaultbrain** [comment]
I tried to change the theme to classic still no luck :(

![image](https://user-images.githubusercontent.com/55988471/84138790-734ab380-aa81-11ea-82c6-660eeca31412.png)

**Comment by AndiDittrich** [comment]
not the Enlighter theme...your WordPress theme..

**Comment by gelodefaultbrain** [comment]
May I ask what is Gutenberg? Sorry I'm new to Wordpress, is it a plugin like for displaying source codes too?

**Comment by AndiDittrich** [comment]
Gutenberg is the new WordPress editor used as of WordPress 5.0

in case you're using Elementor Page Builder you should ask in their forums for support.

maybe you should start with WordPress without page builders..

**Comment by gelodefaultbrain** [comment]
Hello, omg are you the dev of this plugin? hahaha The plugin is great anyways still no luck :(

**Comment by AndiDittrich** [comment]
i'm not sure whats going wrong on your site - i assume some kind of environment error.

maybe you can try it in a "clean" environment to identify the issue (theme or plugin).

at the moment, i can only confirm that this issue cannot be reproduced within the testing environment and didn't occur on regular installations

**Comment by gelodefaultbrain** [comment]
Yep I'll try on other themes, I'll make an update here soon :) thank you :D
