### ISSUE TITLE
Most of settings not at all working for me

### ISSUE THREAD

**Issue by NomendraSinha** [EnlighterJS/Plugin.WordPress#276]
I have disabled toolbar but it still shows. I tried to use theme customizer but none of the settings taking effect.

**Comment by AndiDittrich** [comment]
please provide more details + link to your site showing the issue.

without such information i'm unable to help you.
---

most related issues are related to caching/optimization plugins which takes control of the EnlighterJS css files - you have to disable such plugins for Enlighter or clear the server cache each time you apply changes

**Comment by NomendraSinha** [comment]
Link: https://www.primearly.com/sample-post/
[plugin config.txt](https://github.com/EnlighterJS/Plugin.WordPress/files/4752246/plugin.config.txt)

**Comment by AndiDittrich** [comment]
i cannot see any issue on your site...

![image](https://user-images.githubusercontent.com/1474107/84149966-851c5e80-aa61-11ea-924d-0005d2f0e086.png)

**Comment by NomendraSinha** [comment]
Ok thanks I got it, it was caching issue
