### ISSUE TITLE
启用插件后影响编辑器原有<pre>标签

### ISSUE THREAD

**Issue by wbfz89** [EnlighterJS/Plugin.WordPress#277]
启用前
[https://i.loli.net/2020/06/11/diBasKSPy2bZIQ3.png](https://i.loli.net/2020/06/11/diBasKSPy2bZIQ3.png)

启用后
[https://i.loli.net/2020/06/11/lCnXfQOqz4FhkVj.png](https://i.loli.net/2020/06/11/lCnXfQOqz4FhkVj.png)

**Comment by wbfz89** [comment]
Affects editor's original `<pre>` tag when plugin is enabled.

Before I enable the plug-in
[https://i.loli.net/2020/06/11/diBasKSPy2bZIQ3.png](https://i.loli.net/2020/06/11/diBasKSPy2bZIQ3.png)

After I enable the plug-in
[https://i.loli.net/2020/06/11/lCnXfQOqz4FhkVj.png](https://i.loli.net/2020/06/11/lCnXfQOqz4FhkVj.png)

**Comment by AndiDittrich** [comment]
without additional informations/testcases i'm unable to help you.

i don't even know what your screenshots are showing...please provide more informations + example code
