### ISSUE TITLE
Plugin looks broken after taking update

### ISSUE THREAD

**Issue by infoextractpvtltd** [EnlighterJS/Plugin.WordPress#279]
Hi,
I was using plugin to put code but after taking update it is broken. please refer this page link where i have used code Enlighter and it is looking like standard wordpress:

This is the link 

https://vbaoverall.com/insert-hyperlink-in-excel-addin-c/

**Comment by AndiDittrich** [comment]
the Enlighter resources are loaded on your page (only the inline init code) . therefore it cannot work
i see that you're using autoptomizly - did you exclude Enlighter from it as mentioned in the faq ?

are you running any caching plugins ? in this case you have to clear the caches after applying plugin changes

**Comment by infoextractpvtltd** [comment]
Hi as per FAQ i have changed Cache directory permission level to 0777 also I am using autoptomizly plugin but don't know how to exclude it from?

Please help

**Comment by AndiDittrich** [comment]
disable Autoptimize and test if Enlighter is working

**Comment by infoextractpvtltd** [comment]
yes it works but I need Autoptimize any solution would be appreciated please

**Comment by AndiDittrich** [comment]
is it working as expected without Autoptimize ?

**Comment by AndiDittrich** [comment]
you will find the instructions on the FAQ: https://wordpress.org/plugins/autoptimize/#%0Ahow%20does%20%E2%80%9Cexclude%20from%20optimizing%E2%80%9D%20work%3F%0A

paths: https://github.com/EnlighterJS/documentation/blob/master/wordpress/FAQ.md#javascript-error-enlighterjs-resources-not-loaded-yet

**Comment by infoextractpvtltd** [comment]
Great!!!! it works thanks
