### ISSUE TITLE
Support for Hootkit Custom Code Plugin

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#280]
Hi

I would be grateful if you can consider this please.

I am using the theme Unos Business Premium (a child theme supplied by the developer). The parent theme is Unos Premium.

They supply a simple plugin called Hootkit Custom Code which is a placeholder for our own php and style sheets.

They showed me how easy it was for me to have my custom enlighter css file in a folder under their plugin and theone line of code to import it.

That in itself works and the code renders correctly on the website. But the backend area does not know about this css file location. It has to be in (as documented) a enlighter sub-folder of the child theme.

So can you please consider adding support to look in the hootkit plugin folder (if it is installed)? The benefit for me is I will then not lose settings when upgrading their child theme to a new version.

I hope this makes sense.

Thank you.

**Comment by ajtruckle** [comment]
> on the other hand, you can add any themes as css sources to your page and alter the `enlighter_theme` filter to include your special theme

Could you please explain a little more about this for me when you have a moment? Thank you.

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/documentation/blob/master/wordpress/FilterHooks.md#filterenlighter_themes

you can also add custom themes to the list - but your "solution" posted above may cause dependency issues and the styles might be broken

**Comment by ajtruckle** [comment]
OK, I think I get you. If you recall we already have some code that is filtering the lists. But, it was adding the custom item to the list automatically by your plugin.

**Comment by ajtruckle** [comment]
Do I put enlighter as the left value and then TruckleSoft as the right value?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
Do I put **enlighter** as the left value and then **TruckleSoft** as the right value?
> but your "solution" posted above may cause dependency issues and the styles might be broken

Why do you think this may happen? So I can be aware of it.

**Comment by AndiDittrich** [comment]
> Do I put **enlighter** as the left value and then **TruckleSoft** as the right value?

i don't know what you mean

> Why do you think this may happen? So I can be aware of it.

you can't - it's related the the wordpress `enqueue` dependencies.

**Comment by ajtruckle** [comment]
Using `enlighter_theme` ....

**Comment by AndiDittrich** [comment]
* `key` - css theme class
* `value` - label which is displayed in the select boxes

**Comment by ajtruckle** [comment]
Seems to work. Thanks. :) Andrew
