### ISSUE TITLE
Generic Code - Shortcode

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#281]
Hi

I have stumbled over some code on my site (I don't know if it was actually EnlighterJS or not:

```
[generic highlight="1,19-37"]
REQUIRES "Sory by:" AS $strSortBy VALUES "Talk Number,Theme"

// Iterate the available list ot talk categories
LOOP FROM "Public Talk Categories" NODATERANGE SORTBY "Description"

// Insert a gap between each category
IF "$RowNumber" ISNOT "1"
BLANK *1
END_IF

// Display the category description
TAB =3>
FONT BOLD
FIELD "Description"
EOL
FONT NOBOLD

IF "$strSortBy" IS "Talk Number"
// Display all talks assigned to this category
LOOP FROM "Public Talk Titles" NODATERANGE WHERE "Category" IS CURRENT."Category" SORTBY "Talk Number"
FIELD "Talk Number"
TAB =3>
FIELD "Theme"
EOL
END_LOOP
END_IF

IF "$strSortBy" IS "Theme"
// Display all talks assigned to this category
LOOP FROM "Public Talk Titles" NODATERANGE WHERE "Category" IS CURRENT."Category" SORTBY "Theme"
FIELD "Talk Number"
TAB =3>
FIELD "Theme"
EOL
END_LOOP
END_IF

END_LOOP
[/generic]
```
But was this a shortcode used by your earlier version? Since i did not include code snippets before in my forum posts. But now all these generic ones are not showing as generic formatting code any more.

**Comment by AndiDittrich** [comment]
Enlighter supports the "generic" shortcode - but keep in mind that you can remove it by using the filters...

**Comment by ajtruckle** [comment]
I thought it did support it.

![Generic](https://user-images.githubusercontent.com/7985331/86349716-7e949780-bc59-11ea-9fa2-00ab1ded151d.png)

My actual drop-down in the bbPress editor has a generic option still which works. As far as I am aware I have not knowingly removed your shortcode.

**Comment by AndiDittrich** [comment]
are the other language shortcodes working ? did you checked your shortcode settings ?

**Comment by ajtruckle** [comment]
I don't use any other shortcodes. I checked the options as you suggested and they are on:

![Settings](https://user-images.githubusercontent.com/7985331/86350358-76892780-bc5a-11ea-8245-16396de2db0c.png)

That said, I notice the notes there state `[enlighter]` and not `[generic]`.

**Comment by AndiDittrich** [comment]
the settings are looking ok. btw. please read the labels/description -  "Generic shortcode" is not related to "Generic language"

you also need to enable bbPress shortcode processing - without this setting it wont work

**Comment by ajtruckle** [comment]
Thank you. I have selected **Enlighter Low-Level (recommended)** and now the shortcode works. Maybe I lost this setting when I started using the new theme on the website.

Thank you.

**Comment by ajtruckle** [comment]
I notice your comment:

> If you do not need shortcodes (use the Visual-Editor-Integration instead!) it is recommended to disable the shortcode processing for performance reasons.

Maybe in time I will locate all of these `[generic]` instances and convert them to actual code blocks.
