### ISSUE TITLE
Selective highlighting

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#282]
Hi!

I know we can highlight full lines of code.

But do you think it could be possible to highlight just sections of code on a line? For example, something like this:

![Workbook-S-140-PublicTalk-WatchtowerStudy-ServiceTalk-Assignments-v1-Code3](https://user-images.githubusercontent.com/7985331/86531217-4ee2cb00-beb7-11ea-94c0-29a1d8b895a6.png)

**Comment by AndiDittrich** [comment]
Hi,

i didn't see any possibility to implement this within the editor plugins

**Comment by AndiDittrich** [comment]
btw: (imho) you're looking for the wrong solution...your scheme above looks like a custom "language" within XML....the bulletproof solution is to extend the XML language and add additional highlighting tokens to the attributes

**Comment by ajtruckle** [comment]
I understand your idea. In this situation I was not wanting a basic improvement to syntax highlighting style, I just wanted to make clear to the user the components in the XML they needed to pay attention to. Previously I was just some static images like the one I showed you. Now I am using EnlighterJS:

https://www.publictalksoftware.co.uk/sdm_downloads/workbook-s-140-with-weekend-meeting-and-duty-assignments-in-english/

Not to worry. Sounds like too much work.

**Comment by ajtruckle** [comment]
In basic terms I was think of ability to specify the start / end characters for the highlight, I dunno, maybe:

`1[50-60]` would highlight chars 50 to 60 on line 1. I know that it could only be used on a single line by line basis.

But I have no idea of complexity to implement.

**Comment by AndiDittrich** [comment]
the problem is not the implementation within EnlighterJS...the main issues are raised by the editing plugin support..

**Comment by ajtruckle** [comment]
I see, could nit not just be the existing "highlight numbers` edit box? So, instead of just putting in there:

`1,2`

I put:

`1[50-60], 2[60-70]`

Or, some other appropriate container `1{50-60]`. It would still highlight the actual line number bit on the left (if the style sheet is configured to do so).

**Comment by AndiDittrich** [comment]
just putting the lines into an additional textbox is not an issue....other required changes are much larger

**Comment by ajtruckle** [comment]
Understood!
