### ISSUE TITLE
NoHighlight language option

### ISSUE THREAD

**Issue by viktorix** [EnlighterJS/Plugin.WordPress#286]
I wanted to display an error log snippet, so I was looking for an option that has no highlighting. I see that EnlighterJS has a language "[NoHighlight](https://enlighterjs.org/Language.NoHighlight.html)", which doesn't show any highlighting.

WordPress plugin (v4.2) doesn't specifically have NoHighlight option. I'm not sure if this is a bug or by design. I thought I'll report this.

**Comment by AndiDittrich** [comment]
the website is outdated

in v4.2 use "RAW" in v4.3 "Plain Text"

see language mappings within `LanguageManager.php`

**Comment by viktorix** [comment]
Perfect, thanks for the help.
