### ISSUE TITLE
CSS highlighting issue

### ISSUE THREAD

**Issue by viktorix** [EnlighterJS/Plugin.WordPress#287]
One more thing I noticed in a CSS snippet, CSS highlighting seems to be off based on what the [demo shows](https://enlighterjs.org/Language.CSS.html). I also did check in a previous v3, and it was working fine. So something in v4 might have screwed it up. Multiple themes, not just one.

![image](https://user-images.githubusercontent.com/1692600/87232491-78a36280-c38d-11ea-8b4a-e60691abe53b.png)

**Comment by viktorix** [comment]
Before I open a separate issue, this may be related. I noticed ini/conf language highlighting issue: 
![image](https://user-images.githubusercontent.com/1692600/87232841-2dd71a00-c390-11ea-8195-cc07f485812a.png)

I'm comparing this to the demo.

**Comment by AndiDittrich** [comment]
the website is outdated. it contains examples based on EnlighterJS v2

**Comment by AndiDittrich** [comment]
btw. please read the changelogs - EnlighterJS v2 vs v3 and Enlighter Plugin v3 vs v4 - these are completely different projects..

**Comment by viktorix** [comment]
Sorry, I didn't notice the website was for an older version.

**Comment by viktorix** [comment]
Just a quick suggestion, I ended up on the theme demos page by clicking on the link on the plugin's page. Since website is for a completely different version, I would recommend to at least add a notice on the website about that. Maybe point to the correct documentation. 

Thanks again!

**Comment by AndiDittrich** [comment]
the website has been decommissioned yesterday
