### ISSUE TITLE
An issue about customized CSS Selector in Ver4.2

### ISSUE THREAD

**Issue by CokeMine** [EnlighterJS/Plugin.WordPress#288]
Hello,
Since I used "Crayon Syntax Highlighter" as my Highlighting plugin which is no longer support, I changed it to Enlighter.
Here are my settings
CSS block selector: 
`pre.EnlighterJSRAW, pre[class*="lang:"][class~="decode:true"]`
CSS inline selector: 
`code.EnlighterJSRAW, span[class*="lang:"][class~="decode:true"][class~="crayon-inline"]`
It works very well in version 3.11,but when it updates it to 4.2,It has a problem.
![Snipaste_2020-07-19_18-46-35](https://user-images.githubusercontent.com/45122329/87872999-45497f00-c9f0-11ea-9474-aaaac030cc95.png)
So I found this:
In the Ver3.11
![3](https://user-images.githubusercontent.com/45122329/87873055-b5f09b80-c9f0-11ea-9856-5914b871639b.png)
In the Ver4.2
![2](https://user-images.githubusercontent.com/45122329/87873067-c43eb780-c9f0-11ea-9661-2fe38abb0a07.png)
I think """ are replaced to "&quot" in HTML so that JS can not work right.
I would really appreciate it if you can give me a solution.
Thank you.

**Comment by AndiDittrich** [comment]
Hi @CokeMine ,

you can try to use an escape sequence like `\"` - since the configuration is serialized via json this is the expected behaviour.
in case you need special selectors you have to add a custom EnlighterJS init code to your page and disable the default one.

**Comment by AndiDittrich** [comment]
btw. did you've tried the crayon compatibility mode ? it converts everything on the fly

**Comment by CokeMine** [comment]
@AndiDittrich 
Hi,
The compatibility mode works well.Thank you!
