### ISSUE TITLE
Add an option to compile code

### ISSUE THREAD

**Issue by DevelopedByAnurag** [EnlighterJS/Plugin.WordPress#290]
Hey, I have my container and even an API that can be used to send request and get compiled code so is it possible to add this functionality to the plugin by adding API and getting code compiled in realtime ??

**Comment by AndiDittrich** [comment]
not to the open source (php based) version.

cloud based rendering is planed for the paid subscriptions within the pro/enterprise plans

**Comment by DevelopedByAnurag** [comment]
I have my own API Available using HackerEarth I just simply want to integrate that to my website is that possible ?

**Comment by AndiDittrich** [comment]
i'm not sure what you want... Enlighter (including the EnlighterJS library) are created to be an integral part of WordPress.
The javascript library runs on the client side.

**Comment by DevelopedByAnurag** [comment]
Can you suggest me a way if I want to edit the code for EnlighterJS plugin so i can integrate a download code button as well as run code as an option ??

**Comment by AndiDittrich** [comment]
your project sounds more like an "online editor" - EnlighterJS is not intended for this - it has no editing features (and they cannot be added without a lot of rework) - i assume that you're looking for an editor like ace/cloud9 ?

EnlighterJS is available here on GitHub
