### ISSUE TITLE
Please help to fit the theme of centered text，and some other features

### ISSUE THREAD

**Issue by tk-xiong** [EnlighterJS/Plugin.WordPress#291]
My English is poor, so I have to take a screenshot.
Thank you very much.

![image](https://user-images.githubusercontent.com/11442654/88356467-821fc800-cd9a-11ea-816e-8f1cfed73cc9.png)
![image](https://user-images.githubusercontent.com/11442654/88356516-ae3b4900-cd9a-11ea-80e0-39efb251d4db.png)

**Comment by tk-xiong** [comment]
in china， i can't see the Picture， if you can't see the Picture.
i want send e-mail to you.

**Comment by AndiDittrich** [comment]
Hi @tk-xiong ,

no problem, maybe you can use baidu-translate.

* first image: it looks like you've selected the wrong language (left side) - on the right side it looks like standard wordpress "codeblock", not Enlighter
* second image: html markup within a codeblock cannot be used
