### ISSUE TITLE
Global options couldn't be retrieved by the editing plugins as of v4.3.0

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#293]
Hi

Since upgrading. for some reason, the "Show line numbers" is now always un-ticked by default. Has it always be like that? I can't remember!

Thanks.

Andy

**Comment by AndiDittrich** [comment]
which editor ?

**Comment by ajtruckle** [comment]
Oops! TinyMCE inside bbPress.

**Comment by AndiDittrich** [comment]
the default configuration doesn't seems to be applied to the editing plugins

**Comment by ajtruckle** [comment]
Has it always been like that? In my **Appearance** settings it says to show line numbers. So I thought it would default to ticked. Is this something that has changed?

**Comment by AndiDittrich** [comment]
its a bug within the init code....i'm working on a hotfix

**Comment by AndiDittrich** [comment]
fixed in 4.3.1

**Comment by AndiDittrich** [comment]
thx for your report!

**Comment by ajtruckle** [comment]
You're welcome! All good now. :)
