### ISSUE TITLE
Plugin is ignoring permission

### ISSUE THREAD

**Issue by jandrabek** [EnlighterJS/Plugin.WordPress#295]
Hello, in the latest version I tried to use plugin but I suppose without cache directory writable it is not possible. I set permission to 777 and still got the warning. Even tried manual settings for cache and changed directory but is still shows warning of the original cache directory and still isnt working.

**Comment by AndiDittrich** [comment]
Hi  @jandrabek ,

i cannot confirm this issue, therefore i assume some kind of a missconfigured environment:

* is the plugin working and just the warning is thrown ?
* which webserver OS are your using ?
* is SE Linux enabled including additional permission checks ?

**Comment by jandrabek** [comment]
This is my plugin info:
erver
PHP Version: 7.4.8
PHP JSON Extension: available
Server Software: Linux
Components
Enlighter Plugin: 4.3.1 CE
EnlighterJS Version: 3.4.0
TinyMCE Extension: 5.0.1
Gutenberg Extension: 1.0.0
Theme Customizer: 2.3.0
WP-Skeleton Version: 0.24.0
Environment
Cache writeable: false
Shortcode Processor: Enlighter low-level

Plugin is not working at all. Permissions are set but it is not able to detect the change.

**Comment by AndiDittrich** [comment]
is it a shared hosting environment or a custom server stack ?

**Comment by AndiDittrich** [comment]
and how did you installed Enlighter - via the WordPress plugin manager or manually (file upload, wp-cli, ssh) ?

**Comment by jandrabek** [comment]
It is VPN and I tried both - manual and repository installation. Now I have all the plugins uninstalled, changed permission via server web FTP just to be sure there is no problem with Filezilla or Krusader (tried both). Permission is set to 777

**Comment by AndiDittrich** [comment]
what happens after going into the Enlighter settings menu and press "save changes" - are files appearing within the cache directory.

in the past there were some issues regarding custom hosting environments with default selinux profile and/or different users/groups of the php process and the filesystem.

it's definitely no issue with the plugin...
