### ISSUE TITLE
Add Button Below Code

### ISSUE THREAD

**Issue by DevelopedByAnurag** [EnlighterJS/Plugin.WordPress#296]
Hey is there any way to add custom Button Below the code By adding a blank space below containing a button/link.
Where I want to add a Download Link Below the Code combined to EnlighterJS

**Comment by AndiDittrich** [comment]
yes...by changing the EnlighterJS sources.

The much easier way is to use some jQuery element injection

**Comment by DevelopedByAnurag** [comment]
Instead of editing plugin can you suggest any other way edit /add the link from backend?

**Comment by AndiDittrich** [comment]
* use some jQuery element injection
* create a custom shortcode and add it after the Enlighter element.

**Comment by DevelopedByAnurag** [comment]
Okay, I will Go with Jquery  Thanks !!
