### ISSUE TITLE
Compatibility mode not working with Crayon

### ISSUE THREAD

**Issue by r-martins** [EnlighterJS/Plugin.WordPress#301]
Hello folks. First of all, congratulations for the great work so far.
It seems Crayon Compatibility is not working, as previously stated in #136.

I just tested Crayon compatibility with Wordpress 5.5.1 and Enlighter 4.3.1.
I have a post, that was previously using crayon highlighter, and contain the following \<pre\> declaration:

`<pre class="lang:php decode:true" title="app/code/Magenteiro/Observer/Observer/CustomerRegister.php">`

However, even after enabling the plugin and crayon compatibility, the code is still displayed as simple preformatted.
Note I have disabled crayon highlight plugin.

**Comment by AndiDittrich** [comment]
Hi @r-martins 

i'm unable to reproduce your issue - the code snippet above works without any issues within the testing environment.

therefore: please post your Enlighter Config (About -> Debug) and post a link to the post/page including the snippet above, thanks

**Comment by r-martins** [comment]
Thanks again, @AndiDittrich.
Here is my config:

```json
{
    "translation-enabled": true,
    "enlighterjs-init": "inline",
    "enlighterjs-assets-js": true,
    "enlighterjs-assets-themes": true,
    "enlighterjs-assets-themes-external": false,
    "enlighterjs-selector-block": "pre.EnlighterJSRAW",
    "enlighterjs-selector-inline": "code.EnlighterJSRAW",
    "enlighterjs-indent": 4,
    "enlighterjs-ampersandcleanup": true,
    "enlighterjs-linehover": true,
    "enlighterjs-rawcodedbclick": false,
    "enlighterjs-textoverflow": "break",
    "enlighterjs-linenumbers": true,
    "enlighterjs-theme": "enlighter",
    "enlighterjs-retaincss": false,
    "enlighterjs-language": "generic",
    "toolbar-visibility": "default",
    "toolbar-button-raw": true,
    "toolbar-button-copy": true,
    "toolbar-button-window": true,
    "toolbar-button-enlighterjs": true,
    "tinymce-backend": true,
    "tinymce-frontend": false,
    "tinymce-formats": true,
    "tinymce-autowidth": false,
    "tinymce-tabindentation": false,
    "tinymce-keyboardshortcuts": false,
    "tinymce-font": "sourcecodepro",
    "tinymce-fontsize": "0.7em",
    "tinymce-lineheight": "1.4em",
    "tinymce-color": "#000000",
    "tinymce-bgcolor": "#f9f9f9",
    "gutenberg-backend": true,
    "quicktag-backend": false,
    "quicktag-frontend": false,
    "quicktag-mode": "html",
    "shortcode-mode": "disabled",
    "shortcode-inline": true,
    "shortcode-type-generic": true,
    "shortcode-type-language": false,
    "shortcode-type-group": false,
    "shortcode-filter-content": true,
    "shortcode-filter-excerpt": true,
    "shortcode-filter-widget": false,
    "shortcode-filter-comment": false,
    "shortcode-filter-commentexcerpt": false,
    "gfm-enabled": false,
    "gfm-inline": true,
    "gfm-language": "raw",
    "gfm-filter-content": true,
    "gfm-filter-excerpt": true,
    "gfm-filter-widget": false,
    "gfm-filter-comment": false,
    "gfm-filter-commentexcerpt": false,
    "compat-enabled": false,
    "compat-crayon": true,
    "compat-codecolorer": false,
    "compat-type1": false,
    "compat-type2": false,
    "compat-filter-content": true,
    "compat-filter-excerpt": true,
    "compat-filter-widget": false,
    "compat-filter-comment": false,
    "compat-filter-commentexcerpt": false,
    "cache-custom": false,
    "cache-path": "",
    "cache-url": "",
    "dynamic-resource-invocation": false,
    "ext-infinite-scroll": false,
    "ext-ajaxcomplete": false,
    "bbpress-shortcode": false,
    "bbpress-markdown": false
}
```

I don't have a public URL for this because I'm still testing it in local environment. Below you can also find some screenshots.
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/191149/92539973-8474ad80-f286-11ea-9646-d57622105086.png">
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/191149/92540006-9d7d5e80-f286-11ea-93a0-609ac6007536.png">

**Comment by AndiDittrich** [comment]
i see what's going wrong (RTFM :P)

just take a look onto the first tab of the compatibility mode and read it **carefully**

**Comment by r-martins** [comment]
F.. heheh
I'm pretty sure I've enabled it before.. I may have disabled and forgot.
Sorry for that mate. 
(my newbie mode was On, hehe)
