### ISSUE TITLE
Enlighter WP multisite usage

### ISSUE THREAD

**Issue by cxwstar** [EnlighterJS/Plugin.WordPress#302]
> 启用多站点的情况下,加载enlighterjs.min.js和enlighterjs.min.css时,会在文件名称前加上X1_,造成404错误,插件失效
> ![微信截图_20200912052357](https://user-images.githubusercontent.com/70595241/92974214-4eb70b00-f4b8-11ea-9e80-fbdf5c4807df.png)

**google translate:**
When multi-site is enabled, when loading enlighterjs.min.js and enlighterjs.min.css, X1_ will be added before the file name, causing a 404 error and the plug-in failure

**Comment by AndiDittrich** [comment]
please use english or german for support requests!

Enlighter is currently not optimized for multisite usage (some cache sharing issues)

**Comment by cxwstar** [comment]
明知有bug却不解决...

**Comment by AndiDittrich** [comment]
it's not a bug...everything is working within the testing environment and the prefixes are required

请使用英语或德语
