### ISSUE TITLE
Inline code in Gutenberg rich text block

### ISSUE THREAD

**Issue by bluisier** [EnlighterJS/Plugin.WordPress#304]
Hi,

First of all thanks a lot for creating such an amazing syntax highlighter. By far the best I tried on WordPress!

I recently moved one of my website to Gutenberg and I was happy to find that you had a Enlighter Gutenberg block. Unfortunately one thing I was doing a lot in the classic editor was to add some inline code with Enlighter and I couldn't find a way to do the same in Gutenberg without switching to the code editor. So I was wondering if one day you could maybe add this option to the rich text block. It would be really helpful (even if I have no clue how complex it is ti implement such a feature).

All the best and keep up the great work

**Comment by AndiDittrich** [comment]
It's already there but not released yet

- https://github.com/EnlighterJS/Plugin.Gutenberg/blob/master/CHANGES.md
- https://github.com/EnlighterJS/Plugin.WordPress/blob/master/CHANGES.md

**Comment by bluisier** [comment]
Thanks a lot! That made my day :)
