### ISSUE TITLE
Insert code in text editor

### ISSUE THREAD

**Issue by bclothier** [EnlighterJS/Plugin.WordPress#306]
Normally when I edit blog articles, I use text editor; the "visual" is too clunky and cumbersome for me to even want to use it. 

However, there is no button on the text editor to insert the code. Furthermore, the [documentation](https://github.com/EnlighterJS/documentation/tree/master/wordpress) does not really discuss the usage with text editor besides a comment that shortcodes is to be used only there but without any explanation what shortcodes are recognized etc. 

I've resorted to inserting the code via visual editor, switching back to text editor then copying'n'pasting the generated HTML but that feels really clunky....

**Comment by AndiDittrich** [comment]
raw html editing is absolutely not recommended due to filters like wpautop and missing html escape sequences....therefore this kind of editing mode is not documented to avoid issues with regular users/beginners.

a list of all available shortcodes can be found within the contextual help (dynamically generated)

**Comment by bclothier** [comment]
That is unfortunate. We used to use Crayon and it worked even in the text editor. We had to switch to Enlighter since Crayon did not keep itself updated with Wordpress and I'm sorely missing this functionality. I do not want to use the horrid visual editor.

**Comment by AndiDittrich** [comment]
i don't understand your issue.... shortcodes+markdown are designed to be used in text mode. 

additionally Enlighter provides full QuickTag integration (shortcodes or html) for the text editor..just enable it

the shortcode documentation is available on the contextual help tabs

**Comment by AndiDittrich** [comment]
in case it helps: we can remove all shortcode related docs from the contextual help and move it into the documentation

**Comment by bclothier** [comment]
To be honest I completely missed that there are tabs on the top of Enlighter -> Editing section.

Thank you very much. I will give the quicktags a try.

**Comment by AndiDittrich** [comment]
the documentation has been moved to https://github.com/EnlighterJS/documentation/blob/master/editing/Shortcode.md
