### ISSUE TITLE
Gutenberg block error after update 4.4.1

### ISSUE THREAD

**Issue by booraik** [EnlighterJS/Plugin.WordPress#312]
Update Enlighter 4.4.1 and can't edit post block

Cosnole output: 
![image](https://user-images.githubusercontent.com/11221482/96411093-e5e35100-1222-11eb-90ad-e204e226532d.png)

Gutenberg output:
![image](https://user-images.githubusercontent.com/11221482/96411242-1aefa380-1223-11eb-903d-02ab7d036ad5.png)
It's korean. It's means "This block has error and can not  preview"

Platform: CentOS 7
Wordpress: 5.1.6-1.el7.noarch
apache: 2.4.6
php: 5.6.40

**Comment by AndiDittrich** [comment]
please upgrade to WordPress 5.5

**Comment by booraik** [comment]
No more support wordpress 5.1?

**Comment by AndiDittrich** [comment]
the inline editing mode of Gutenberg Editor isn't available in this release, therefore it throws the error

**Comment by booraik** [comment]
Thanks. I'll close this issue
