### ISSUE TITLE
how can I load my own theme config file

### ISSUE THREAD

**Issue by RichardHu714** [EnlighterJS/Plugin.WordPress#313]
Can you add a feature that allowed us to upload my theme config file in enlighter-option-resources tab. 
And also,if would be perfect if the stylesheet in theme customizer can be edited.

**Comment by mfnalex** [comment]
So how can one use an own theme? I've looked everywhere and can't find anything. I cannot even find the included theme files in my wp-content folder

**Comment by AndiDittrich** [comment]
i've posted the answer on your WordPress forums topic
