### ISSUE TITLE
I want to change the theme and colors but it's not working

### ISSUE THREAD

**Issue by khanakia** [EnlighterJS/Plugin.WordPress#315]
Hi,

I am change the default theme here /wp-admin/admin.php?page=enlighter-customizer but it still loads the base theme no matter what and also if i make any changes to the customizer nothing changes.

<img width="965" alt="Screenshot 2020-11-08 at 11 26 49 AM" src="https://user-images.githubusercontent.com/2174170/98458329-542d8a80-21b5-11eb-8384-f4f444649f97.png">

**Comment by khanakia** [comment]
I just figured it out the issue is i cannot scroll the the dropdown is position fixed and there is no vertical scrollbar. So i cannot select the Theme Customizer even if i want to.
Check screenshots please.

<img width="1391" alt="Screenshot 2020-11-08 at 4 42 08 PM" src="https://user-images.githubusercontent.com/2174170/98463459-67564f80-21e1-11eb-810c-6de6c022daff.png">
<img width="1250" alt="Screenshot 2020-11-08 at 4 41 24 PM" src="https://user-images.githubusercontent.com/2174170/98463462-6c1b0380-21e1-11eb-92cc-b232c2f00c56.png">

**Comment by AndiDittrich** [comment]
it seems to be an issue with your browsers theme/plugins. generally the dropdown list is a standard TinyMCE component not part of Enlighter. You can just change the global/standard theme within Enlighter settings or use a bugger window for testing

Firefox 78.04 ESR
![image](https://user-images.githubusercontent.com/1474107/98464019-3fa2bf80-21c0-11eb-9eef-39d0a42a24e3.png)

Chromium 83
![image](https://user-images.githubusercontent.com/1474107/98464067-88f30f00-21c0-11eb-88f7-abee854df349.png)

**Comment by khanakia** [comment]
@AndiDittrich Same issue i just installed a fresh wordpress installation and only plugin i had installed this time was the Classic Editor or Disable Gutenberg. I still cannot scroll please check the screeshots
I tested in Chrome Latest, Opera Latest Web Browser

<img width="1225" alt="Screenshot 2020-11-09 at 12 39 05 PM" src="https://user-images.githubusercontent.com/2174170/98510222-b60af480-2288-11eb-979b-9ca6965e2f29.png">
<img width="1222" alt="Screenshot 2020-11-09 at 12 38 38 PM" src="https://user-images.githubusercontent.com/2174170/98510228-ba371200-2288-11eb-82be-5fe15fb279a2.png">

**Comment by AndiDittrich** [comment]
i believe that you're experience that issue but i'm unable to reproduce it on any test systems.
Again: the UI dialog is not part of the Enlighter.TinyMCE plugin, it's a UI component from TinyMCE (ClassicEditor). Maybe the issue is related to your WordPress theme - check for additional styles (non-tinymce source) applied to the elements

As a workaround, you have multiple possibilities:

1. set the global Enlighter theme to "Theme Customizer"
2. alter the ordering of the language list (see docs/filters)
3. apply your css fix for your site

**Comment by khanakia** [comment]
@AndiDittrich  it's not a theme issue as it's just a fresh wordpress installation with default theme. Anyway i will check and fix the issue with custom css on admin. Thanks fo the support
