### ISSUE TITLE
HTTP 404 - EnlighterJS styles not found (v3)

### ISSUE THREAD

**Issue by mrpmorris** [EnlighterJS/Plugin.WordPress#316]
I am using EnglighterJS (thank you so much!) in my website.

If you use Chrome and you go to this page that uses it:
https://blazor-university.com/components/one-way-binding/

You'll see the following message in the console

>Refused to apply style from 'https://blazor-university.com/wp-content/plugins/enlighter/resources/EnlighterJS.min.css?ver=3.10.0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

And none of the styles are applied.

**Comment by AndiDittrich** [comment]
just try to open the mentioned linked: it returns a http404 - something seems to be wrong on your website (especially with the installed Enlighter plugin).

please update to the latest version (`v4.4.1`) - your version is pretty old.... https://wordpress.org/plugins/enlighter/

**Comment by mrpmorris** [comment]
Not sure why you received a 404, it's working fine now. I've uploaded to 4.4.1 and although I see no errors there is no styling being applied. For example

https://blazor-university.com/components/creating-a-component/

The html at the top should be HTML highlighted

```html
<div>
    <h2>This is my first component</h2>
</div>
```

And when you hover the mouse over it the "Plain text" etc buttons just show up as little empty boxes.

**Comment by AndiDittrich** [comment]
you've selected `wpcustom` as theme but it's not generated (maybe you didn't initialized the customizer) - therefore no styling is applied (only the base layout)

**Comment by mrpmorris** [comment]
Fantastic, thank you for your help!
