### ISSUE TITLE
1 or 2-line spaces in between lines

### ISSUE THREAD

**Issue by marcosbelfastdev** [EnlighterJS/Plugin.WordPress#318]
After upgrading to the latest version on Wordpress 5.5.3, one or 2 spaces are shown even if you set Code Indentation to No Modification.

Components
Enlighter Plugin: 4.4.1 CE
EnlighterJS Version: 3.4.0
TinyMCE Extension: 5.0.1
Gutenberg Extension: 1.1.0
Theme Customizer: 2.3.0
WP-Skeleton Version: 0.27.0

PHP 7.3

**Comment by AndiDittrich** [comment]
That's not a bug, it's the standard html behaviour to shrink multiple whitespaces
