### ISSUE TITLE
Enlighter plugin is showing code as text plane

### ISSUE THREAD

**Issue by refactorizando-web** [EnlighterJS/Plugin.WordPress#319]
Hi, 

I have updated my enlighter plugin version to 4.4.1, and now my code is showing up as a text plane. 
You can see in this page:
https://refactorizando.com/microservicios-spring-cloud-kubernetes/

Regards

**Comment by AndiDittrich** [comment]
the EnlighterJS js resources are missing. try to disable/clear caching plugns

**Comment by AndiDittrich** [comment]
and your theme sources are looking strange: the footer doesn't contain any scripts...i would assume that a call to `wp_footer` is missing

**Comment by refactorizando-web** [comment]
it was a problem with css
