### ISSUE TITLE
highlighting comments

### ISSUE THREAD

**Issue by rrrfer** [EnlighterJS/Plugin.WordPress#320]
Support for highlighting code in the comments to articles has disappeared. What to do?

**Comment by AndiDittrich** [comment]
please provide more informations

* WordPress Version
* Editing method
* Enlighter Debug Output

**Comment by rrrfer** [comment]
I sole the problem by plugin settings
Editing->Shortcodes->FilterTargets->comment text (set the flag)
It works because i use shortcodes.

Thank you.

**Comment by rrrfer** [comment]
Closed
