### ISSUE TITLE
Migrate from CRYON

### ISSUE THREAD

**Issue by DBJDBJ** [EnlighterJS/Plugin.WordPress#321]
# How?

I have a **lot** of WordPress posts with a **lot** of code using CRYON WP plugin. It seems as of today it has a terminal problem with the latest WPress. 

That is mentioned on the plugin official page.

Any ideas or directions ?

Thanks ...

**Comment by AndiDittrich** [comment]
Goto `Enlighter -> Compatibility -> Compatibility Mode` and then `Enlighter -> Compatibility -> Crayon`

**Comment by DBJDBJ** [comment]
Just seen that ... sorry for "rocking the boat" before RTFM :)

**Comment by DBJDBJ** [comment]
And it worketh, of course.
