### ISSUE TITLE
How to change the theme Enlighter is using to color the legacy Crayon blocks?

### ISSUE THREAD

**Issue by DBJDBJ** [EnlighterJS/Plugin.WordPress#322]
I assume I am not even on the right place to ask this question ... Thanks

**Comment by AndiDittrich** [comment]
It's the standard (global) theme

**Comment by DBJDBJ** [comment]
@AndiDittrich  thanks. Now I fancy a slightly bigger front,  How do I make Enlkgiher show the font size I want when it renders the Crayon blocks?

I assume that might be some CSS incantation?

**Comment by AndiDittrich** [comment]
the default theme is used as theme for crayon. you can set it to `wpcustom` (Theme Customizer) and adjust the output.

**Comment by DBJDBJ** [comment]
Ah ok, thanks. Please understand the use case: 10+ years old blog with 500+ posts. Reasonably frequently visited and referenced globaly. Thus by now a big author's time spender. I simply have no time to "sit and learn". Thanks for being so responsive.

**Comment by AndiDittrich** [comment]
You can also get commercial support from my company for special cases
