### ISSUE TITLE
Multisite Support

### ISSUE THREAD

**Issue by b21946606** [EnlighterJS/Plugin.WordPress#327]
Hello,
Plugin doesn't work in multisite
https://technogezgin.com/en/serve-static-assets-with-an-efficient-cache-policy-guide/

**Comment by AndiDittrich** [comment]
it's working with WP MU.

the enlighter css doesn't seems to be generated `en/wp-content/plugins/enlighter/cache/X4_enlighterjs.min.css`

are files existing within the cache directory ?

**Comment by b21946606** [comment]
There are 2 files, 1 of them CSS other 1 is JS. But CSS file has different name

**Comment by b21946606** [comment]
I deleted and installed plugin again. It works now, thanks for that beautiful plugin :)

**Comment by AndiDittrich** [comment]
interesting. did the filename started without the `X.._` prefix ?
did you installed the plugin before enabling mu ?

**Comment by b21946606** [comment]
Yes, installed it before enabling multisite. After enabling MU; probably a bug occured. There was another CSS file (also as i remember this CSS file's name was meaningful). But after i deleted and installed it again it works without any problems 👍
