### ISSUE TITLE
Theme Customizer not changes after changing base theme

### ISSUE THREAD

**Issue by truongan012** [EnlighterJS/Plugin.WordPress#328]
As title, theme customizer is loaded after change the base theme.
I tried to change from enligher to atomic, click on load and save changes as well,
but somehow it does not affect to the website.
![image](https://user-images.githubusercontent.com/13611865/107136420-917cf200-6935-11eb-9443-1d2aadc8f1a1.png)
![image](https://user-images.githubusercontent.com/13611865/107136474-06502c00-6936-11eb-96ce-4d2d1387c5ab.png)

**Comment by AndiDittrich** [comment]
did you load the new base styles into the customizer ?
