### ISSUE TITLE
How to set the max line numbers?

### ISSUE THREAD

**Issue by Kampi** [EnlighterJS/Plugin.WordPress#331]
I have several code snippets on my website which are quite long. Is there a way to tell Enlighter to show a specific number of lines and then add a vertical scrollbar?

(Sorry for that noobish question :) )

**Comment by AndiDittrich** [comment]
short answer: no, use css as intended

**Comment by Kampi** [comment]
> short answer: no, use css as intended

Hi,

thank you. How can I do it?

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/EnlighterJS/issues/87
you can copy the related css from the EnlighterJS sources

**Comment by Kampi** [comment]
Hi,

I have added the code block 

```
.enlighter-collapse {
    &.@{VIEW_STANDARD} {
        overflow-y: auto;
        max-height: 50px;
    }
    &.@{VIEW_CODEGROUP} {
        .enlighter-codegroup-wrapper {
            overflow-y: auto;
            max-height: 50px;
        }
    }

    &.enlighter-collapse-full.@{VIEW_STANDARD} {
        max-height: none;
    }

    &.enlighter-collapse-full.@{VIEW_CODEGROUP} .enlighter-codegroup-wrapper {
        max-height: none;
    }
}
```

to my style.css of my theme (as you wrote), but it doesn´t change the visible lines of my code blocks.

**Comment by AndiDittrich** [comment]
this is not css, it's the less code including the EnlighterJS framework functions - this won't work

**Comment by Kampi** [comment]
It´s working now, but I don´t have a scrollbar. I thought `overflow-y: auto` enables the vertical scrollbar.

**Comment by AndiDittrich** [comment]
it depends on the browser - you can also set it to `scroll` - https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y

**Comment by Kampi** [comment]
mmh both options doesn´t work.

**Comment by AndiDittrich** [comment]
it's working fine within the dev env
![image](https://user-images.githubusercontent.com/1474107/118272627-2d814100-b4c3-11eb-996f-dc004e4accc6.png)

**Comment by philippeflorent** [comment]
this should be an option in Gutenberg

**Comment by AndiDittrich** [comment]
the option is theme related and sets the absolute height (px) of the codeblock
