### ISSUE TITLE
try to add the code

### ISSUE THREAD

**Issue by atnaples** [EnlighterJS/Plugin.WordPress#332]
$query = $db->query("SELECT value FROM `" . DB_PREFIX . "setting` WHERE `key` = 'config_timezone'");
	if ($query->num_rows) {
		date_default_timezone_set($query->row['value']);
	}

.... what I get

  $query = $db->query("SELECT value FROM <code data-enlighter-language="raw" class="EnlighterJSRAW">" . DB_PREFIX . "setting</code> WHERE <code data-enlighter-language="raw" class="EnlighterJSRAW">key</code> = 'config_timezone'");
  if ($query->num_rows) {
    date_default_timezone_set($query->row['value']);
  }

**Comment by AndiDittrich** [comment]
which editing mode you're using ?

**Comment by atnaples** [comment]
Sorry, code PHP

**Comment by AndiDittrich** [comment]
which wordpress editing mode you're using ?

* Gutenberg
* TinyMCE Visual
* TinyMCE plain with shortcodes
* TinyMCE plain with `pre` tags
* Text editor with shortcodes
* Text editor with `pre` tags
