### ISSUE TITLE
Compatibility with PHP 7.x

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.WordPress#336]
Hi

I ran the plugin through a PHP Scanner for 7.3 and it reported:

> ===  Enlighter - Customizable Syntax Highlighter  ===
> File: plugins/enlighter/modules/skltn/SettingsManager.php
> File has mixed line endings; this may cause incorrect results
> 
> File: plugins/enlighter/modules/skltn/SettingsViewHelper.php
> File has mixed line endings; this may cause incorrect results
> 
> File: plugins/enlighter/Enlighter.php
> File has mixed line endings; this may cause incorrect results
>

**Comment by AndiDittrich** [comment]
thanks; but it shouldn't have any effect
