### ISSUE TITLE
how to use host based fonts?

### ISSUE THREAD

**Issue by aminabedi68** [EnlighterJS/Plugin.WordPress#338]
Hi
i use Enlighter in my website, it's working fine but it seems there is no way to load monospaced font directly from the host. system fonts are good but results are different on Android and Windows (for example, chrome on Android doesn't have consolas)

**Comment by AndiDittrich** [comment]
you have to add the required fonts to your theme.

**Comment by aminabedi68** [comment]
thank you @AndiDittrich
