### ISSUE TITLE
Shortcode for showcasing DELETE method renders in the frontend as PUT

### ISSUE THREAD

**Issue by amouratoglou** [EnlighterJS/Plugin.WordPress#344]
Hiya,

first of all thanks for the plugin.

**Description and Screenshot**

as the title says, the issue I have found is that for  the Description Shortcode:
the **DELETE** method is wrongly rendering as a **PUT** on the Frontend.

![Screen Shot 2022-01-07 at 16 31 16](https://user-images.githubusercontent.com/7943759/149006103-fb5c98b8-8e4a-4f17-8ec0-8e9224ea5099.png)

**HTML in the dashboard:**

```
[description method="DELETE"]
<div class="description">
<pre class="EnlighterJSRAW" data-enlighter-language="null">https://sandbox-api.com/v1/Customer/:id</pre>

Customer card delete
</div>
[header]headers[/header]

[header_row txt-bold="Authorization"]Bearer Token[/header_row]

[type]

[header]PATH VARIABLES[/header]

[header_row txt-bold="id"]ID[/header_row]

[/description]
```

**Comment by AndiDittrich** [comment]
hi @amouratoglou 
it doesn't look like an Enlighter issue...it's more like a problem with the nested shortcode/the related plugin.

did you checked the generated markup and the shortcode plugin code ?

**Comment by amouratoglou** [comment]
I was granted full access to the CMS today. I'll have a look and confirm thanks for your time.
