### ISSUE TITLE
PHP Notice in Widget Area WP 5.9.2

### ISSUE THREAD

**Issue by Jolle775** [EnlighterJS/Plugin.WordPress#348]
**Describe the bug**
Notice: wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 5.8.0.) in /www/htdocs/wp-includes/functions.php on line 5768

**WordPress Editing Mode**
Which WordPress editing mode you're using ?

* Gutenberg

**Frontend or Backend Issue**

Only in Backend, Widget Area

**To Reproduce**
Steps to reproduce the behavior: Going into /wp-admin/widgets.php

**Additional context**
Wordpress 5.9.2 - all other Plugins deactivated, Change of Theme same behavior.

**Comment by AndiDittrich** [comment]
thanks, it was caused by the renaming of the internal Gutenberg assets (`wp-editor` has become `wp-block-editor`)
