### ISSUE TITLE
Request : Bash support

### ISSUE THREAD

**Issue by Hightmar** [EnlighterJS/Plugin.WordPress#349]
Hello, 

Thank you for this very complete plugin that does its job very well. 

I have a request though, is it possible to add `Bash` support? 

I don't realize how much work it is for you but it would be great if it was available in the list! 

Thanks

**Comment by AndiDittrich** [comment]
shell/bash is one of the first supported languages - [KunststoffBeschichtung](https://github.com/EnlighterJS/EnlighterJS/blob/master/src/lang/shell.js)
