### ISSUE TITLE
Einstellungen verschwunden

### ISSUE THREAD

**Issue by t251018** [EnlighterJS/Plugin.WordPress#350]
Seit dem letzten Update auf Version 4.5.0 sind die eingestellten Schriftarten und -farben verschwunden... Alles auf "Start" :( Man hüte sich vor Updates!

**Comment by AndiDittrich** [comment]
Von welcher Version erfolgte das Update ? In der 4.5 wurden keinerlei Änderungen am Customizer oder an den Optionen etc vorgenommen (siehe Changelog und Commits).

Die Einstellungen (CSS) aus dem Theme Customizer werden in der `wp_options` Tabelle gespeichert (`enlighter-customizer`) - siehe auch Enlighter -> About -> Debug und können relativ einfach aus einem Backup wiederhergestellt werden.
