### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by ThetaEdra** [EnlighterJS/Plugin.WordPress#352]
When i click on read more at enlighter -> editing -> Frontend Integration i get a 404 on  https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs/TinyMCE.md

I just wanna know how to use it without gutenberg editor but tinymce advanced. 

Also when i use the tools -> code buttons from tinymce it does not work. Seems like the plugins broken. Also cant select a language when doign so like its described ont he WP Plugin Page. Is it outdated?

**Comment by AndiDittrich** [comment]
Thanks for the hint, forgot to update a few doc links since the whole documentation has been moved to https://github.com/EnlighterJS/documentation

EnlighterJS as well as the editor plugins are standalone, nothing is outdated.
