### ISSUE TITLE
</string> are shown automatically

### ISSUE THREAD

**Issue by kensoftphDOTcom** [EnlighterJS/Plugin.WordPress#354]
**Describe the bug**
I am writing a blog post on my website. I have a java code which includes ChoiceBox<String> cb = new ChoiceBox<>(); something like that and there is no problem in the text editor but when I preview the post, it shows the end or closing tag at the end of the code snippet like this: </string> it should not supposed to show a closing tag like that.

Website url: *****

**WordPress Editing Mode**
Using the Classic text editor - No problem.
![Screenshot_1](https://user-images.githubusercontent.com/89630370/183239043-43a492fd-c5ff-4a95-a703-fffbe0a2c348.jpg)

**Comment by AndiDittrich** [comment]
sry but first of all, please provide website link without fu**** ad overlay!

to reproduce your issue i need much more details: which editing method you'r using ? shortcodes (which filter: enlighter or legacy) or raw html ?

such issues are mostly caused by non-escaped html specialchars using raw html editing mode or WordPress shortcode handler

**Comment by kensoftphDOTcom** [comment]
Sorry, I didn't mean to. I just included the URL because I wonder if that could be helpful if you inspect it. Not intended to show ads on your side. I'm so sorry about that, and thank you for removing the URL to avoid others from viewing it.

Please see the attached screenshots; these might help you and I have no idea what you mean by editing method and filters you're looking for. I just use what I see in the classic text editor.
![1](https://user-images.githubusercontent.com/89630370/183278346-bf89d4d9-a328-4900-9613-a24cc32b6843.jpg)
![2](https://user-images.githubusercontent.com/89630370/183278348-5dba12db-8404-4b06-8159-43a238dd1119.jpg)
![3](https://user-images.githubusercontent.com/89630370/183278349-76f84fd8-e240-4ce1-842f-4dc6ad9cdab4.jpg)
![4](https://user-images.githubusercontent.com/89630370/183278352-6e1c12c7-0211-41df-a4f2-0a8598eff97c.jpg)
![5](https://user-images.githubusercontent.com/89630370/183278353-d3916a8b-7f05-48ae-9c51-e4016d694ec9.jpg)
![6](https://user-images.githubusercontent.com/89630370/183278354-8de7729e-ee11-4882-86bc-b4c458b1a180.jpg)
![7](https://user-images.githubusercontent.com/89630370/183278355-620d9a21-a16c-4ea4-981c-aa19fb106804.jpg)
![8](https://user-images.githubusercontent.com/89630370/183278358-80302725-ff33-4c9e-9b80-6c4a115dfc88.jpg)

**Comment by kensoftphDOTcom** [comment]
This code will generate 2 </string> when it's being previewed. Just like I provided on the question.
![Screenshot_2](https://user-images.githubusercontent.com/89630370/183278521-35036a10-23a6-43da-b0c1-74b053ad1f48.jpg)

**Comment by AndiDittrich** [comment]
i'm confused... there is no "preview" function build into the TinyMCE editor (classic editor) - imho thats caused by a 3rd party plugin. please try it within a clean install

**Comment by kensoftphDOTcom** [comment]
Sorry for the confusion. Please take a look at the screenshots.

The first screenshot is currently editing, and the second screenshot is being previewed or output.
![Screenshot_1](https://user-images.githubusercontent.com/89630370/183283682-84921a15-d623-4ac8-b041-7e46a0f9352b.png)
![Screenshot_2](https://user-images.githubusercontent.com/89630370/183283683-9d31ff31-7bf1-4e9c-a95a-7a8ae087f581.png)

**Comment by AndiDittrich** [comment]
just for clarification: you're using the Gutenberg editor with a "Classic" Block, then adding EnlighterJS codeblock via TinyMCE Buttons ? btw. this editing "method" shouldn't be used - there is a native Gutenberg integration/blocks available for EnlighterJS

----

atm i'm unable to reproduce this issue within the testing environment - it must be a third party plugin/theme or page builder issue

**Comment by kensoftphDOTcom** [comment]
Correct.

Thank you very much for your response. Maybe it was a third party plugin issue, and I'm going to investigate this next time.

**Comment by kensoftphDOTcom** [comment]
Hello, I tried the EnlighterJS block to add Java codes just like I showed to you and the issue is still the same.

**Comment by kensoftphDOTcom** [comment]
I didn't use the TinyMCE.

**Comment by AndiDittrich** [comment]
i strongly believe that you're experiencing this issue but i'm unable to reproduce the issue within the dev env.

could you please try it in a clean wordpress enviroment (standard theme, Enlighter plugin - nothing else) - if this is working it's a third party issue (in 99% of all similar cases that was the root cause). to identify the weak theme/plugin enable/disable the others one by one

**Comment by kensoftphDOTcom** [comment]
Oh, I'm sorry. I forgot about the third party issue, my bad. What I did was to try the Enlighther block and didn't investigate the issue by disabling those third party plugins. I will investigate this next time and will update you if the issue persists.
