### ISSUE TITLE
How to make fixed window height with code?

### ISSUE THREAD

**Issue by lumonat** [EnlighterJS/Plugin.WordPress#355]
--

**Comment by AndiDittrich** [comment]
please use **english** or **deutsch** for support requests - otherwise i'm not able to help you

**Comment by lumonat** [comment]
How to make fixed window height with code?


Something is unclear, how can this problem be solved without wrecking? Thank you.

**Comment by AndiDittrich** [comment]
the option `enlighter-collapse` is support by EnlighterJS but not integrated into the wordpress plugin. you have to add the class manually and enable `retainCssClasses` option

**Comment by justanotheranonymoususer** [comment]
> the option `enlighter-collapse` is support by EnlighterJS but not integrated into the wordpress plugin

Why not? Can it be integrated? I updated from SyntaxHighlighter Evolved and it's the only missing functionality

**Comment by AndiDittrich** [comment]
it's currently a feature of the pro/enterprise edition...
