### ISSUE TITLE
Font is not monospaced

### ISSUE THREAD

**Issue by khoitsma** [EnlighterJS/Plugin.WordPress#356]
**Describe the bug**
No matter what font selections I make, the font is not changed -- the font is Trebuchet MS, just like the rest of the page

**WordPress Editing Mode**
Classic Editor

**Wordpress**
WPEngine

**Theme**
Starbay

**Comment by AndiDittrich** [comment]
sounds like your themes css is overriding the EnlighterJS default styles

did you selected "Theme Customizer" as EnlighterJS theme ?

**Comment by khoitsma** [comment]
Andy,

Thank you kindly for your quick response.

It was tricky but I got it.

I deleted the plugin, reinstalled it, and it seems to be working.

   Link: https://www.mathpax.com/aisc-bolt-holes/

I presume the code block has no coloring when printed, as in my case. I've
looked but can't find a statement saying yes or no.

Thanks again,
Karl

**Comment by AndiDittrich** [comment]
sounds like a cache issue with a "optimization" plugin - read the faq and exclude the enlighter resources.

the "color issue" is caused by modern browsers to increase the readability - you can add some css to turn this off (force colorized)
