### ISSUE TITLE
One-line code block hides the Enlighter buttons

### ISSUE THREAD

**Issue by maidentaiwan** [EnlighterJS/Plugin.WordPress#357]
**Describe the bug**
If a code block is just one line long, the Enlighter buttons on the right side are cut off vertically when the block is rendered.

**WordPress Editing Mode**
Classic editor, but it doesn't matter because the problem is at render time.

**Frontend or Backend Issue**
Frontend

**To Reproduce**
See Example code and the screenshot.

**Expected behavior**
Enlighter buttons on the right side should appear.

**Screenshots**
See screenshot to be uploaded

**Example code**
Render this with Block-Code, Plain Text, Standard (Enlighter).

```
/^[achiort]*c[achiort]*$/
```

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04.6 LTS
 - Browser Chrome for Linux
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by maidentaiwan** [comment]
![Screenshot_20221017_103854](https://user-images.githubusercontent.com/4689691/196208188-2e983605-616c-4171-8d58-525352d879cb.png)

**Comment by AndiDittrich** [comment]
see https://github.com/EnlighterJS/documentation/blob/master/Tweaks.md#set-minimal-height-for-single-line-codeblocks

it's the intended behaviour.
