### ISSUE TITLE
All code in one line

### ISSUE THREAD

**Issue by cecilioalvarez** [EnlighterJS/Plugin.WordPress#360]
All lines of code are presented in only one line with the last version of the plugin
here and example
<img width="1043" alt="Captura de pantalla 2022-10-30 a las 17 20 21" src="https://user-images.githubusercontent.com/19729374/198889649-51e68252-0f99-4297-9d3b-f69db33c2a1a.png">

**Comment by AndiDittrich** [comment]
check this within a clean wordpress environment.
it's a third party theme/plugin issue (100%)  - maybe some kind of "html optimization" / "remove whitespaces" etc

**Comment by cecilioalvarez** [comment]
Thanks for All 😊

Enviado desde mi iPhone

**Comment by ruudmens** [comment]
Got exactly the same issue after the last update

**Comment by cecilioalvarez** [comment]
I solved dísabled  several plugins

Enviado desde mi iPhone

**Comment by ruudmens** [comment]
Problem seems to be related to "Easy Table of Contents" plugin. Version  2.0.35.1 of Easy Table of Content fixes the issue.

**Comment by cecilioalvarez** [comment]
Thanks , yes I use this plugin :)
