### ISSUE TITLE
Python "&" is displaying as  "&amp;"   

### ISSUE THREAD

**Issue by pi-plates** [EnlighterJS/Plugin.WordPress#362]
As written:
if (ADC.getEVENTS(addr) & 0x80):

As displaying:
if (ADC.getEVENTS(addr) &amp; 0x80):

**Comment by pi-plates** [comment]
Yes, this is the plugin on wordpress page. You can see it on the code example at:
https://pi-plates.com/adcplate-users-guide/#Events-2

**Comment by AndiDittrich** [comment]
your not using EnlighterJS ..

**Comment by pi-plates** [comment]
The only other plugin I have is Crayon. And if I turn that off, some of my examples are reduced to a single long line of code.

**Comment by AndiDittrich** [comment]
it's not possible not use Enlighter with Crayon - depending on your settings, the compatibility mode should work as expected

**Comment by pi-plates** [comment]
OK, I'll keep playing with it. Thanks.
