### ISSUE TITLE
Not possible to change the size of formatted text

### ISSUE THREAD

**Issue by SuperBoss9** [EnlighterJS/Plugin.WordPress#365]
![image](https://user-images.githubusercontent.com/53711021/213921641-d039da0e-9eb0-474b-88bd-d56925bddcc7.png)
It remains always 1em.

In 'raw stylesheet' I see only the following:
![image](https://user-images.githubusercontent.com/53711021/213921697-cb235cc1-0bbd-4f83-817d-f009feba298b.png)

But everywhere else in the customizer 1.2em is provided.

What can be wrong?

**Comment by AndiDittrich** [comment]
the `.enlighter` related settings are never changed by the customizer - it just creates a custom theme which overrides the defaults.
you may forgot to set the size unit (rem, em) (missing in your screenshot above)

to control the font-size, just set the "token base style" to "1rem"

**Comment by SuperBoss9** [comment]
> the `.enlighter` related settings are never changed by the customizer - it just creates a custom theme which overrides the defaults. you may forgot to set the size unit (rem, em) (missing in your screenshot above)

I'm sorry but I didn't get you. If I select a theme from a list in the set-up. Then use a customizer then will I get a custom CSS which is applied to the site "code tags" or not?
> 
> to control the font-size, just set the "token base style" to "1rem"
Yes, that was my mistake. Now fixed. Thank you :)
