### ISSUE TITLE
Java generic interpreted as html

### ISSUE THREAD

**Issue by simnation** [EnlighterJS/Plugin.WordPress#366]
**Describe the bug**
As of recently, java generics are handled as html code, even within Enlighter blocks. Block looks fine on editing but bad on preview and display. Especially the "<" character seems to cause trouble.
 
Example:  Message<AbstractAgent<?, ?>> msg=new Message<>(this,"Hello World!");
becomes:  Message<abstractagent<?, ?="">> msg=new Message<>(this,"Hello World!");</abstractagent<?,>

**WordPress Editing Mode**
Which WordPress editing mode you're using ?
Gutenberg

**Frontend or Backend Issue**
Frontend

**To Reproduce**
Insert java code for generic class signature in enlighter block.

**Expected behavior**
I would expect clean java code to be displayed.

**Screenshots**

**Example code**
See code blocks here: https://jsimplesim.org/advanced-topics/communication-messaging/
and here: https://jsimplesim.org/basic-tutorial/building-a-model/

**Desktop (please complete the following information):**
Windows 10, Firefox, Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AndiDittrich** [comment]
this is a common issue when using other editing modes then Gutenberg/TinyMCE - are your really using the block editor ? did you tried to reproduce the issue in a clean wordpress environment ?

**Comment by simnation** [comment]
Found the culprit: Disabling WP Optimize solved the issue.

There was no problem until the wordpress update to 6.1. and my provider switching to PHP 8, both occured in Nov/Dec 2022. I am going to look for an other optimizer...

Thanks for your quick response!

**Comment by simnation** [comment]
BTW: I have a very minimalistic plugin environment with vanilla Gutenberg edit, so the editor was not the issue.

**Comment by AndiDittrich** [comment]
i'm unable to reproduce your issue:

**Testcode**

```text
protected Time doEvent(Time time) {
	Message<AbstractAgent<?,?>> msg=new Message<>(this,"Hello World!");
	getInport().write(msg);
	return getTimeOfNextEvent();
}
```

**Editor**

![Screenshot_2023-01-31_09-43-25](https://user-images.githubusercontent.com/1474107/215711272-206c6315-632e-4b71-ad1b-57704fc46c91.png)

**Result**

![Screenshot_2023-01-31_09-43-11](https://user-images.githubusercontent.com/1474107/215711305-5ccaba63-ddad-490a-ad8a-c9c726dfb619.png)

**Frontend HTML (DEV ENV)**

![Screenshot_2023-01-31_09-44-40](https://user-images.githubusercontent.com/1474107/215711439-737eac35-51f1-4c31-8f8e-b157f7cffd36.png)

**Comment by simnation** [comment]
As I said: Obviously it was incompatibility with WP Optimize. I changed to another WP cache and everything works fine.
