### ISSUE TITLE
Copy and Extern action results in extra XML data in output

### ISSUE THREAD

**Issue by HarmVeenstra** [EnlighterJS/Plugin.WordPress#367]
If users copy PowerShell code from blog posts on my website powershellisfun.com, they receive extra XML tags like this in the output:

$codeblock = "<code data-enlighter-language="raw" class="EnlighterJSRAW"></code><code data-enlighter-language="raw" class="EnlighterJSRAW"></code><code data-enlighter-language="raw" class="EnlighterJSRAW"></code>"

The original code was:

$codeblock = "``````"

(Blog post : https://powershellisfun.com/2023/02/01/export-pipeline-output-to-a-markdown-file-using-powershell/)

Another example:

Write-Host ("[Install printer driver(s)]<code data-enlighter-language="n" class="EnlighterJSRAW">n") -ForegroundColor Green

Original code:

Write-Host ("`n[Add printerdriver(s) to Windows]") -ForegroundColor Green

(Blog post: https://powershellisfun.com/2022/12/05/adding-printer-drivers-and-printers-using-microsoft-intune-and-powershell/)

**Comment by HarmVeenstra** [comment]
For example  this code:

Start-Transcript -Path c:\windows\temp\printers.log
#Read printers.csv as input
$Printers = Import-Csv .\printers.csv

#Add all printer drivers by scanning for the .inf files and installing them using pnputil.exe
$infs = get-childitem -Path . -Filter "*.inf" -Recurse -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Fullname

$totalnumberofinfs = $infs.Count
$currentnumber = 1
Write-Host ("[Install printer driver(s)]`n") -ForegroundColor Green
Foreach ($inf in $infs) {
    Write-Host ("[{0}/{1}] Adding inf file {2}" -f $currentnumber, $totalnumberofinfs, $inf) -ForegroundColor Green
    try {
        c:\windows\sysnative\Pnputil.exe /a $inf | Out-Null
    }
    catch {
        try {
            c:\windows\system32\Pnputil.exe /a $inf | Out-Null
        }
        catch {
            C:\Windows\SysWOW64\pnputil.exe /a $inf | Out-Null
        }
    }
    $currentnumber++
}

#Add all installed drivers to Windows using the CSV list for the correct names
$totalnumberofdrivers = ($printers.drivername | Select-Object -Unique).count
$currentnumber = 1
Write-Host ("`n[Add printerdriver(s) to Windows]") -ForegroundColor Green
foreach ($driver in $printers.drivername | Select-Object -Unique) {
    Write-Host ("[{0}/{1}] Adding printerdriver {2}" -f $currentnumber, $totalnumberofdrivers, $driver) -ForegroundColor Green
    Add-PrinterDriver -Name $driver
    $currentnumber++
}


is translated to this

![image](https://user-images.githubusercontent.com/5159742/217652345-098d534b-1152-43d2-9b2e-d91438b14fd9.png)

**Comment by AndiDittrich** [comment]
do you've enabled "markdown" as editing method but still using the visual integration ?

**Comment by HarmVeenstra** [comment]
I did enable MarkDown support in WordPress, yes. I use Enlighter with PowerShell support for better visuals and line numbers. The screenshot above is from what you get when using the Copy button, it adds XML-like tags

**Comment by HarmVeenstra** [comment]
![image](https://user-images.githubusercontent.com/5159742/217655647-678f3bf2-be0e-4c33-ba1f-a0bb1338050b.png)
Looks like this on the WordPress page

**Comment by AndiDittrich** [comment]
disable the markdown support. you cannot use both.

**Comment by HarmVeenstra** [comment]
![image](https://user-images.githubusercontent.com/5159742/217661276-de682c19-3330-44ea-9954-3d94f5228646.png)

Switched it and yes! Thanks, forgot about that!
