### ISSUE TITLE
Copy Code button doesn't do anything in Safari browser on MacOs Ventura

### ISSUE THREAD

**Issue by HarmVeenstra** [EnlighterJS/Plugin.WordPress#368]
**Describe the bug**
Copy button doesn't work in Safari browser

**WordPress Editing Mode**
Gutenberg

**Frontend or Backend Issue**

Frontend

**To Reproduce**
Go to one of my pages on powershellisfun.com, try to copy a piece of script using the Copy button (The plain text en other code in another window do work), nothing happens

**Expected behavior**
Code block copied to clipboard

**Screenshots**
None (Reporting this for another user who uses my site)

**Example code**
https://powershellisfun.com/2023/02/06/toot-on-mastodon-using-api-and-powershell/ in the first code block

```
code...
```

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 
 - Browser Safari
 - Version 
 
 
![image](https://user-images.githubusercontent.com/5159742/218176335-2296abdb-9de5-467b-9a1a-b3455699c2ae.png)

**Additional context**
None

**Comment by AndiDittrich** [comment]
Hi @HarmVeenstra 
i can confirm that it's broken on your website but this is not EnlighterJS related - the sourcecode highlighting is also not working.
everything works as expected within the dev environment (and also on my personal blog).

therefore i would assume that this issue is related to a third party plugin/theme

**Comment by HarmVeenstra** [comment]
Highlighting does work:

![image](https://user-images.githubusercontent.com/5159742/218266915-0afc7432-746d-42fa-99ba-c103f7553b92.png)

But you don't see the colors in DarkMode, that's correct...

I asked somebody to test it for me in Safari on MacOS (Don't have a Mac) if it does work in Light instead of Dark mode

**Comment by HarmVeenstra** [comment]
Removed some old plugins for code highlighting and switched back to 8.0 from 8.1 PHP, it works now :)
