### ISSUE TITLE
Notranslate

### ISSUE THREAD

**Issue by TGMivo** [EnlighterJS/Plugin.WordPress#373]
I dont want that Google translate the code.

I cannot add the second class="notranslate"  its conflict class="EnlighterJSRAW" is

**Comment by AndiDittrich** [comment]
depending on the editing method you can add the class manually. additionally you have to enable the "retain css class" flag within Enlighter advanced settings

**Comment by TGMivo** [comment]
I found another solution :)

```
<div class="notranslate">

</div>
```
