### ISSUE TITLE
Import and export custom configurations

### ISSUE THREAD

**Issue by tanhongit** [EnlighterJS/Plugin.WordPress#375]
I'm sorry if I missed any issue that mentioned this issue.

Because I need to apply this plugin to many different websites but they need to be consistent in custom styles.

I had to customize each color, style, and configuration every time I installed it on a site.
This is very time-consuming and it also is not feasible for me to back up the current configuration (For cases where I need to reuse it later. Perhaps this is also the biggest reason I want this feature).

So I was thinking, can you guys release a new version that has the feature to import and export all the configurations that the user has made?

Thanks!

**Comment by AndiDittrich** [comment]
Dear @tanhongit 

Enlighter is primary designed for individual developers site and not for large scale (commercial) deployments.
Currently there is already the ability to add custom (external) themes as mentioned in the docs. this allows you to create a derived theme which can be used by other blogs (copy+paste the css file).

A build-in import/export function is available within the upcoming pro/enterprise editions

**Comment by tanhongit** [comment]
> Currently there is already the ability to add custom (external) themes as mentioned in the docs. this allows you to create a derived theme which can be used by other blogs (copy+paste the css file).

I got it! I have checked the documentation and just applied it.

> A build-in import/export function is available within the upcoming pro/enterprise editions

Great! I will wait for that.

Thank you! @AndiDittrich
