### ISSUE TITLE
C# 6.0 string interpolation

### ISSUE THREAD

**Issue by devel0** [EnlighterJS/Plugin.WordPress#39]
Follow piece of C# code

``` csharp
Console.WriteLine($"contains element = {Fn(100)}");
```

not receive formatting as for the interpolated string feature of the C# 6.0,
numeric value 100 and all inside double quotes is treated as string.

**Comment by AndiDittrich** [comment]
Dear Lorenzo,

thanks for your feedback - you're right, this feature level is not supported yet.
i will try to add interpolated string highlighting to [EnlighterJS](https://github.com/AndiDittrich/EnlighterJS) v3

best regards, Andi

**Comment by AndiDittrich** [comment]
C# Interpolated String support is added to EnlighterJS v3.0

![enlighterjs_csharp](https://cloud.githubusercontent.com/assets/1474107/16713290/1088cb56-46a3-11e6-9b92-b6f58a06d8c2.jpg)

**Comment by devel0** [comment]
Cool, I will confirm when I receive the plugin update notify on my WordPress site.

Actually it shows I have installed the 3.1 version, but I think wordpress plugin walk with their own version while you referring here to the core library 3.0 I think.
![capture](https://cloud.githubusercontent.com/assets/13405008/16713442/3e10162e-46a8-11e6-9ad4-f4dd4de22154.PNG)


Thanks.

**Comment by AndiDittrich** [comment]
you're right - it will become available with the next core library (Enlighter**JS**) update. this release will be integrated into the next major release of the **Enlighter** WordPress plugin (v4.x)
