### ISSUE TITLE
Json highlighting needs fix

### ISSUE THREAD

**Issue by d-robin** [EnlighterJS/Plugin.WordPress#42]
Hi, I have a JSON on my website which is valid. Though enlighter does not display it appropriately with right coloring.

Please check here - http://adhocshare.tk/hadoop/query-escaped-json-string-hive/
look at the first enlighter box on the page.

**Comment by AndiDittrich** [comment]
Dear robin,

thanks for your report!
of course, it seems to be a bug within the EnlighterJS Language support file. i will fix with the next major release (v3).

best regards, Andi

**Comment by d-robin** [comment]
You are welcome. Patiently waiting for the next release :-)
