### ISSUE TITLE
Prolog syntax

### ISSUE THREAD

**Issue by rrrfer** [EnlighterJS/Plugin.WordPress#48]
Add Prolog syntax please.

**Comment by AndiDittrich** [comment]
In 4.0

**Comment by AndiDittrich** [comment]
I've added basic Prolog support to EnlighterJS v3 - will be released soon

![enlighterjs_prolog](https://user-images.githubusercontent.com/1474107/42732460-3be21e5c-8822-11e8-9fbb-6ddec6345f72.png)
