### ISSUE TITLE
Problem with new line

### ISSUE THREAD

**Issue by rrrfer** [EnlighterJS/Plugin.WordPress#49]
Hello.
Compare such text with bbpress:

> Рассмотрим функцию, выполняющую переворот строки, учитывая, что на вход подано <em>rvalue (временный объект)</em>:
> [cpp]string reverse(string&& str) {
> }[/cpp]
> 
> Тут экономия (более высокая эффективность) обеспечивается за счет того

And

> Рассмотрим функцию, выполняющую переворот строки, учитывая, что на вход подано <em>rvalue (временный объект)</em>:
> [cpp]string reverse(string&& str) {
> }[/cpp]
> Тут экономия (более высокая эффективность) обеспечивается за счет того

If symbol of new line after [/cpp] is absent - so next paragraph was highlight too. 
See example on printscreen.
![2016-09-19 08-03-25](https://cloud.githubusercontent.com/assets/21195729/18620206/aa2d3dde-7e1e-11e6-9046-f42a466668c5.png)

**Comment by AndiDittrich** [comment]
i will check it asap.

**Comment by AndiDittrich** [comment]
i've tried to reproduce the issue using the following testposts:

**post1**
```
Рассмотрим функцию, выполняющую переворот строки, учитывая, что на вход подано rvalue (временный объект):
[cpp]string reverse(string&& str) {
}[/cpp]

Тут экономия (более высокая эффективность) обеспечивается за счет того
```

**post2**
```
Рассмотрим функцию, выполняющую переворот строки, учитывая, что на вход подано rvalue (временный объект):
[cpp]string reverse(string&& str) {
}[/cpp]
Тут экономия (более высокая эффективность) обеспечивается за счет того
```

**post3**
```
Рассмотрим функцию, выполняющую переворот строки, учитывая, что на вход подано rvalue (временный объект):
[cpp]string reverse(string&& str) {
}[/cpp]Тут экономия (более высокая эффективность) обеспечивается за счет того
```

**Result**
Everything looks like excepted ?!

![ghb_47_1](https://cloud.githubusercontent.com/assets/1474107/18662221/a881aa8c-7f19-11e6-8d93-09df023bc663.jpg)
