### ISSUE TITLE
Algolia wordpress Search + Enlighter Plugin Conflict 

### ISSUE THREAD

**Issue by chinolz** [EnlighterJS/Plugin.WordPress#56]
Plugin Conflict with
https://wordpress.org/plugins/search-by-algolia-instant-relevant-results/

**Comment by AndiDittrich** [comment]
Dear chinolz,

thanks for your advice.
could you please provide a more detailed description ?
this is a payed service plugin right ? therefore i cannot investigate the issue by myself

best regards, Andi

**Comment by chinolz** [comment]
Hi, Algolia is a free service (paid is for higher quote usage)

here is the error log

VM1008:23Uncaught TypeError: Cannot read property 'matchedWords' of undefined(…)(anonymous function) @ VM1008:23c @ underscore.min.js?ver=1.8.3:5(anonymous function) @ wp-util.min.js?ver=4.7:1u @ instantsearch-preact.min.js?ver=1.6.0:8value @ instantsearch-preact.min.js?ver=1.6.0:8C @ instantsearch-preact.min.js?ver=1.6.0:7(anonymous function) @ instantsearch-preact.min.js?ver=1.6.0:7A @ instantsearch-preact.min.js?ver=1.6.0:7T @ instantsearch-preact.min.js?ver=1.6.0:7M @ instantsearch-preact.min.js?ver=1.6.0:7O @ instantsearch-preact.min.js?ver=1.6.0:7C @ instantsearch-preact.min.js?ver=1.6.0:7O @ instantsearch-preact.min.js?ver=1.6.0:7R @ instantsearch-preact.min.js?ver=1.6.0:7A @ instantsearch-preact.min.js?ver=1.6.0:7T @ instantsearch-preact.min.js?ver=1.6.0:7M @ instantsearch-preact.min.js?ver=1.6.0:7O @ instantsearch-preact.min.js?ver=1.6.0:7R @ instantsearch-preact.min.js?ver=1.6.0:7U @ instantsearch-preact.min.js?ver=1.6.0:8o @ instantsearch-preact.min.js?ver=1.6.0:7render @ instantsearch-preact.min.js?ver=1.6.0:9(anonymous function) @ instantsearch-preact.min.js?ver=1.6.0:2n @ instantsearch-preact.min.js?ver=1.6.0:6r @ instantsearch-preact.min.js?ver=1.6.0:6value @ instantsearch-preact.min.js?ver=1.6.0:2n.emit @ instantsearch-preact.min.js?ver=1.6.0:5r._handleResponse @ instantsearch-preact.min.js?ver=1.6.0:3n @ instantsearch-preact.min.js?ver=1.6.0:4u @ instantsearch-preact.min.js?ver=1.6.0:5(anonymous function) @ instantsearch-preact.min.js?ver=1.6.0:2

**Comment by chinolz** [comment]
When Enlighter Plugin activated Algolia stops showing results due to conflict

**Comment by AndiDittrich** [comment]
It seems to be an incompatibility in between  **MooTools** (EnlighterJS) and **underscore.js** (instantsearch).
I am sorry, but this **issue cannot be fixed**.

The upcoming EnlighterJS Release v3 is created as standalone application which works without MooTools or jQuery - this means that it will be possible to use Enlighter togehter with Algolia Plugin in the near future
