### ISSUE TITLE
Lisp and Prolog languages

### ISSUE THREAD

**Issue by rrrfer** [EnlighterJS/Plugin.WordPress#67]
Hello. I need lisp and prolog languages.

**Comment by AndiDittrich** [comment]
Dear rrrfer,

new languages will be implemented in EnlighterJS v3 soon - maybe the "Generic Highlighting" will fulfill your requirements in the meantime.

best regards, Andi

**Comment by rrrfer** [comment]
What is about prolog? :)

it would be great if, with the support of new languages, it would be possible to replace all the code tags in a certain sub-forum (bbpress).

For example, now, instead of [prolog] [/ prolog] tags, I'm using raw or plain or something.

That would be nice if all the tags in the forum / prolog / ... I could replace at once ...

**Comment by AndiDittrich** [comment]
I've just added basic Prolog support to EnlighterJS v3

![enlighterjs_prolog](https://user-images.githubusercontent.com/1474107/42732466-6280eeee-8822-11e8-9d7b-73c80f5fa762.png)
