### ISSUE TITLE
c# generics syntax highlighting.

### ISSUE THREAD

**Issue by pete2014** [EnlighterJS/Plugin.WordPress#69]
Hi,

I'm looking for highlighting similar to VS on generics.

example:
 Entity < MyClass > myObject;

In this case the whole of Entity < MyClass > is in the same color but MyClass should be different.

**Comment by AndiDittrich** [comment]
Dear pete2014,

the related [language support file](https://github.com/AndiDittrich/EnlighterJS/blob/master/Source/Language/CSharp.js) does not contain any rules to match such generic patterns. 

i can add these kind of patterns to the upcoming EnlighterJS v3 release which will become available within the next few month.

br, Andi
