### ISSUE TITLE
Cannot publish a post or save draft

### ISSUE THREAD

**Issue by odieardhia** [EnlighterJS/Plugin.WordPress#75]
Hi, I can't publish a post, I even can't save the draft when I insert PHP code.
Here's the code:
`$siteURL = "http://www.google.com/";`
`$googlePagespeedData = file_get_contents("https://www.googleapis.com/pagespeedonline/v2/runPagespeed?url=$siteURL&screenshot=true");`
`$googlePagespeedData = json_decode($googlePagespeedData, true);`
`$screenshot = $googlePagespeedData['screenshot']['data'];`
`$screenshot = str_replace(array('_','-'),array('/','+'),$screenshot); `
`echo "<img src=\"data:image/jpeg;base64,".$screenshot."\" />";`

**Comment by AndiDittrich** [comment]
Hi odieardhia ,

how did you insert the code ? With the Code Insert Dialog or another method ?

Do you have any security plugins installed which may block this (try to disable all other plugins)?

br, Andi

**Comment by odieardhia** [comment]
Yes, I insert the code from Code Insert Dialog.
I did not install any security plugins, 
It works fine when I insert the HTML / CSS code.

**Comment by AndiDittrich** [comment]
please try to disable any other plugins you're may using.

i've tried to reproduce your issue but everything works fine (WordPress 4.8.1, Enlighter 3.4).

generally it sounds like an issue with the editor plugin which may conflicts with another one. does the javascript console shows any errors in your webbrowser ?
