### ISSUE TITLE
Python incorrect syntax highlighting

### ISSUE THREAD

**Issue by chris-relaxing** [EnlighterJS/Plugin.WordPress#79]
I have a line of Python code that should look like this:
![8-18-2017 2-54-29 pm](https://user-images.githubusercontent.com/30215910/29475599-17494166-8426-11e7-8e1e-dabcbff1fee1.png)
But it actually looks like this in Wordpress:
![8-18-2017 3-01-45 pm](https://user-images.githubusercontent.com/30215910/29475662-56c06d1a-8426-11e7-8f13-6ab6354cc520.png)
I circled the problem spot in red. This should not be treated as a string. It should match the first image. Is this just a misunderstanding of Python syntax by the JS highlighter? If so, how do I fix it?

**Comment by AndiDittrich** [comment]
Hi chris,

this looks like a bug within the highlighting engine...it will be fixed soon with EnlighterJS v3

**Comment by chris-relaxing** [comment]
Great! How can I make sure this EnlighterJS v3 update makes its way into my Wordpress when it's ready?

**Comment by AndiDittrich** [comment]
its included in the next major Enlighter Release (v4) - therefore it will be available as WordPress Plugin Upgrade

**Comment by chris-relaxing** [comment]
Excellent! And thank you for your speedy replies.
