### ISSUE TITLE
Typescript support :)

### ISSUE THREAD

**Issue by eestein** [EnlighterJS/Plugin.WordPress#82]
Amazing plugin!
It took me a while to find it, but I did and it is exactly what I was looking for with its visual editor integration.

I have two suggestions:

1. It would be great if you could also add typescript support
    - I'm currently using Javascript, but it's not the best option in my opinion
2. Add a new theme with VSCode dark colors

Great job guys!

**Comment by AndiDittrich** [comment]
Hi eros,

Typescript support is projected for EnlighterJS **v3.x** 

Is the VSCode Theme OpenSource/MIT Licensed ? In this case we can use it..otherwise some changes are required ..

br, Andi

**Comment by eestein** [comment]
@AndiDittrich Hey, thanks for your answer and I'm sorry for the delay!

Awesome, I'll be looking for it. As for the VSCode theme, I'm not sure :/ BUT! VSCode is open source, so I'm assuming... <<<  they are as well. 

https://code.visualstudio.com/docs/getstarted/themes

https://github.com/Microsoft/vscode

https://github.com/Microsoft/vscode/tree/master/extensions


Dark theme: https://github.com/Microsoft/vscode/tree/master/extensions/theme-defaults/themes

Thanks!

**Comment by AndiDittrich** [comment]
just added TypeScript to EnlighterJS v3

## TypeScript ##

![enlighter_typescript](https://user-images.githubusercontent.com/1474107/42734757-bd35f448-8849-11e8-9d63-62966bfb0a21.png)

**Comment by eestein** [comment]
Thank you! :)
