### ISSUE TITLE
Conflict with MixItUp.js v3

### ISSUE THREAD

**Issue by reatlat** [EnlighterJS/Plugin.WordPress#85]
Today I found Issue with js Library [MixItUp3](https://github.com/patrickkunka/mixitup/)

```
mootools-core-yc.js?ver=3.5:4 Uncaught TypeError: Browser.Request is not a constructor
    at mootools-core-yc.js?ver=3.5:4
    at mootools-core-yc.js?ver=3.5:4
(anonymous) @ mootools-core-yc.js?ver=3.5:4
(anonymous) @ mootools-core-yc.js?ver=3.5:4
```
![image](https://user-images.githubusercontent.com/9933516/31489689-c4f0d928-af41-11e7-8093-d14245670686.png)

**Comment by AndiDittrich** [comment]
Hi Alex,
the issue seems to be related to the MooTools Framework and not EnlighterJS nor Enlighter Plugin itself

**Comment by reatlat** [comment]
@AndiDittrich Yes, I think so, but the error comes only if I load MixItUp.js ....

**Comment by AndiDittrich** [comment]
of course...it's an incompatibility... but i'm not able not fix it..
