### ISSUE TITLE
Code breaking issue

### ISSUE THREAD

**Issue by AlexGyver** [EnlighterJS/Plugin.WordPress#96]
Hello, I have some problems with C++ lang. Code like this
  if (colorPot <= 250) {
    byte k = map(colorPot, 0, 250, 0, 255);
    R = 0;
    G = k;
    B = 255;
  } else if (colorPot > 250 && colorPot <= 500) {
    byte k = map(colorPot, 250, 500, 0, 255);
    R = 0;
    G = 255;
    B = 255 - k;
  } else if (colorPot > 500 && colorPot <= 750) {
    byte k = map(colorPot, 500, 750, 0, 255);
    R = k;
    G = 255;
    B = 0;
  } else if (colorPot > 750 && colorPot <= 1023) {
    byte k = map(colorPot, 750, 1023, 0, 255);
    R = 255;
    G = 255 - k;
    B = 0;
  }

looks like this after enlighter

  if (colorPot <= 250) { byte k = map(colorPot, 0, 250, 0, 255); R = 0; G = k; B = 255; } else if (colorPot > 250 && colorPot <= 500) { byte k = map(colorPot, 250, 500, 0, 255); R = 0; G = 255; B = 255 - k; } else if (colorPot > 500 && colorPot <= 750) { byte k = map(colorPot, 500, 750, 0, 255); R = k; G = 255; B = 0; } else if (colorPot > 750 && colorPot <= 1023) {
    byte k = map(colorPot, 750, 1023, 0, 255);
    R = 255;
    G = 255 - k;
    B = 0;
  }

it looks like enlighter is not a big fan of "else if" section.

**Comment by AndiDittrich** [comment]
Hi Alex,

i've tried to reproduce your issue but everything worked as expected:

![enlighter_issue_96](https://user-images.githubusercontent.com/1474107/36631249-eff7f7bc-1974-11e8-93d0-b5c77513d094.jpg)

maybe you have some css rules on your site which overrides the highlighting engine ? maybe you can post a link to your site ?!

best regards, Andi

**Comment by AlexGyver** [comment]
Of course, here http://alexgyver.ru/arduino-algorithms/
section СВЕТОДИОДЫ, inside all of 3 toggles
Also I am using Avada theme and it's framework, maybe problem in them...

**Comment by AlexGyver** [comment]
Yes, i am using page builder...
So, i make some tests. My "toggles" page element breaks your plugin =( Very strange

**Comment by AndiDittrich** [comment]
it doesn't break the plugin.... it breaks the content itself. the Enlighter Visual Editor Plugin just wraps the content into a `<pre>` element with a special class to avoid any kind of side effects with other plugins.

maybe your "toggle" plugin uses a weak regex which removes the linebreaks
